BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithoutProfilesXLation/src/objects/EM_Event_Budget_vod__c.object
<CustomObject>
    <fields>
        <fullName>Budget_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The budget being accessed by the event.</description>
        <label>WBS/CC</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>EM_Budget_vod__c.Status_vod__c</field>
                <operation>equals</operation>
                <value>Available_For_Use_vod</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>EM_Budget_vod__c</referenceTo>
        <relationshipLabel>WBS/CCs</relationshipLabel>
        <relationshipName>EM_Event_Budget_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The activity that is accessing the budget</description>
        <label>Event</label>
        <referenceTo>EM_Event_vod__c</referenceTo>
        <relationshipLabel>WBS/CCs</relationshipLabel>
        <relationshipName>Event_vod</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithoutProfilesXLation/src/objects/EM_Event_vod__c.object
<CustomObject>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/classes/VPROF_All_Activities_Controller.cls
public class VPROF_All_Activities_Controller {
	

	public String needID{get;set;}
	public List<EM_Event_vod__c> activities{get;set;}
	public boolean hasResults{get;set;}
	public Schema.FieldSet myFieldSet{get;set;}

	
	public List<Schema.FieldSetMember> getFields() {
        return Schema.SObjectType.EM_Event_vod__c.fieldSets.getMap().get('Need_Related_Activities').getFields();
    }


	public VPROF_All_Activities_Controller() {
		
		needID = ApexPages.currentPage().getParameters().get('ID');

		List<EM_Event_Budget_vod__c> actBudgets = [SELECT Id,Event_vod__c
					FROM EM_Event_Budget_vod__c WHERE Budget_vod__c = :needId];

		Set<Id> actIds = new Set<Id>();
		for(EM_Event_Budget_vod__c ab : actBudgets){
			actIds.add(ab.Event_vod__c);
		}

		String query = 'SELECT ';
        for(Schema.FieldSetMember f : this.getFields()) {
            query += f.getFieldPath() + ', ';
        }
        query += 'Id FROM EM_Event_vod__c  WHERE Id IN :actIds';
        
        activities = Database.query(query);

		if(activities.size() > 0){
			hasResults = true;
		}else{
			hasResults = false;
		}



	}
}