BMSSimplificationEclipseWS/zEUFULL-PROD-IntegrationFields/src/objects/EM_Attendee_vod__c.object
<CustomObject>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/EM_Attendee_vod__c.object
    <fields>
        <fullName>End_Time_vod__c</fullName>
        <description>End time of the event</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/EM_Attendee_vod__c.object
    <fields>
        <fullName>Start_Time_vod__c</fullName>
        <description>Start time of the event</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/objects/EM_Event_Speaker_vod__c.object
<CustomObject>
    <description>Service Provider at an Activity for Veeva Event Management.</description>
    <fields>
        <fullName>End_Time_vod__c</fullName>
        <description>End time of the event</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time_vod__c</fullName>
        <description>Start time of the event</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event Service Provider</label>
    <nameField>
        <displayFormat>ESP-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Service Providers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithoutProfilesXLation/src/objects/EM_Event_vod__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Event_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links events together in a series.</description>
        <label>Parent Event</label>
        <referenceTo>EM_Event_vod__c</referenceTo>
        <relationshipLabel>EM Events</relationshipLabel>
        <relationshipName>EM_Event_Parent_Event_vod</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

BMSSimplificationEclipseWS/murugesh.naidu@EUFULL-TrackerUpdates/src/objects/EM_Event_vod__c.object
    <fields>
        <fullName>Country_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Country where an event takes place. Used to define event-level rules.</description>
        <label>Funding Country</label>
        <referenceTo>Country_vod__c</referenceTo>
        <relationshipName>EM_Event_Country_vod</relationshipName>
        <type>Lookup</type>
    </fields>

BMSSimplificationEclipseWS/murugesh.naidu@EUFULL-TrackerUpdates/src/objects/EM_Event_vod__c.object
    <fields>
        <fullName>End_Time_vod__c</fullName>
        <description>End time of the event.</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>

BMSSimplificationEclipseWS/murugesh.naidu@EUFULL-TrackerUpdates/src/objects/EM_Event_vod__c.object
    <fields>
        <fullName>Start_Time_vod__c</fullName>
        <description>Start time of the event.</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/objects/Event_Attendee_vod__c.object
<CustomObject>
    <description>This is a child object of Medical Event. One row represents a entity (Account, Contact, User) who has been invited to attended to the Medical Event. The Attendee_vod field is updated by a trigger to insure it always matches the name field of the account, contact, or user on create/update.</description>
    <fields>
        <fullName>EM_Attendee_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used by the system. It must be visible to users of Veeva Event Management.</description>
        <label>Attendee</label>
        <referenceTo>EM_Attendee_vod__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendees_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EM_Event_Speaker_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used by the system. It must be visible to users of Veeva Event Management.</description>
        <label>Event Speaker</label>
        <referenceTo>EM_Event_Speaker_vod__c</referenceTo>
        <relationshipLabel>Event Attendees(Event Speaker)</relationshipLabel>
        <relationshipName>Event_Attendees_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Medical_Event_vod__c</fullName>
        <description>The Medical Event that the Account, Contact, or User is attending.</description>
        <label>Event</label>
        <referenceTo>Medical_Event_vod__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendee_vod</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Meeting Attendee</label>
    <nameField>
        <displayFormat>A{000000000}</displayFormat>
        <label>Attendee Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/objects/Medical_Event_vod__c.object
<CustomObject>
    <description>This object is used to store medical events. It is not related to the base salesforce.com event (calendar event) object. It has one standard child (event attendees), but custom objects can be added as children to track different attributes of medical events. Medical Event is a top level object with its own security and is referred to in the interaction reporting functionality.</description>
    <fields>
        <fullName>Country_Name_vod__c</fullName>
        <description>Country of Medical Event location</description>
        <label>Country Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EM_Event_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used by the system. It must be visible to users of Veeva Event Management.</description>
        <label>Event</label>
        <referenceTo>EM_Event_vod__c</referenceTo>
        <relationshipLabel>Medical Events</relationshipLabel>
        <relationshipName>Medical_Events_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Time_vod__c</fullName>
        <description>End time of the event.</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time_vod__c</fullName>
        <description>Start time of the event.</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/objects/Preferences_vod__c.object
<CustomObject>
    <description>A set of preferences for users or profiles.</description>
    <fields>
        <fullName>Event_Management_User_vod__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to indicate if a user has Veeva Event Management. To turn on Event Management, the user must have read permission to this field. The checkbox does not need to be checked.</description>
        <label>Event Management User</label>
        <type>Checkbox</type>
    </fields>
    <label>Preferences</label>
    <nameField>
        <label>Preferences Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EMSIM-AllTriggers&Apex/src/classes/EMRedirectController.cls
public with sharing class EMRedirectController {
    boolean isStub = false;
    boolean isEMUser = false;
    ApexPages.StandardController controller;
    String attendeeStubId;
    String eventStubId;
    String startTime;
    String endTime;
    String country;
    String retURL;
    String parentId;
    String recordTypeId;
    
    public EMRedirectController(ApexPages.StandardController controller) {
        this.controller = controller;
        isEmUser = Schema.SObjectType.Preferences_vod__c.fields.Event_Management_User_vod__c.isAccessible(); 
        retURL = ApexPages.currentPage().getParameters().get('retURL');
        recordTypeId= ApexPages.currentPage().getParameters().get('RecordType');
        if(isEMUser) {
            sObject record = controller.getRecord();
        	if(isAttendee()) {
                if(record.get('EM_Attendee_vod__c') != null) {
                    isStub = true;
                    attendeeStubId = (String)record.get('EM_Attendee_vod__c');
                } else if (record.get('EM_Event_Speaker_vod__c') != null) {
                    isStub = true;
                    attendeeStubId = (String)record.get('EM_Event_Speaker_vod__c');
                }
            } else if (isMedicalEvent()) {
                if(record.get('EM_Event_vod__c') != null) {
                    isStub = true;
                    eventStubId = (String)record.get('EM_Event_vod__c');
                }
            } else if(isEMEvent()) {
                DateTime tempDateTime;
                if(record.get('Start_Time_vod__c') != null) {
                    tempDateTime = (DateTime)record.get('Start_Time_vod__c');
                    startTime = tempDateTime.format();
                }
                if(record.get('End_Time_vod__c') != null) {
                    tempDateTime = (DateTime)record.get('End_Time_vod__c');
                    endTime = tempDateTime.format();
                }
                if(record.get('Id') != null) {
                    parentId = (String)record.get('Id');
                }
                if(record.get('Country_vod__c') != null) {
                    country = (String)record.get('Country_vod__c');
                }
            }    
        }   
    }

    private boolean isAttendee() {
        return controller.getRecord().getSObjectType().getDescribe().getName() == 'Event_Attendee_vod__c';
    }

    private boolean isMedicalEvent() {
    	return controller.getRecord().getSObjectType().getDescribe().getName() == 'Medical_Event_vod__c';
    }
    
    private boolean isEMEvent() {
        return controller.getRecord().getSObjectType().getDescribe().getName() == 'EM_Event_vod__c';
    }
    
    public PageReference redirectEdit() {      
        if(!isEMUser) {
            if(recordTypeId != null) {
            	return new PageReference('/' + controller.getId() + '/e?retURL=' + retURL +'&nooverride=1&RecordType=' + recordTypeId);     
            } else {
                return new PageReference('/' + controller.getId() + '/e?retURL=' + retURL +'&nooverride=1'); 
            }
        }
        
        if(isStub) {
            if(isAttendee()) {
                return new PageReference('/' + attendeeStubId + '/e?retURL=' + retURL);    
            } else if (isMedicalEvent()) {
                return new PageReference('/' + eventStubId + '/e?retURL=' + retURL);
            }           
        }
        
        if(recordTypeId != null) {
            return new PageReference('/' + controller.getId() + '/e?retURL=' + retURL +'&nooverride=1&RecordType=' + recordTypeId);     
        } else {
            return new PageReference('/' + controller.getId() + '/e?retURL=' + retURL +'&nooverride=1'); 
        }      
    }
    
    public PageReference redirectView() {
        if(!isEMUser) {
            new PageReference('/' + controller.getId() + '?retURL=' + retURL + '&nooverride=1');    
        }
        if(isStub) {
            if(isAttendee()) {
                return new PageReference('/' + attendeeStubId);    
            } else if (isMedicalEvent()) {
                return new PageReference('/' + eventStubId);
            }           
        }
        return new PageReference('/' + controller.getId() + '?retURL=' + retURL + '&nooverride=1'); 
    }
    
    public PageReference redirectNewEventChild() {     
        String eventObjectId = VOD_RedirectUtil.getObjectDurableId('EM_Event_vod');
        String childPageUrl = '/setup/ui/recordtypeselect.jsp?ent=' + EncodingUtil.urlEncode(eventObjectId.substring(0,15), 'UTF-8');      
        String eventKeyPrefix = controller.getRecord().getSObjectType().getDescribe().getKeyPrefix();
        childPageUrl += '&save_new_url=/'+ eventKeyPrefix + '/e?retURL=' + EncodingUtil.urlEncode('/' + controller.getId(), 'UTF-8');
        if(startTime != null) {
            childPageUrl += '&Start_Time_vod__c=' + startTime;   
        }
        if(endTime != null) {
            childPageUrl += '&End_Time_vod__c=' + endTime;    
        } 
        if(parentId != null) {
            childPageUrl += '&Parent_Event_vod__c=' + parentId;
        }
        if(country != null) {
            Country_vod__c countryObj = [SELECT Country_Name_vod__c FROM Country_vod__c WHERE Id =: country];
            
            childPageUrl += '&parentCountry=' + countryObj.Country_Name_vod__c;
        }
        
        PageReference newChildPage = new PageReference(childPageUrl);
        
        return newChildPage;       
    }
}