BMSSimplificationEclipseWS/zEUFULL-PROD ListViews/src/objects/EM_Budget_vod__c.object
<CustomObject>
</CustomObject>

BMSSimplificationEclipseWS/murugesh.naidu@EUFULL-TrackerUpdates/src/objects/EM_Budget_vod__c.object
    <fields>
        <fullName>Approval_Status_HCPTS__c</fullName>
        <description>Status of the Need Approval Process</description>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Sent For Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Certifier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

BMSSimplificationEclipseWS/murugesh.naidu@EUFULL-TrackerUpdates/src/objects/EM_Budget_vod__c.object
    <fields>
        <fullName>Status_vod__c</fullName>
        <description>Status of a budget. It must be marked as Available for Use to be selected on an event.</description>
        <label>Availability Status</label>
        <picklist>
            <picklistValues>
                <fullName>Available_For_Use_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Service Coordinator Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Pre-Activation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marked For Delete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/classes/HCPTS_ViewApprovalHistController.cls
public with sharing class HCPTS_ViewApprovalHistController {

	public EM_Budget_vod__c theBudget {get;set;}
	public HCPTS_ViewApprovalHistController(ApexPages.StandardController controller){
		
		theBudget = [ Select m.Name, m.Id, m.Approval_Status_HCPTS__c, m.Status_vod__c, 
		             (Select Id, SystemModstamp, ProcessInstanceId, ProcessInstance.Status, OriginalActor.Name, Actor.Name, Comments, CreatedBy.Name, CreatedDate, StepStatus
							 From ProcessSteps order by CreatedDate desc) 
			           From EM_Budget_vod__c m
			           where m.id =: ((EM_Budget_vod__c) controller.getRecord()).Id];		
		
		
	}
}