BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Mobile_ID_vod__c</fullName>
        <description>System field used by mobile products to aid synchronization.</description>
        <externalId>true</externalId>
        <label>Mobile ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Address_vod__c.object
<CustomObject>
    <description>This object stores all addresses for each account profile as well as DEA and State Licenses for physicians.  The State Licenses are maintained across Address records based on the Address_trigger_vod trigger.</description>
    <fields>
        <fullName>Mobile_ID_vod__c</fullName>
        <description>System field used by mobile products to aid synchronization.</description>
        <externalId>true</externalId>
        <label>Mobile ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address line 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/objects/Medical_Event_vod__c.object
<CustomObject>
    <description>This object is used to store medical events. It is not related to the base salesforce.com event (calendar event) object. It has one standard child (event attendees), but custom objects can be added as children to track different attributes of medical events. Medical Event is a top level object with its own security and is referred to in the interaction reporting functionality.</description>
    <fields>
        <fullName>Active_vod__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Once an event is complete, it can be inactivated so that it does not show up in the call reporting picklists.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Address_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to address, filtered based on the selected account for the Medical Event</description>
        <inlineHelpText>Lookup to address, filtered based on the selected account for the Medical Event</inlineHelpText>
        <label>Address</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Address_vod__c.Account_vod__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account_vod__c</valueField>
            </filterItems>
            <filterItems>
                <field>Address_vod__c.Inactive_vod__c</field>
                <operation>notEqual</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Address_vod__c</referenceTo>
        <relationshipLabel>Medical Events</relationshipLabel>
        <relationshipName>Medical_Events_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approved_Agenda_Number__c</fullName>
        <label>Approved Agenda Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Associated_Budget_BMS_CORE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Budget</label>
        <referenceTo>Budget_BMS_CORE__c</referenceTo>
        <relationshipName>Event_Management</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget</label>
        <referenceTo>Budget_BMS_CORE__c</referenceTo>
        <relationshipName>Budget</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City_BMS__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_BMS__c</fullName>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description_vod__c</fullName>
        <description>This field is used to store a description of the Medical Event.</description>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Date_vod__c</fullName>
        <description>The ending date of the event. If not specified, the ending date is assumed to be the same as the starting date.</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Number_BMS__c</fullName>
        <description>Event Number to uniquely identify an Event</description>
        <externalId>true</externalId>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Event_Stage_BMS__c</fullName>
        <label>Event Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Planning2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>This is a sample custom field for event type with no special processing.</description>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Corporate Support Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OLA Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lunch and Learn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accredited</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expense_Amount_vod__c</fullName>
        <description>Holds the amount of the expense of this event.</description>
        <label>Expense Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expense_Post_Status_vod__c</fullName>
        <description>Holds a Success or Fail status based on the attempt to post this event into Concur. If the expense was not yet posted, the status will be null.</description>
        <label>Expense Post Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expense_System_External_ID_vod__c</fullName>
        <description>The ID that maps to the expense management system.</description>
        <label>Expense System External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ID_BMS__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Has_Rate_Card__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the Event has a customized rate card. Not needed to be exposed to end user.</description>
        <label>Has Rate Card</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Sample custom field to store location of the event. There is no special processing on this field.</description>
        <inlineHelpText>For Remote Meetings, please detail Audience, Speaker and Broadcast Locations.</inlineHelpText>
        <label>Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_ID_vod__c</fullName>
        <externalId>true</externalId>
        <label>Mobile ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Product__c</fullName>
        <description>Primary company product that this event is related to. This is a sample field with no special processing.</description>
        <label>Primary Product</label>
        <picklist>
            <picklistValues>
                <fullName>ABILIFY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BARACLUDE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ELIQUIS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ERBITUX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ONGLYZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ORENCIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REYATAZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPRYCEL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUSTIVA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YERVOY</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Secondary_Product__c</fullName>
        <description>Secondary company product that this event is related to. This is a sample field with no special processing.</description>
        <label>Secondary Product</label>
        <picklist>
            <picklistValues>
                <fullName>Erbitux</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IXEMPRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YERVOY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NULOJIX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ORENCIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPRYCEL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restolar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cholecap</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Speaker_BMS_CORE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Speaker</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Event_Management</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Speaker_BMS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Speaker</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Medical_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date_vod__c</fullName>
        <description>The start date of the event.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Meeting_Speaker_BMS__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Meeting Speakers</relationshipLabel>
        <relationshipName>Meeting_Speakers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Has_Rate_Card__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Rate Card</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lock_Rate_Card__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lock Rate Card</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Meeting__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Meeting</label>
        <referenceTo>Medical_Event_vod__c</referenceTo>
        <relationshipLabel>Meeting Speakers</relationshipLabel>
        <relationshipName>Meeting_Speakers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mobile_ID_vod__c</fullName>
        <externalId>true</externalId>
        <label>Mobile ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Planned_Expenses_BMS_IC__c</fullName>
        <description>Planned expenses for the speaker rate card</description>
        <label>Planned Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate_Card_Planned_Expenses__c</fullName>
        <description>Planned expenses for rate card without miscellaneous expenses</description>
        <label>Rate Card Planned Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Card</label>
        <referenceTo>Rate_Card__c</referenceTo>
        <relationshipLabel>Meeting Speakers</relationshipLabel>
        <relationshipName>Meeting_Speakers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meeting Speaker</label>
    <nameField>
        <displayFormat>MS-{0000}</displayFormat>
        <label>Meeting Speaker BMS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EMSIM-AllTriggers&Apex/src/classes/EventsManagementContract_BMS.cls
public with sharing class EventsManagementContract_BMS {
    private ApexPages.StandardController controller {get; set;}
    public Date Today { get { return Date.today(); }}
    public Medical_Event_vod__c medicalEvent {get; set;}
    public Account speaker {get; set;}
    public Address_vod__c speakerAddress {get; set;}
    public Id meetingSpeakerId {get; set;}
    public User owner {get; set;}
    public List<Id> territoryIds {get; set;}
    public String ownerTerritory {get; set;}
    public String renderAs {get;set;}
    public Meeting_Speaker_BMS__c meetingSpeaker {get;set;}
    public Boolean renderAsPdf {get;set;}
    public String render {get;set;}
    
    public String getRenderLanguage() {
        return ApexPages.currentPage().getParameters().get('rl');
    }
    
    public EventsManagementContract_BMS(ApexPages.StandardController controller) {
        system.debug('JK - starting honorarium pdf');
        this.renderAsPdf = false;
        this.medicalEvent = new Medical_Event_vod__c();
        this.speaker = new Account();
        this.speakerAddress = new Address_vod__c();
        this.owner = new User();
        this.territoryIds = new List<Id>();
        //initialize the stanrdard controller
        this.controller = controller;
        this.meetingSpeakerId = ((Meeting_Speaker_BMS__c)controller.getRecord()).Id;
        this.meetingSpeaker = [SELECT Account__c, CreatedById, CreatedDate, IsDeleted, IsLocked, LastActivityDate, Has_Rate_Card__c,
                                      LastModifiedById, LastModifiedDate, MayEdit, Meeting__c, Name, OwnerId, Rate_Card__c, 
                                      Id, SystemModstamp, Lock_Rate_Card__c, Planned_Expenses_BMS_IC__c, Rate_Card_Planned_Expenses__c   
                               FROM Meeting_Speaker_BMS__c
                               WHERE Id = :this.meetingSpeakerId];
        //Get details about this medical event
        for (Medical_Event_vod__c me : [SELECT Active_vod__c,Approved_Agenda_Number__c,Associated_Budget_BMS_CORE__c,Budget__c,City_BMS__c,Country_BMS__c,CreatedById,
                                                CreatedDate,Description_vod__c,End_Date_vod__c,Event_Stage_BMS__c, Event_Number_BMS__c,
                                                Event_Type__c,Expense_Amount_vod__c,Expense_Post_Status_vod__c,
                                                Expense_System_External_ID_vod__c,External_ID_BMS__c,Has_Rate_Card__c,Id,
                                                IsDeleted,IsLocked,LastActivityDate,LastModifiedById,LastModifiedDate,Location__c,
                                                MayEdit,Mobile_ID_vod__c,Name,OwnerId,Primary_Product__c,RecordTypeId,Secondary_Product__c,
                                                Speaker_BMS_CORE__c,Speaker_BMS__c,Start_Date_vod__c,State_BMS__c,Status_BMS_CORE__c,
                                                Status_BMS__c,Submit_Expense_vod__c,SystemModstamp,TA_BMS__c,
                                                Total_Expenses_BMS_CORE__c,Website__c 
                                        FROM Medical_Event_vod__c
                                        WHERE Id = :this.meetingSpeaker.Meeting__c]) { 
            this.medicalEvent = me;
        } 
        owner = [SELECT Name, Id
                 FROM User
                 WHERE Id =: this.medicalEvent.OwnerId];
                 
        
                 
        for (UserTerritory ut : [SELECT Id,TerritoryId,UserId FROM UserTerritory WHERE UserId =: this.medicalEvent.OwnerId]){
            this.territoryIds.add(ut.TerritoryId);
        }
        for (Territory t : [SELECT Name FROM Territory WHERE Id IN :this.territoryIds]){
            if(!String.IsEmpty(t.Name) && t.Name != 'null') {
                system.debug('Territory name: ' + t.Name);
                this.ownerTerritory += t.Name + ', ';
            }
        }
        if (this.ownerTerritory != null) {
            this.ownerTerritory = this.ownerTerritory.Substring(0,this.ownerTerritory.length()-2);  
        }        
                 
        speaker = [SELECT FirstName,LastName,Middle_vod__c,Name, IsPersonAccount
                   FROM Account
                   WHERE ID = :this.meetingSpeaker.Account__c LIMIT 1];
            
        speakerAddress = new Address_vod__c();
        for (Address_vod__c ad : [SELECT Address_line_2_vod__c,City_vod__c,Id,Mailing_vod__c,Name,Primary_vod__c,State_vod__c,Zip_vod__c 
                          FROM Address_vod__c 
                          WHERE Account_vod__c = :this.speaker.Id
                          ORDER BY Primary_vod__c DESC LIMIT 1] ) {
            speakerAddress = ad;                          
        
        }                         
        
    }
    
    public PageReference English() {
        system.debug('jk - firing as english');
        this.renderAs = 'pdf';
        this.renderAsPdf = true;
        if (this.medicalEvent.Event_Type__c == 'Corporate Support Event') {
            this.render = 'englishCorp';
        } else {
            this.render = 'englishHonorarium';
        }
        return ApexPages.currentPage();
    }
    public PageReference French() {
        system.debug('jk - firing as french');
        this.renderAs = 'pdf';
        this.renderAsPdf = true;
        if (this.medicalEvent.Event_Type__c == 'Corporate Support Event') {
            this.render = 'frenchCorp';
        } else {
            this.render = 'frenchHonorarium';
        }
        return ApexPages.currentPage();

    }
}