BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Source_Country_BMS_CORE__c</fullName>
        <label>Account Source Country</label>
        <picklist>
            <picklistValues>
                <fullName>AD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BQ</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Department_BMS_CN__c</fullName>
        <description>Department</description>
        <label>Department</label>
        <picklist>
            <picklistValues>
                <fullName>CCU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BUY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OBG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PCH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GYN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HSUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IHEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>END</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CINT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PHA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HP_Usage_Level_BMS_CN__c</fullName>
        <description>HP Usage Level</description>
        <label>HP Usage Level</label>
        <picklist>
            <picklistValues>
                <fullName>Baraclude Loyalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G-ETV Loyalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lamivudine Trialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Trialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No-MD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>M3_Avg_ETV_ARV_BMS_CN__c</fullName>
        <description>ETV/ARV 3个月平均比例(%) for HP</description>
        <label>3 Months Average ETV/ARV</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>M3_Avg_HP_ETV_BMS_CN__c</fullName>
        <description>HP/ETV 3个月平均比例(%) for HP</description>
        <label>3 Months Average HP/ETV</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>M3_Avg_Lamivudine_ARV_BMS_CN__c</fullName>
        <description>Lamivudine/ARV 3个月平均比例(%) for HP</description>
        <label>3 Months Average Lamivudine/ARV</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Technical_Title_BMS_CN__c</fullName>
        <description>Technical title of the professional</description>
        <label>Technical Title</label>
        <picklist>
            <picklistValues>
                <fullName>E011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E021</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E022</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E023</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E024</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E025</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E026</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E027</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E028</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E029</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E030</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T001</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T002</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T003</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Patient_Tracker_BMS_CN__c.object
<CustomObject>
    <description>Patient Tracker</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patient Tracker</relationshipLabel>
        <relationshipName>Patient_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Baraclude_ETV_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Baraclude patient share among total ETV (%)</description>
        <label>Baraclude patient share among total ETV</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cycle_Period_BMS_CN__c</fullName>
        <description>Cycle Period</description>
        <label>Cycle Period</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ETV_ARV_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <description>ETV patient share among total ARV (%)</description>
        <label>ETV patient share among total ARV</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Lamivudine_ARV_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Lamivudine patient share among total ARV (%)</description>
        <label>Lamivudine patient share among total ARV</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <label>Patient Tracker</label>
    <nameField>
        <displayFormat>PT-{0000000000}</displayFormat>
        <label>Patient Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Product_Metrics_vod__c.object
<CustomObject>
    <description>This object stores all metrics available for all accounts. Each metric is specific to a product, so the logical key is (account, product).</description>
    <fields>
        <fullName>Account_Source_Country_BMS_CORE__c</fullName>
        <formula>TEXT(Account_vod__r.Account_Source_Country_BMS_CORE__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Source Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_vod__c</fullName>
        <description>Account is the master object for product metrics.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Metrics</relationshipLabel>
        <relationshipName>Product_Metrics_vod</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HP_Usage_Level_BMS_CN__c</fullName>
        <description>HP Usage Level</description>
        <label>HP Usage Level</label>
        <picklist>
            <picklistValues>
                <fullName>Baraclude Loyalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G-ETV Loyalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lamivudine Trialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Trialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No-MD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Product Metrics</label>
    <nameField>
        <displayFormat>M-{0000000000}</displayFormat>
        <label>Product Metrics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/classes/BMS_CN_HP_Patient_Tracker_Cal.cls
/*
* Name: BMS_CN_HP_Patient_Tracker_Cal
* Description: Calculate past 3 months average value of HP patient tracker
* Author: Roy Zhang
* Created Date: 06/19/2013
* Last Modified Date: 06/19/2013
*/
global class BMS_CN_HP_Patient_Tracker_Cal implements Database.Batchable<sObject>{
	global String strQuery;
	
	global BMS_CN_HP_Patient_Tracker_Cal() {
		strQuery = 'SELECT'
					+ '     Id,'
					+ '     Department_BMS_CN__c ,'
					+ '     Technical_Title_BMS_CN__c  ,'
					+ '     M3_Avg_ETV_ARV_BMS_CN__c,'
					+ '     M3_Avg_HP_ETV_BMS_CN__c,'
					+ '     M3_Avg_Lamivudine_ARV_BMS_CN__c,'
					+ '     HP_Usage_Level_BMS_CN__c' 
					+ ' FROM'
					+ '     Account'
					+ ' WHERE'
					+ '     IsPersonAccount = true AND' 	
					+ '     Account_Source_Country_BMS_CORE__c = \'CN\'';				
	}
	
	global Database.Querylocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(strQuery);
	}
	
	global void execute(Database.BatchableContext BC, List<sObject> scope){
			
		List<Account> actList = scope;
		Map<Id,Account> actMap = new Map<Id,Account>(actList);
		Set<Id> actIdSet = actMap.keySet();
		
		List<String> periodList = new List<String>();
		periodList.add(getPeriod(-1));
		periodList.add(getPeriod(-2));
		periodList.add(getPeriod(-3));

		List<AggregateResult> ptAggrRlt = [SELECT
											Account__c,
											AVG(Baraclude_ETV_BMS_CN__c) Baraclude_ETV,
											AVG(ETV_ARV_BMS_CN__c) ETV_ARV,
											AVG(Lamivudine_ARV_BMS_CN__c) Lamivudine_ARV
										FROM
											Patient_Tracker_BMS_CN__c
										WHERE
											Account__c IN: actIdSet AND
											Cycle_Period_BMS_CN__c IN: periodList
										GROUP BY
											Account__c];
											
		Map<String,AggregateResult> ptAggrMap = new Map<String,AggregateResult>();
		for(AggregateResult agg: ptAggrRlt) {
			ptAggrMap.put(String.valueOf(agg.get('Account__c')),agg);
		}
		
		List<Product_Metrics_vod__c> pmList = [SELECT
													Id,
													Account_vod__c,
													HP_Usage_Level_BMS_CN__c
												FROM
													Product_Metrics_vod__c
												WHERE
													Account_vod__c IN: actIdSet AND
													Products_vod__r.BU_BMS_CN__c = 'HP'];
											
		for(Account act: actList){
			if(ptAggrMap.containsKey(act.Id)){
				AggregateResult aggResult = ptAggrMap.get(act.Id);
				act.M3_Avg_ETV_ARV_BMS_CN__c = Double.valueOf(aggResult.get('ETV_ARV'));
				act.M3_Avg_HP_ETV_BMS_CN__c = Double.valueOf(aggResult.get('Baraclude_ETV'));
				act.M3_Avg_Lamivudine_ARV_BMS_CN__c = Double.valueOf(aggResult.get('Lamivudine_ARV'));
				
				String HPUasgeLv = '';
				if(act.Department_BMS_CN__c == 'PHA' || act.Technical_Title_BMS_CN__c == 'E015'){
					HPUasgeLv = 'No-MD';
				} else if(act.M3_Avg_ETV_ARV_BMS_CN__c >= 30 && act.M3_Avg_HP_ETV_BMS_CN__c >= 50) {
            		HPUasgeLv = 'Baraclude Loyalist';
          		}else if(act.M3_Avg_ETV_ARV_BMS_CN__c >= 30 && act.M3_Avg_HP_ETV_BMS_CN__c < 50) {
            		HPUasgeLv = 'G-ETV Loyalist';
          		}else if(act.M3_Avg_ETV_ARV_BMS_CN__c < 30 && act.M3_Avg_Lamivudine_ARV_BMS_CN__c >= 25) {
            		HPUasgeLv = 'Lamivudine Trialist';
          		}else if(act.M3_Avg_ETV_ARV_BMS_CN__c == 0) {
            		HPUasgeLv = 'Non-Trialist';
          		}else if(act.M3_Avg_ETV_ARV_BMS_CN__c < 30 && act.M3_Avg_Lamivudine_ARV_BMS_CN__c < 25) {
            		HPUasgeLv = 'Others';
          		}
          		
          		act.HP_Usage_Level_BMS_CN__c = HPUasgeLv;
          		
 				for(Product_Metrics_vod__c pm: pmList) {
 					if(pm.Account_vod__c == act.id){
 						pm.HP_Usage_Level_BMS_CN__c = HPUasgeLv;
 					}
 				} 
			}
		}
		
		update actList;
		update pmList;		
	}
	global void finish(Database.BatchableContext BC) {
		
	}
	
	//Get period
	public String getPeriod(Integer shift) {
		Date nextMonth = Date.Today().addMonths(shift);
	    String s=String.ValueOf(nextMonth);
	    String[] ymd = s.split('-', -1);
	    return (ymd[0]+'/'+ymd[1]);
	}
}