BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/objects/EM_Event_Speaker_vod__c.object
<CustomObject>
    <description>Service Provider at an Activity for Veeva Event Management.</description>
    <fields>
        <fullName>Contract_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to select the contract being applied to a speaker for a particular event for Veeva Event Management.</description>
        <label>zContract</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>$Source.Speaker_vod__c</field>
                <operation>equals</operation>
                <valueField>Contract_vod__c.Speaker_HCPTS__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contract_vod__c.Status_vod__c</field>
                <operation>equals</operation>
                <value>Signed</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract_vod__c</referenceTo>
        <relationshipName>Event_Speakers_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Speaker_Contract_HCPTS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to select the contract being applied to a speaker for a particular event for Veeva Event Management.</description>
        <label>Activity Agreement</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Speaker_vod__c</field>
                <operation>equals</operation>
                <valueField>Contract_vod__c.Speaker_HCPTS__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contract_vod__c.Status_vod__c</field>
                <operation>equals</operation>
                <value>Activated</value>
            </filterItems>
            <filterItems>
                <field>Contract_vod__c.Expired_vod__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Type_HCPTS__c</field>
                <operation>equals</operation>
                <valueField>Contract_vod__c.Service_Type_HCPTS__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contract_vod__c.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Framework Agreement</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Subtype_HCPTS__c</field>
                <operation>equals</operation>
                <valueField>Contract_vod__c.Service_Subtype_HCPTS__c</valueField>
            </filterItems>
            <infoMessage>Only Signed unexpired Activity Agreements for the Speaker matching in Contract type and Subtype are selectable from this screen</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract_vod__c</referenceTo>
        <relationshipName>Event_Speakers_HCPTS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_ICF_HCPTS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related ICF</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3 AND ((4 AND 5) OR (6 AND 7) OR 8)</booleanFilter>
            <filterItems>
                <field>$Source.Speaker_vod__c</field>
                <operation>equals</operation>
                <valueField>Information_Collection_Form__c.Speaker_HCPTS__c</valueField>
            </filterItems>
            <filterItems>
                <field>Information_Collection_Form__c.Status_HCPTS__c</field>
                <operation>equals</operation>
                <value>Signed, Signed Manually</value>
            </filterItems>
            <filterItems>
                <field>Information_Collection_Form__c.Expired_Formula_HCPTS__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Type_HCPTS__c</field>
                <operation>equals</operation>
                <value>Services</value>
            </filterItems>
            <filterItems>
                <field>Information_Collection_Form__c.ICF_Type_HCPTS__c</field>
                <operation>equals</operation>
                <value>HCP/Non-HCP Services, HCO Services</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Type_HCPTS__c</field>
                <operation>equals</operation>
                <value>Sponsorship</value>
            </filterItems>
            <filterItems>
                <field>Information_Collection_Form__c.ICF_Type_HCPTS__c</field>
                <operation>equals</operation>
                <value>Sponsorship</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Type_HCPTS__c</field>
                <operation>equals</operation>
                <value>Events</value>
            </filterItems>
            <infoMessage>Only Signed unexpired ICFs are available for selection from this screen corresponding to the Contract type and Subtypes</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Information_Collection_Form__c</referenceTo>
        <relationshipName>Event_Speakers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Type_HCPTS__c</fullName>
        <description>Helps categorize a Contract per BMS Service Type. Please note: Long-term &amp; Short-term apply to Services Contract. Short-term contracts do not include an MSA while Long-term contracts do when Contracts are sent out to HCP. Events and Sponsorship Contract types applies to Exhibits &amp; Sponsorship activities respectively.</description>
        <inlineHelpText>Helps categorize a Contract per BMS Service Type. Please note: Long-term &amp; Short-term apply to Services Contract. Short-term contracts do not include an MSA while Long-term contracts do when Contracts are sent out to HCP.</inlineHelpText>
        <label>Contract Type</label>
        <picklist>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Speaker_Contract_HCPTS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Framework Agreement</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contract_vod__c.Speaker_HCPTS__c</field>
                <operation>equals</operation>
                <valueField>$Source.Speaker_vod__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contract_vod__c.Status_vod__c</field>
                <operation>equals</operation>
                <value>Activated</value>
            </filterItems>
            <filterItems>
                <field>Contract_vod__c.Expired_vod__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>Contract_vod__c.Service_Type_HCPTS__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Type_HCPTS__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contract_vod__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Framework Agreement</value>
            </filterItems>
            <infoMessage>Only Signed unexpired Framework Agreements for the Speaker are selectable from this screen</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract_vod__c</referenceTo>
        <relationshipName>Event_Speakers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Speaker_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The speaker for an event.</description>
        <label>Service Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>EM_Speaker_vod__c.Status_vod__c</field>
                <operation>equals</operation>
                <value>Eligible_vod</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>EM_Speaker_vod__c</referenceTo>
        <relationshipName>Speakers_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_vod__c</fullName>
        <description>Status of the speaker for the event.</description>
        <label>Veeva Status</label>
        <picklist>
            <picklistValues>
                <fullName>Nominated_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invited_vod</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cleared_Signature_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Did Not Attend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined_Simple</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Event Service Provider</label>
    <nameField>
        <displayFormat>ESP-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Service Providers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithoutProfilesXLation/src/objects/EM_Speaker_vod__c.object
<CustomObject>
    <fields>
        <fullName>Status_vod__c</fullName>
        <description>The status of a speaker.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Nominated_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired_vod</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Information_Collection_Form__c.object
<CustomObject>
    <fields>
        <fullName>Vendor_HCPTS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Party Reference</label>
        <referenceTo>EM_Vendor_vod__c</referenceTo>
        <relationshipLabel>Information Collection Forms</relationshipLabel>
        <relationshipName>Information_Collection_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Information Collection Form</label>
    <nameField>
        <label>Information Collection Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Information Collection Forms</pluralLabel>
    <recordTypes>
        <fullName>ICF</fullName>
        <active>true</active>
        <description>ICF that is editable</description>
        <label>ICF</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EMSIM-AllTriggers&Apex/src/classes/CustomVeevaUtilities.cls
/* 
* @author - Murugesh Naidu, Veeva Systems Professional Services
* @createdDate - Jul 8, 2013
* @description - CustomVeevaUtilities - contains custom generic helper methods that can be applicable across a spectrum of customizations
*/
public with sharing class CustomVeevaUtilities {

    public static String getDynamicSOQLForAllEligibleFields(Schema.SobjectType sObjType){
        
        if(!sObjType.getDescribe().isQueryable()){
            throw new ApplicationException ('Object ' + sObjType.getDescribe().getName() + ' cannot be queried');
        }
        if(!sObjType.getDescribe().isAccessible()){
            throw new ApplicationException ('Object ' + sObjType.getDescribe().getName() + ' cannot be accessed');
        }
        
        Map<String, Schema.SObjectField> mapFields = sObjType.getDescribe().fields.getMap();
        
        String dynamicSOQL = 'Select ';
        for(Schema.SObjectField aField: mapFields.values()){
            if(aField.getDescribe().isAccessible()){
                dynamicSOQL += aField.getDescribe().getName() ;
                dynamicSOQL += ', ';
            }
        }
        dynamicSOQL = dynamicSOQL.substringBeforeLast(',');
        dynamicSOQL += ' From ' + sObjType.getDescribe().getName();
        System.debug('dynamicSOQL ==>' + dynamicSOQL);
        return dynamicSOQL;
    }
    
    public static String getDynamicChildFieldsSOQL(Schema.ChildRelationship childRelationship, ID parentIdValue){
        String dynamicSOQL = getDynamicSOQLForAllEligibleFields(childRelationship.getChildSObject());
        //apply the where clause to only return child records related to parent
        dynamicSOQL += ' where ' + childRelationship.getField().getDescribe().getName() + ' = \'' + parentIdValue + '\'';
        System.debug('dynamicChild fields SOQL ==>' + dynamicSOQL);
        
        return dynamicSOQL;
    }
    
    public static Schema.SObjectType getSObjectType(String objectAPIName){
        Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
        return gd.get(objectAPIName);
    }
    
    public static Schema.SObjectField getSObjectField(String objectAPIName, String fieldAPIName){
        Schema.SObjectType sObjType = getSObjectType(objectAPIName);
        Schema.SObjectField sObjField = null;
        if(sObjType!=null){
            sObjField =  sObjType.getDescribe().fields.getMap().get(fieldAPIName);
        }
        return sObjField;
    }
    
    public static Set<String> getFieldTokens(String s, String startKey, String endKey, Boolean includeKeys){
        if(s==null || s.trim() == '' || (!s.contains(startKey) && !s.contains(endKey))){
            return null;
        }
        Set<String> tokenList = new Set<String> ();
        
        while(s.indexOf(startKey)!=-1){
            String theToken = s.substringBetween(startKey,endKey);
            if(includeKeys){
                theToken = startKey + theToken + endKey;
            }
            tokenList.add(theToken);
            s = s.replaceFirst(startKey, '');
            s = s.replaceFirst(endKey, '');
        }
        System.debug('The tokenList = ' + tokenList);
        return tokenList;
    }
        
    public class ApplicationException extends Exception {
        
    }

    // created by Huron Consulting Group 1-20-2016
    public static String updateContractParties(EM_Event_Speaker_vod__c esp){

        if(esp.Related_ICF_HCPTS__c!=null){

            // make sure that the Contact Party on the Framework agreement and the Activity Agreement are
            // updated to match the Contact Party on the ICF
            Information_Collection_Form__c existingIFC = [SELECT Vendor_HCPTS__c FROM Information_Collection_Form__c WHERE Id = :esp.Related_ICF_HCPTS__c];

            List<Id> contractIds = new List<Id>();
            contractIds.add(esp.Event_Speaker_Contract_HCPTS__c);
            contractIds.add(esp.Speaker_Contract_HCPTS__c);

            List<Contract_vod__c> agreements = [SELECT Id,Status_vod__c,Lock_vod__c,Vendor_HCPTS__c FROM Contract_vod__c WHERE Id IN :contractIds];
            List<Contract_vod__c> agreementsToUpdate = new List<Contract_vod__c>();
            for(Contract_vod__c c: agreements){
                if(c.Status_vod__c != 'Activated' && c.Lock_vod__c != true && c.Vendor_HCPTS__c != existingIFC.Vendor_HCPTS__c){
                    c.Vendor_HCPTS__c = existingIFC.Vendor_HCPTS__c;
                    c.Service_Type_HCPTS__c = esp.Service_Type_HCPTS__c;
                    c.Service_Subtype_HCPTS__c = esp.Service_Subtype_HCPTS__c;
                    agreementsToUpdate.add(c);
                }else if((c.Status_vod__c == 'Activated' || c.Lock_vod__c == true) && c.Vendor_HCPTS__c != existingIFC.Vendor_HCPTS__c){
                    return Label.ActiveContractWithWrongContractParty;
                }
            }
            try{
                update agreementsToUpdate;
            }Catch(DmlException e){
                return System.label.VPROF_Error_Updating_Contract_Party + e;
            }
        }

        return 'Success';
    }

    public static String getDynamicSOQLForAllEligibleFieldsWithoutFrom(Schema.SobjectType sObjType){
        
        if(!sObjType.getDescribe().isQueryable()){
            throw new ApplicationException ('Object ' + sObjType.getDescribe().getName() + ' cannot be queried');
        }
        if(!sObjType.getDescribe().isAccessible()){
            throw new ApplicationException ('Object ' + sObjType.getDescribe().getName() + ' cannot be accessed');
        }
        
        Map<String, Schema.SObjectField> mapFields = sObjType.getDescribe().fields.getMap();
        
        String dynamicSOQL = 'Select ';
        for(Schema.SObjectField aField: mapFields.values()){
            if(aField.getDescribe().isAccessible()){
                dynamicSOQL += aField.getDescribe().getName() ;
                dynamicSOQL += ', ';
            }
        }
        dynamicSOQL = dynamicSOQL.substringBeforeLast(',');
        //dynamicSOQL += ' From ' + sObjType.getDescribe().getName();
        System.debug('dynamicSOQL ==>' + dynamicSOQL);
        return dynamicSOQL;
    }
    
    public static List<LockActivityChildren__c> unlockForEdits(String objectAPIName){
        List<LockActivityChildren__c> lockedChildren = [Select Id, EditLock__c, Object__c from LockActivityChildren__c where  Object__c =:objectAPIName and EditLock__c = true];
        for(LockActivityChildren__c c: lockedChildren){
            c.EditLock__c = false;
        }       
        update lockedChildren;
        return lockedChildren;
        
    }
    
    public static void relockForEdits(List<LockActivityChildren__c> childrenToLock){
        for(LockActivityChildren__c c: childrenToLock){
            c.EditLock__c = true;
        }
        update childrenToLock;
        
    }
    
    /**
    */
    @future
    public static void updateEventSpeakerEmployerConsentsAsync(List<ID> eventSpeakerIds){
        List<EM_Event_Speaker_vod__c> eventSpeakers = [Select Id, Name, Employer_Consent_Required_HCPTS__c, Speaker_vod__c
                                                        from EM_Event_Speaker_vod__c
                                                        where Id in: eventSpeakerIds];
        Set<ID> speakerIds = new Set<ID>();
        
        for(EM_Event_Speaker_vod__c esp: eventSpeakers){
            speakerIds.add(esp.Speaker_vod__c);
        }
        
        Map<Id, EM_Speaker_vod__c> speakerMap = new Map<Id, EM_Speaker_vod__c> (
                                                                        [Select Id, Employer_Consent_Required_HCPTS__c 
                                                                        from EM_Speaker_vod__c where id in: speakerIds]) ;
        
        updateEventSpeakerEmployerConsents(eventSpeakers, speakerMap);
        
    }
    /**
    */
    public static void updateEventSpeakerEmployerConsents(List<EM_Event_Speaker_vod__c> eventSpeakers, 
                                                            Map<Id, EM_Speaker_vod__c> speakerMap){
        for(EM_Event_Speaker_vod__c esp: eventSpeakers){
            esp.Employer_Consent_Required_HCPTS__c = speakerMap.get(esp.Speaker_vod__c).Employer_Consent_Required_HCPTS__c;
        }
        List<LockActivityChildren__c> childrenToLock = unlockForEdits('EM_Event_Speaker_vod__c');
        List<Database.SaveResult> SR = Database.update(eventSpeakers, false);
        relockForEdits(childrenToLock);
        System.debug('Update result - ' + SR);
    }

}