BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/objects/Event_Attendee_vod__c.object
<CustomObject>
    <description>This is a child object of Medical Event. One row represents a entity (Account, Contact, User) who has been invited to attended to the Medical Event. The Attendee_vod field is updated by a trigger to insure it always matches the name field of the account, contact, or user on create/update.</description>
    <fields>
        <fullName>Attendee_vod__c</fullName>
        <description>The text of the Person that is selected either in the Account, Contact, or User Lookup.  This is populated by a Trigger on Save.</description>
        <label>Attendee</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Medical_Event_vod__c</fullName>
        <description>The Medical Event that the Account, Contact, or User is attending.</description>
        <label>Event</label>
        <referenceTo>Medical_Event_vod__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendee_vod</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date_vod__c</fullName>
        <description>Start Date for the Medical Event</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Meeting Attendee</label>
    <nameField>
        <displayFormat>A{000000000}</displayFormat>
        <label>Attendee Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/objects/Medical_Event_vod__c.object
<CustomObject>
    <description>This object is used to store medical events. It is not related to the base salesforce.com event (calendar event) object. It has one standard child (event attendees), but custom objects can be added as children to track different attributes of medical events. Medical Event is a top level object with its own security and is referred to in the interaction reporting functionality.</description>
    <fields>
        <fullName>Address_Line_1_BMS_IC__c</fullName>
        <description>Stores Address Line 1 of the event</description>
        <label>Address Line 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approved_Agenda_Number__c</fullName>
        <label>Approved Agenda Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City_BMS__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_BMS__c</fullName>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description_vod__c</fullName>
        <description>This field is used to store a description of the Medical Event.</description>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Date_Time_BMS_IC__c</fullName>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>End_Date_vod__c</fullName>
        <description>The ending date of the event. If not specified, the ending date is assumed to be the same as the starting date.</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Number_BMS__c</fullName>
        <description>Event Number to uniquely identify an Event</description>
        <externalId>true</externalId>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Event_Stage_BMS__c</fullName>
        <label>Event Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Planning2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Event_SubType_BMS_IC__c</fullName>
        <label>Event SubType</label>
        <picklist>
            <controllingField>Primary_Product__c</controllingField>
            <picklistValues>
                <fullName>(NP) Changing our Persp in Met Me</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(PP) Novel Treat Appro in Met.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(SP) Adv in Immuno Onco for Me</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Art of Adherence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Art of Custom Treat for Patie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ATE: INTOLERANCE &amp; SIDE EFFECT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ATE: RESISTANCE/REFRACTORY DISORDER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENDO2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evolving Treat. Algor (CD-Engl Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good STAART TO HAART</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GP/Module/Bipolar Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GP/Module/Mood Disorders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GP/Module/Switching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harness Potential Immu-Onco Opt M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hot topics in RA (CHE prog)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hot topics in RA (iPad appl)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immun Int&apos;l Spkr Tour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Int&apos;l Lit Search in Virology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Journal Clubs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manage Age-related comorbidit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rounds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sleep &amp; HIV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Slide Deck/On-Label</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Videos 2012/Receptor Profiles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Videos 2012/Switching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Virology Int&apos;l Spkr Tour</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>This is a sample custom field for event type with no special processing.</description>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Corporate Support Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OLA Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lunch and Learn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accredited</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FMAS_Meeting_ID_BMS_EMEA__c</fullName>
        <description>VPRO EMEA Mar 2015: Used by FR for their abbreviated process
BMS EMEA - Q1 GRM 2017: Help Text updated as per the new FFM logic defined for France.</description>
        <inlineHelpText>Format is &quot;PBxxxxxx&quot; or N/A for Field Users and
Format is &quot;xxxx-xxx&quot; or N/A for HQ Medical</inlineHelpText>
        <label>FMAS Meeting ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Sample custom field to store location of the event. There is no special processing on this field.</description>
        <inlineHelpText>For Remote Meetings, please detail Audience, Speaker and Broadcast Locations.</inlineHelpText>
        <label>Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_BMS_IC__c</fullName>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Privacy_Statement_BMS_EMEA_AT__c</fullName>
        <description>BMS ACN: March 2015 - Privacy Statement (Country Speciifc) Field used to dipslay Disclaimer on the Print Attendance Sheet during the Meeting Post Execution Phase.</description>
        <label>Privacy Statement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Privacy_Statement_BMS_EMEA_DE__c</fullName>
        <defaultValue>&quot;Im Rahmen Ihrer Teilnahme an der BMS Fortbildungsveranstaltung erhebt die Bristol-Myers Squibb GmbH &amp; Co. KGaA die folgenden personenbezogenen Daten (Daten), um Ihre Teilnahme abzuwickeln und um unser Veranstaltungsprogramm zu bewerten und zu verbessern.Durch das Ausfüllen und Unterzeichnen des Formulars erklären Sie sich damit einverstanden, dass diese Daten zu den oben genannten Zwecken den Gesellschaften der BMS Unternehmensgruppe sowie sorgfältig ausgewählten Dritten, die uns bei der Planung und Durchführung von Veranstaltungen unterstützen, übermittelt und durch diese genutzt und gespeichert werden. Sie können jederzeit eine Kopie Ihrer personenbezogenen Daten erhalten, diese Daten korrigieren lassen oder ihrer weiteren Verarbeitung widersprechen. Kontaktieren Sie hierzu bitte Ihren lokalen BMS Ansprechpartner.&quot;</defaultValue>
        <description>BMS ACN: March 2015 - Privacy Statement (Country Speciifc) Field used to dipslay Disclaimer on the Print Attendance Sheet during the Meeting Post Execution Phase.</description>
        <label>Privacy Statement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Privacy_Statement_BMS_EMEA_ES__c</fullName>
        <defaultValue>&quot;En cumplimiento de lo dispuesto en la Ley Orgánica 15/1999, de 13 de diciembre, de Protección de Datos de Carácter Personal y en su normativa de desarrollo, todos los asistentes abajo indicados autorizan expresamente la inclusión de sus datos personales en los ficheros titularidad de Bristol-Myers Squibb, S.A.U., con domicilio social en el número 15 de la Calle Quintanavides de Madrid, 28050, España (“BMS”), debidamente inscritos en el Registro de la Agencia Española de Protección de Datos con la finalidad de ser utilizados por esta compañía tanto en la gestión de la participación y asistencia como en la mejora y desarrollo de programas educativos. Asimismo, según sea necesario esos datos podrán ser tratados para las finalidades mencionadas por terceros que podrán acceder a los mismos cuando sea necesario para la prestación a BMS de un servicio relacionado con los presentes fines, en los términos del artículo 12 de la citada Ley Orgánica. Dichos proveedores de servicios estarán obligados por contrato a respetar la confidencialidad de la Información y a dar cumplimiento a las exigencias contenidas en la legislación aplicable, todo ello con objeto de proteger sus datos. En todo caso, podrán los asistentes ejercitar en cualquier momento los derechos de acceso, rectificación, cancelación y oposición conforme a la LOPD, dirigiendo a tal efecto la oportuna solicitud por correo electrónico a spain.dataprivacy@bms.com  o por correo postal a Bristol-Myers Squibb, S.A.U., Dpto. Informática, C/ Quintanavides, 15 – Edificio 2 – Planta 2ª, 28050 MADRID. &quot;</defaultValue>
        <description>BMS ACN: March 2015 - Privacy Statement (Country Speciifc) Field used to dipslay Disclaimer on the Print Attendance Sheet during the Meeting Post Execution Phase.</description>
        <label>Privacy Statement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time_BMS_IC__c</fullName>
        <description>Date and time of meeting start</description>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date_vod__c</fullName>
        <description>The start date of the event.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Meeting_Speaker_BMS__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1_BMS_IC__c</fullName>
        <label>Address Line 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_BMS_IC__c</fullName>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Meeting Speaker</label>
    <nameField>
        <displayFormat>MS-{0000}</displayFormat>
        <label>Meeting Speaker BMS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EMSIM-AllTriggers&Apex/src/classes/BMS_EMEA_Print_Attendee_Sheet_FR.cls
public with sharing class BMS_EMEA_Print_Attendee_Sheet_FR{
    private ApexPages.StandardController controller {get; set;}
    public Medical_Event_vod__c medicalEvent {get; set;}
    public List<Event_Attendee_vod__c> eventAttendees {get; set;}
    public List<Account> nullList;
    public List<Meeting_Speaker_BMS__c> meetingSpeaker {get; set;}
    public Id medicalEventID {get; set;}
    public User salesLineUser {get; set;}
    public String startHour {get; set;}
    public String endHour {get; set;}
    public String SpecialtyTA {get; set;}
    public String Institution {get; set;}
    public String Signature {get; set;}
    public String HCPDHG {get; set;}
    public String disclaimer{get; set;}
    public String attendeeHeader{get; set;}
    public String myContacts{get; set;}
    public String blankTableHeader{get; set;}
    
    public String Table3{get; set;}
    public String speakerHeader{get; set;} 
    public String printAttendee{get; set;}     
    public String printAttendee1{get; set;}  
    public String printAttendee2{get; set;}
    public String printAttendee3{get; set;}     
    public String printAttendee4{get; set;}  
    public String printAttendee5{get; set;}
    public String printAttendee6{get; set;}  
    public String printAttendee7{get; set;}
    public String Venue{get; set;}
    public String Speaker{get; set;}
    public String privacyStatement{get; set;}
    public Date myDate { get; set; }
    
    public String imageURL{get;set;}
    public List<Account> getnulllist() {

return [select id from account limit 10];

} 
   
    public BMS_EMEA_Print_Attendee_Sheet_FR(ApexPages.StandardController controller) {
    
            
     Schema.DescribeFieldResult dfr  = Medical_Event_vod__c.Privacy_Statement_BMS_EMEA_AT__c.getDescribe();
     printAttendee  = dfr.getDefaultValueFormula();
     System.debug('printAttendee --->' + dfr.getDefaultValueFormula() );
    
    
    imageURL='/servlet/servlet.FileDownload?file=';
    List< document > documentList=[select name from document where 
                                    Name='BMSLogo']; 
 
    if(documentList.size()>0)
    {
      imageURL=imageURL+documentList[0].id;
    }
        system.debug('JK - starting pdf');
        //initialize the stanrdard controller
        this.controller = controller;
        this.medicalEventId = ((Medical_Event_vod__c)controller.getRecord()).Id;
        
        eventAttendees = new List<Event_Attendee_vod__c>();
        meetingSpeaker = new List<Meeting_Speaker_BMS__c>();
        //displayEventAttendees = new List<DisplayAttendee>();
        
        //Get details about this medical event
        for (Medical_Event_vod__c me : [SELECT Name,Address_Line_1_BMS_IC__c,Approved_Agenda_Number__c,City_BMS__c,Country_BMS__c,FMAS_Meeting_ID_BMS_EMEA__c,
                                               Description_vod__c,End_Date_vod__c,End_Date_Time_BMS_IC__c,Event_Number_BMS__c,Event_Stage_BMS__c,
                                               Event_SubType_BMS_IC__c,Event_Type__c,Location__c,Postal_Code_BMS_IC__c ,
                                               Start_Date_vod__c,Start_Date_Time_BMS_IC__c,Privacy_Statement_BMS_EMEA_DE__c,Privacy_Statement_BMS_EMEA_ES__c,State_BMS__c,Status_BMS_CORE__c,Owner.name,OwnerId,Planned_Start_Date_BMS_EMEA__c,Location_City_BMS_EMEA__c,Name_of_Venue_BMS_EMEA__c,Venue_BMS_IC__c,FFM_Activity_Type_BMS_EMEA__c
                                        FROM Medical_Event_vod__c
                                        WHERE Id = :this.medicalEventId]) {
            salesLineUser = [SELECT Id,BMS_Territory_ID_BMS_SHARED__c FROM User WHERE id = :me.OwnerId LIMIT 1];
            this.medicalEvent = me;
            Venue = me.Location_City_BMS_EMEA__c + me.Name_of_Venue_BMS_EMEA__c ;
                    }
        
        //Event_Attendee_vod__c sea;
        //DisplayAttendee da;
        
        //get event attendees Specialty_1_vod__c
        for (Event_Attendee_vod__c ea : [SELECT Name, Account_vod__r.Name, Account_vod__r.FirstName, Account_vod__r.LastName ,Account_vod__r.Specialty_formula_BMS_EMEA__c ,Account_vod__r.Main_Institution_BMS_EMEA__r.Name,Account_vod__r.Local_ID_BMS_EMEA__c,Account_vod__r.ShippingAddress,Account_vod__r.ShippingStreet,Account_vod__r.ShippingCity,Account_vod__r.ShippingPostalCode,Attendee_vod__c, Attendee_Name_vod__c,Account_vod__r.Specialty_1_vod__c, Signature_vod__c 
                                         FROM Event_Attendee_vod__c
                                         WHERE Medical_Event_vod__c = :this.medicalEventId ORDER BY Account_vod__r.LastName ASC]) {
            system.debug('EA CONTAINS ---------------------->' + ea);
            
            eventAttendees.add(ea);
            
                     
        }
        for(integer i=0; i<5; i++){
        Event_Attendee_vod__c  ea = new Event_Attendee_vod__c();
        eventAttendees.add(ea);
        }
        /*
        Event_Attendee_vod__c  ea = new Event_Attendee_vod__c();
        eventAttendees.add(ea);
        Event_Attendee_vod__c  ea1 = new Event_Attendee_vod__c();
        eventAttendees.add(ea1);
        Event_Attendee_vod__c  ea2 = new Event_Attendee_vod__c();
        eventAttendees.add(ea2);
        Event_Attendee_vod__c  ea3= new Event_Attendee_vod__c();
        eventAttendees.add(ea3);
        Event_Attendee_vod__c  ea4 = new Event_Attendee_vod__c();
        eventAttendees.add(ea4);
       /* Event_Attendee_vod__c  ea5 = new Event_Attendee_vod__c();
        eventAttendees.add(ea5);
        Event_Attendee_vod__c  ea6 = new Event_Attendee_vod__c();
        eventAttendees.add(ea6);
        Event_Attendee_vod__c  ea7 = new Event_Attendee_vod__c();
        eventAttendees.add(ea7);
        Event_Attendee_vod__c  ea8= new Event_Attendee_vod__c();
        eventAttendees.add(ea8);
        Event_Attendee_vod__c  ea9 = new Event_Attendee_vod__c();
        eventAttendees.add(ea9);*/
       // system.debug('JK - eventAttendees: ' + displayEventAttendees);
   //meetingSpeaker = new List<Meeting_Speaker_BMS__c>();
          for (Meeting_Speaker_BMS__c msp : [SELECT Name,Account__r.Name, Account__r.FirstName, Account__r.LastName ,Account__r.Specialty_BMS_EMEA__c,Account__r.Specialty_formula_BMS_EMEA__c,Account__r.Specialty_2_BMS_EMEA__c,Account__r.ShippingCity,Account__r.Main_Institution_BMS_EMEA__r.Name,Account__r.Local_ID_BMS_EMEA__c
                                             FROM Meeting_Speaker_BMS__c
                                             WHERE Meeting__c = :this.medicalEventId ORDER BY Account__r.LastName ASC]) {
            system.debug('EA CONTAINS ---------------------->' + msp);
            
            meetingSpeaker.add(msp); 

            
             

    
    }
            Meeting_Speaker_BMS__c  msp = new Meeting_Speaker_BMS__c();
            meetingSpeaker.add(msp);
            Meeting_Speaker_BMS__c  msp1 = new Meeting_Speaker_BMS__c();
            meetingSpeaker.add(msp1);
            Meeting_Speaker_BMS__c  msp2 = new Meeting_Speaker_BMS__c();
            meetingSpeaker.add(msp2);
            Meeting_Speaker_BMS__c  msp3 = new Meeting_Speaker_BMS__c();
            meetingSpeaker.add(msp3);
            Meeting_Speaker_BMS__c  msp4 = new Meeting_Speaker_BMS__c();
            meetingSpeaker.add(msp4);
    }
    }