BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/objects/Medical_Event_vod__c.object
<CustomObject>
    <description>This object is used to store medical events. It is not related to the base salesforce.com event (calendar event) object. It has one standard child (event attendees), but custom objects can be added as children to track different attributes of medical events. Medical Event is a top level object with its own security and is referred to in the interaction reporting functionality.</description>
    <fields>
        <fullName>Activity_Type_BMS_EMEA__c</fullName>
        <description>VPRO - October 2013 - BMS EMEA Core Requirements &amp; Design: Custom field to capture the Activity Type of a meeting.  This field was created in relation to H20 meetings module for EMEA.</description>
        <label>Activity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Advisory Boards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DA Group Meetings with External Speaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DA MSM Presentation with MSM as Speaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Promotional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Promotional Stand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Serial - Advisory Boards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Serial - Disease Area Group Meetings with External Speaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Serial - Disease Area MSM presentation with MSM as Speaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Serial - Non Promotional Stand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Serial - Other Presentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Serial - Speaker Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Serial - Sponsorship of local HCP to a national/international congress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non serial - Sponsorship of local meeting (Symposium)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Serial - Sponsorship of national or international meeting (symposium)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Non Promotional Meetings in response to an expressed need</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Representative Presentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P2P Discussion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serial - Disease Area Group Meetings with External Speaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serial - Disease Area MSM presentation with MSM as Speaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serial - Other Presentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serial - Speaker Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speaker Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship of Hospital meetings (stand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship of local meetings (stand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRP - Opportunity Meetings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRP - Staff Meetings</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Address_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to address, filtered based on the selected account for the Medical Event</description>
        <inlineHelpText>Lookup to address, filtered based on the selected account for the Medical Event</inlineHelpText>
        <label>Address</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Address_vod__c.Account_vod__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account_vod__c</valueField>
            </filterItems>
            <filterItems>
                <field>Address_vod__c.Inactive_vod__c</field>
                <operation>notEqual</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Address_vod__c</referenceTo>
        <relationshipLabel>Medical Events</relationshipLabel>
        <relationshipName>Medical_Events_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attachment_Validated_BMS_EMEA__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Have all required files been attached?</inlineHelpText>
        <label>Attachment Validated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country_MasterFile_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: Country of the Meeting, populated from the Master File.</description>
        <formula>TEXT( Master_File_BMS_EMEA__r.Country_BMS_EMEA__c )</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>This is a sample custom field for event type with no special processing.</description>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Corporate Support Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OLA Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lunch and Learn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accredited</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FFM_Activity_Type_BMS_EMEA__c</fullName>
        <description>VPRO 30/10/2013: Activity Type from the parent Master File. Applicable only for Field Force Meetings.</description>
        <formula>TEXT( Master_File_BMS_EMEA__r.Activity_Type_BMS_EMEA__c )</formula>
        <label>Activity Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFM_Step_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field used to match the Master File record with the Document Template object (to expose the required fields)</description>
        <label>FFM Step</label>
        <picklist>
            <picklistValues>
                <fullName>Meeting Planning</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Post-Execution</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Has_All_Documents_BMS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Meeting has all required documents</description>
        <label>Has All Documents</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Rate_Card__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the Event has a customized rate card. Not needed to be exposed to end user.</description>
        <label>Has Rate Card</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MeetingRecordTypeDelete_BMS_EMEA__c</fullName>
        <label>MeetingRecordTypeDelete</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Speaker_BMS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Speaker</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Medical_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_BMS_CORE__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted - Waiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <recordTypes>
        <fullName>BMS_EMEA_2_Meeting_Post_Execution</fullName>
        <active>true</active>
        <description>VPRO Nov 2013: Meeting Post-Execution (2nd step of the Meeting process)</description>
        <label>BMS - EMEA - 2. Meeting Post-Execution</label>
    </recordTypes>
    <recordTypes>
        <fullName>Close_Out</fullName>
        <active>true</active>
        <description>Close out / En fermeture</description>
        <label>4. Close Out</label>
    </recordTypes>
    <recordTypes>
        <fullName>Execution</fullName>
        <active>true</active>
        <description>Execution / En exécution</description>
        <label>3. Execution</label>
    </recordTypes>
    <recordTypes>
        <fullName>Planning</fullName>
        <active>true</active>
        <description>Planning state / En planification</description>
        <label>1. Planning</label>
    </recordTypes>
    <recordTypes>
        <fullName>Planning_2</fullName>
        <active>true</active>
        <description>Under Review / En révision</description>
        <label>2. Under Review</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Meeting_Document_Template__c.object
<CustomObject>
    <description>Template for documents required for Meetings</description>
    <fields>
        <fullName>Activity_Type_BMS_EMEA__c</fullName>
        <label>Activity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Speaker Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P2P Discussion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Representative Presentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Representative Presentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship of local meetings (stand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship of Hospital meetings (stand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship of HCPs to local Congress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advisory Boards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DA Group Meetings with External Speaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DA MSM Presentation with MSM as Speaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Non Promotional Meetings in response to an expressed need</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other External Meetings in response to an expressed need</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FFM_Step_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field used to have different required fields based on the FFM Step</description>
        <label>FFM Step</label>
        <picklist>
            <picklistValues>
                <fullName>Master File</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Post-Execution</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Meeting Document Template</label>
    <nameField>
        <label>Meeting Document Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Document Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Rate_Card__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Corporate Support Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OLA Event</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Rate_Card_Template__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Corporate Support Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OLA Event</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rate Card Template</label>
    <nameField>
        <label>Rate Card Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Card Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/classes/EventsManagement_BMS_EMEA.cls
public with sharing class EventsManagement_BMS_EMEA {
    
    private ApexPages.StandardController controller {get; set;}
    public Medical_Event_vod__c medicalEvent {get; set;}
    public Id medicalEventID {get; set;}
    public String eventStage {get; set;}
    private Account speaker {get; set;}
    public List<DisplayRateCard> displayRateCards {get; set;}
    public List<FixedDisplayRateCard> fixedDisplayRateCards {get; set;} 
    
    private Set<String>  usedDescription =  new set<String>();   //CSABA 2014.07.16.
    //private String VEEVA_MEDEV_MISINGATTACH;
    //private String VEEVA_MEDEV_DUPLICATEATTACH;
    private String BMS_EMEA_MEDEV_MISINGATTACH; //Erik, 2014.08.07.
    private String BMS_EMEA_MEDEV_DUPLICATEATTACH; //Erik, 2014.08.07.
    
    public List<BlueFolder> files {get;set;}   //used in VF page  pageblocktable
    
    public decimal percentComplete {get;set;}
    public Address_vod__c SpeakerSummary {get;set;}
    public decimal totalCostSum {get;set;}
    public String attachmentIdToDelete {get;set;}
    public String approvalStatus {get;set;}
    public Boolean checkAttachmentDelete {get;set;}
    
    public EventsManagement_BMS_EMEA(ApexPages.StandardController controller) {
 
        checkAttachmentDelete = false;
 
        //initialize the stanrdard controller
        this.controller = controller;
        this.medicalEventId = ((Medical_Event_vod__c)controller.getRecord()).Id;
        System.Debug('CSABA:  MedEventID = ' + medicalEventId);
        totalCostSum = 0;
        
        System.Debug('CSABA getting Messages');
        getVeevaMessages(Userinfo.getLanguage());  //CSABA 2014.07.16.
        
        //find medical event record types
        Map<Id,RecordType> recordTypeToName = new Map<Id,RecordType>([SELECT Id, DeveloperName, Name
                                                              FROM RecordType 
                                                              WHERE SobjectType = 'Medical_Event_vod__c']);
        
  //      RecordType MPE_Face = [SELECT Id, DeveloperName, Name FROM RecordType WHERE SobjectType ='Medical_Event_vod__c' and DeveloperName = 'BMS_EMEA_2_Meeting_Post_Execution' limit 1];
        
    
        
        
        //Get details about this medical event
        for (Medical_Event_vod__c me : [SELECT FFM_Activity_Type_BMS_EMEA__c,Activity_Type_BMS_EMEA__c,FFM_Step_BMS_EMEA__c,Country_MasterFile_BMS_EMEA__c,RecordTypeId,Attachment_Validated_BMS_EMEA__c ,MeetingRecordTypeDelete_BMS_EMEA__c, Status_BMS_CORE__c, Speaker_BMS__c, Has_Rate_Card__c, Event_Type__c, Has_All_Documents_BMS__c
                                        FROM Medical_Event_vod__c
                                        WHERE Id = :this.medicalEventId]) {
            this.medicalEvent = me;
        }
        
        // Removed recordtype check to FFM step picklist value.
      //  if(this.medicalEvent.RecordTypeId == MPE_Face.Id){
     //       checkAttachmentDelete = true;
     //   }
        
        if(this.medicalEvent.FFM_Step_BMS_EMEA__c == 'Meeting Post-Execution'){
            checkAttachmentDelete = true;
        }
        
        
        //find what stage we are in
        if (recordTypeToName.get(this.medicalEvent.RecordTypeId) == null) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Record Type Not Found'));
            return;
        }

        this.eventStage = recordTypeToName.get(this.medicalEvent.RecordTypeId).DeveloperName;
        system.debug('JK - eventStage: ' + this.eventStage);
        
        //override stage if in approval
        getApprovalStatus();
        if (this.approvalStatus == 'Pending') 
        {
            this.eventStage = 'Planning_2';
        }
        
        populateBlueFolder();
        /*
        if (this.eventStage == 'Planning') {
            if (this.medicalEvent.Speaker_BMS__c != null) {
                populateRateCard();
                populateSpeakerSummary();
            }
        } else if (this.eventStage == 'Planning_2') {
            populateRateCard();
            populateSpeakerSummary();
        } else if (this.eventStage == 'Execution') {
            populateRateCard();
            populateSpeakerSummary();
        } else if (this.eventStage == 'Close_out') {
            populateBlueFolder();
            populateSpeakerSummary();
            system.debug('JK - populate blue folder');          
        }
        */
        
          
        
    }
    public void getApprovalStatus() {
       
        for (ProcessInstance pi : [SELECT Status FROM ProcessInstance WHERE TargetObjectId = :this.medicalEvent.Id]) {
            this.approvalStatus = pi.Status;
        }
    }
    public void saveSpeaker() {
        system.debug('JK - speaker: ' + this.medicalEvent.Speaker_BMS__c);
        update this.medicalEvent;
        populateRateCard();
        populateSpeakerSummary();
    }
    public void populateRateCard() {
        DisplayRateCard drc;
        FixedDisplayRateCard fdrc;
        this.displayRateCards = new List<DisplayRateCard>();
        this.fixedDisplayRateCards = new List<FixedDisplayRateCard>();
        totalCostSum = 0;
        
        if (this.MedicalEvent.Has_Rate_Card__c) {
            for (Rate_Card__c rc : [SELECT Hourly_Rate__c,Hours__c,Id,Medical_Event__c,Name,Type__c, Is_Hourly__c 
                                    FROM Rate_Card__c
                                    WHERE Medical_Event__c = :this.medicalEvent.Id]) {
                if (rc.Is_Hourly__c) {
                    drc = new DisplayRateCard();
                    drc.HourlyRate = rc.Hourly_Rate__c;
                    drc.Hours = rc.Hours__c;
                    drc.isTemplate = false;
                    drc.Name = rc.Name;
                    drc.Type = rc.Type__c;
                    drc.Id = rc.Id;
                    drc.Total = rc.Hours__c * rc.Hourly_Rate__c;
                    this.displayRateCards.add(drc);
                    totalCostSum += (rc.Hours__c * rc.Hourly_Rate__c); 
                } else {
                    fdrc = new FixedDisplayRateCard();
                    fdrc.Total = rc.Hourly_Rate__c;
                    fdrc.Name = rc.Name;
                    this.fixedDisplayRateCards.add(fdrc);
                    totalCostSum += rc.Hourly_Rate__c; 
                }                                       
            }           
        } else {
            for (Rate_Card_Template__c rct : [SELECT Hourly_Rate__c,Hours__c,Id,Name,Type__c 
                                              FROM Rate_Card_Template__c
                                              WHERE Type__c = :this.medicalEvent.Event_Type__c]) {
                drc = new DisplayRateCard();
                drc.HourlyRate = rct.Hourly_Rate__c;
                drc.Hours = rct.Hours__c;
                drc.isTemplate = true;
                drc.Name = rct.Name;
                drc.Type = rct.Type__c;
                drc.Id = rct.Id;
                drc.Total = rct.Hours__c * rct.Hourly_Rate__c;
                this.displayRateCards.add(drc);
                totalCostSum += (rct.Hours__c * rct.Hourly_Rate__c);                    
            }
            
        }
        if (this.eventStage == 'Planning') {
            for (Integer i = 0; i < 3; i++) {
                fdrc = new FixedDisplayRateCard();
                fdrc.Name = '';
                fdrc.Total = 0;
                this.fixedDisplayRateCards.add(fdrc);
            }
        }                
        system.debug('JK - displayRateCards: ' + displayRateCards);
    }
    public void createElectronicSignaturePage() {
        
    }
    public void sendDocuments() {
        
    }
    

    /*****************************************
    
    *****************************************/
    private void getVeevaMessages(String lang)  
    {
        
     System.Debug('CSABA getting Veeva messages for language ' + lang);         
     ExternalString[] labels = [Select Value, Name, Category, (Select Value, language From Localization where language = :lang) From ExternalString  where Category = 'BMS EMEA FFM'];
   
     Map<String,String> labelMap = new Map<String,String>() ;
     for(ExternalString label : labels) 
        {
         ExternalStringLocalization[] localized = label.Localization;   
         if(localized.size() == 1)
            labelMap.put(label.Name, String.escapeSingleQuotes(localized[0].Value)) ;
         else
            labelMap.put(label.Name, String.escapeSingleQuotes(label.value)) ;
        } 
  
     BMS_EMEA_MEDEV_MISINGATTACH = labelMap.get('BMS_EMEA_MEDEV_MISINGATTACH') == NULL ? 'Must specify a description for file' : labelMap.get('BMS_EMEA_MEDEV_MISINGATTACH');    
     BMS_EMEA_MEDEV_DUPLICATEATTACH = labelMap.get('BMS_EMEA_MEDEV_DUPLICATEATTACH') == NULL ? 'Description already in use' : labelMap.get('BMS_EMEA_MEDEV_DUPLICATEATTACH');
     
     System.Debug('Msg1 = ' +  BMS_EMEA_MEDEV_MISINGATTACH + ' msg2 = ' + BMS_EMEA_MEDEV_DUPLICATEATTACH);
        
    }

    
    /*********************************************************
    
    *********************************************************/
    private boolean CheckDuplicateDescription(String thedescr)
    {
        system.Debug('CSABA checking existing of descr: ' +  thedescr);
        //system.debug('ERIK USED DESCRIPTION: ' + this.usedDescription);
        
        if(this.usedDescription.contains(thedescr))
           return true;
           
        return false;
    }
    
    /*************************************************
    Load  all  Description  into a set  and into  a list
    then compare them
    *************************************************/
    private boolean checkDuplicatedDescriptionOnline()
    {
        
        List<String>  list1 = new List<String>();
        Set<String>   set1 = new set<String>();
        
        for (BlueFolder file : files)
        {
            if(file.description == '')
               continue;
            list1.add(file.description);
            set1.add(file.description);
        }
        
        if(list1.size() != set1.size())
           return true;
        
        return false;
    }
    
    /****************************
    CSABA 2014.07.16.  
    ****************************/
    public void attachDocuments() 
    {
        system.debug('starting attach documents');
        Boolean hasAllRequired = true;
        List<Attachment> newAttachments = new List<Attachment>();
        Attachment attachment;
                  
        System.Debug('CSABA Nr  of used Descr =' + this.usedDescription.size());
        for(String s :this.usedDescription)
           System.Debug('CSABA: Desc: = ' + s);
           
        //check if there is duplicstion in the current attach session   
        if(checkDuplicatedDescriptionOnline())
        {
               ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, BMS_EMEA_MEDEV_DUPLICATEATTACH));
               return;          
        }
           
        
        for (BlueFolder file : files) 
        {

            system.debug('file.isUploaded ' + file.isUploaded);
            system.debug('file.newAttachment.Name ' + file.newAttachment.Name);
            system.debug('file.description ' + file.description);
            
            //CSABA 2014.07.16. chekc the existenc e of description
            if(file.description == '' && file.newAttachment.Name != NULL)
            {
               ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, BMS_EMEA_MEDEV_MISINGATTACH + ' '  + file.newAttachment.Name));
               continue;
            }
            
            //CSABA 2014.07.16. chekc duplicate Description
            if(file.description != '' && file.newAttachment.Name != NULL && file.isUploaded ==  false && this.CheckDuplicateDescription(file.description))
            {
               //Commented by Erik, 2014.08.05.
               //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Description (' + file.description + ') is not  unique  See file: ' + file.newAttachment.Name));
               //return;              
            }
            
            if (!file.isUploaded && file.newAttachment.Name != null) 
            {
                /*
                attachment = new Attachment();
                attachment.ParentId = this.medicalEvent.Id;
                attachment.Name = file.newAttachment.Name;
                attachment.Description = file.Description;
                attachment.Body = file.newAttachment.Body;
                attachment.ContentType = file.newAttachment.ContentType;
                */
                file.newAttachment.ParentId = this.medicalEvent.Id;
                file.newAttachment.Description = file.Description;
                system.debug('new attachment: ' + file.newAttachment + ' CSABA 1 with description: ' + file.Description);
                newAttachments.add(file.newAttachment);
                file.isUploaded = true;
            }
        }
        
        for (BlueFolder bf : files) 
        {
            system.debug('JK - starting');
            system.debug('JK - bf.Description ' + bf.Description );
            system.debug('JK - bf.isUploaded' + bf.isUploaded);
            system.debug('JK - bf.isRequired ' + bf.isRequired );
            if (bf.isRequired && !bf.isUploaded) 
            {
                hasAllRequired = false;
            }
        }
        
        system.debug('newAttachments: ' + newAttachments);
        insert newAttachments;
        //update 
        populateBlueFolder();
        //set required documents status
        system.debug('hasAllRequired: ' + hasAllRequired);
        this.medicalEvent.Has_All_Documents_BMS__c = hasAllRequired;
        update this.medicalEvent;
              
    }
    
    
    public void saveRateCard() {
        if (this.MedicalEvent.Has_Rate_Card__c) {
            delete [SELECT Id FROM Rate_Card__c WHERE Medical_Event__c = :this.medicalEvent.Id];
        } 

        Rate_Card__c rc;
        Decimal amount = 0;
        List<Rate_Card__c> rateCards = new List<Rate_Card__c>();
        for (DisplayRateCard drc : this.displayRateCards) {
            
                rc = new Rate_Card__c();
                rc.Is_Hourly__c = true;
                if (drc.Hours > 0) {
                    rc.Hours__c = drc.Hours;
                } else {
                    rc.Hours__c = 0;
                }
                rc.Medical_Event__c = this.medicalEvent.Id;
                rc.Name = drc.Name;
                rc.Type__c = drc.Type;
                rc.Hourly_Rate__c = drc.HourlyRate;
                rateCards.add(rc);
                amount += (rc.Hours__c * rc.Hourly_Rate__c);   
                system.debug('jk - rate card: ' + rc);
            
        }
        for (FixedDisplayRateCard fdrc : this.fixedDisplayRateCards) {
            system.debug('jk - fixed rate card: ' + rc);
            if (fdrc.Total > 0) {
                rc = new Rate_Card__c();
                rc.Is_Hourly__c = false;
                rc.Hours__c = 1;
                rc.Medical_Event__c = this.medicalEvent.Id;
                rc.Name = fdrc.Name;
                rc.Hourly_Rate__c = fdrc.Total;
                rateCards.add(rc);
                amount += fdrc.Total;
                system.debug('jk - adding fixed rate card: ' + rc);
            }
        }
        system.debug('rate cards: ' + rateCards);
        insert rateCards;
        this.MedicalEvent.Has_Rate_Card__c = true;
        this.MedicalEvent.Planned_Expense_Amount__c = amount;
        update this.medicalEvent;
        populateRateCard();
    
    }




    /**************************************
    CSABa  must refrsh the page after delete
    **************************************/
    public PageReference deleteAttachment() 
    {
        String attachmentId= System.currentPageReference().getParameters().get('deleteAttachment');
        System.debug('attachmentIdToDelete : '+attachmentId );
        Attachment a = new Attachment(ID = attachmentId);
        Delete a;

        populateBlueFolder();
        this.usedDescription.clear();  //2014.07.16
          
        return null;
             
    }
    
    /*******************************
    populate the files  List  CSABA*
    *******************************/
    public void populateBlueFolder() 
    {
        decimal completeCount = 0;
        decimal totalCount = 0;
        this.percentComplete = 0;
        //for now just create dummy data.
        BlueFolder bf;
        this.files = new List<BlueFolder>();
        
        //get attachments
        Map<String,Attachment> descriptionToAttachment = new Map<String,Attachment>();
        for (Attachment a : [SELECT ContentType,Description,Id,Name,LastModifiedDate 
                             FROM Attachment
                             WHERE ParentId = :this.medicalEvent.Id]) 
        {
            descriptionToAttachment.put(a.Description,a);
        }   
        
        system.debug('CSABA1 descriptionToAttachment size = ' +  descriptionToAttachment .size());                          
        
        /*
        List<Meeting_Document_Template__c> documentTemplates= [SELECT Id,Meeting_Type__c,Name, Is_Required__c 
                                                               FROM Meeting_Document_Template__c
                                                               WHERE Meeting_Type__c = :this.medicalEvent.Event_Type__c];
        */
        //get document templates
        List<Meeting_Document_Template__c> documentTemplates = new List<Meeting_Document_Template__c>();
        Map<String,Meeting_Document_Template__c> documentTemplateNameToDocument = new Map<String,Meeting_Document_Template__c>();                                                     
        for (Meeting_Document_Template__c mdt : [SELECT Id,Meeting_Type__c,Name, Is_Required__c,Country_Specific_BMS_EMEA__c,FFM_Step_BMS_EMEA__c,Activity_Type_BMS_EMEA__c
                                                               FROM Meeting_Document_Template__c
                                                               WHERE 
                                                               Country_Specific_BMS_EMEA__c =: this.medicalEvent.Country_MasterFile_BMS_EMEA__c
                                                               and FFM_Step_BMS_EMEA__c =: this.medicalEvent.FFM_Step_BMS_EMEA__c
                                                               and Activity_Type_BMS_EMEA__c =: this.medicalEvent.FFM_Activity_Type_BMS_EMEA__c]) 
        {
            documentTemplates.add(mdt);
            documentTemplateNameToDocument.put(mdt.Name,mdt);
                                                                  
        }
        
        System.Debug('CSABA2 documentTemplates size = ' + documentTemplates.size());
        
                                                                       
       //populate blue folder
        for (Meeting_Document_Template__c mdt : documentTemplates) 
        {
            bf = new BlueFolder();
            if (descriptionToAttachment.containsKey(mdt.Name)) 
            {
                Attachment a = descriptionToAttachment.get(mdt.Name);
                bf.Description = mdt.Name;
                bf.Attachment = a; 
                bf.isUploaded = true;
                bf.isRequired = mdt.Is_Required__c;
                system.debug('adding bf from template file ' + bf  + '  CSABA3 with description: ' + mdt.Name );
                
                this.files.add(bf);
                
                if(bf.Description != NULL && bf.Description != '')
                {
                   System.Debug('CSABA X adding :' +  bf.Description);      
                   this.usedDescription.add(bf.Description);  //CSAB: 2014.07.16.
                   
                   //System.Debug('CSABA X adding :' +  bf.Attachment);      
                   //this.usedDescription.add(bf.Attachment);  //CSAB: 2014.07.16.
                }
                   
                if(mdt.Is_Required__c==true)completeCount += 1; //Viktor added IF 20150420 based on Arpi's point
            } 
            else 
            {
                bf.Description = mdt.Name;
                bf.Link = '/#';
                bf.isUploaded = false;
                bf.isRequired = mdt.Is_Required__c;
                system.debug('adding bf from blank template ' + bf  + ' CSABA4 with description: ' + mdt.Name );
                this.files.add(bf);
                
                if(bf.Description != NULL && bf.Description != '')
                {
                System.Debug('CSABA Y adding :' +  bf.Description);       
                this.usedDescription.add(bf.Description);  //CSAB: 2014.07.16.
                }
                
                //completeCount += 1;
                //totalCount += 1;
            }
            
            if(bf.isRequired == true)
            {
                totalCount += 1;
            }
            
        }
        
        //add any misc documents not in the template
        system.debug('CSABA5 add any misc documents not in the template');
        for (Attachment a : descriptionToAttachment.values()) 
        {
            system.debug('jk - attachment ' + a);
            if (!documentTemplateNameToDocument.containsKey(a.Description)) 
            {
                system.debug('jk - misc document ' + a);
                bf = new BlueFolder();
                bf.Description = a.Description;
                bf.Attachment = a; 
                bf.isUploaded = true;
                bf.isRequired = false;
                system.debug('adding bf from misc ' + bf  + ' CSABA6  with description: ' + a.Description);
                this.files.add(bf);
                
                if(bf.Description != NULL && bf.Description != '')
                {
                   System.Debug('CSABA Z adding :' +  bf.Description);  
                   this.usedDescription.add(bf.Description);  //CSAB: 2014.07.16. 
                }
            }
        }


        system.debug('CSABA7  why we are doing this? These might be the  2  empty  lines  for new  attachments!');
        bf = new BlueFolder();
        bf.Description = '';
        //bf.Description = 'CSABA  to be  filled';
        bf.Link = '/#';
        bf.isUploaded = false;
        bf.isRequired = false;
        this.files.add(bf);
        
        if(bf.Description != NULL && bf.Description != '')
        {
          System.Debug('CSABA A adding :' +  bf.Description);   
          this.usedDescription.add(bf.Description);  //CSAB: 2014.07.16.     
        }
        
        bf = new BlueFolder();
        bf.Description = '';
        //bf.Description = 'CSABA  to be  filled';
        bf.Link = '/#';
        bf.isUploaded = false;
        bf.isRequired = false;
        this.files.add(bf);
        
        if(bf.Description != NULL && bf.Description != '')
        {
          System.Debug('CSABA B adding :' +  bf.Description);   
          this.usedDescription.add(bf.Description);  //CSAB: 2014.07.16.
        }
       
        if (totalCount > 0) 
        {
            this.percentComplete = (completeCount/totalCount) * 100;
        } 
        
        system.Debug('CSABA  UserDescr nr = ' + this.usedDescription.size());
        
        system.Debug('CSABA: Nr  of items in the List = ' + this.files.size());                                      
    }
    
    
    public void populateBlueFolder_old() 
    {
        decimal completeCount = 0;
        decimal totalCount = 0;
        this.percentComplete = 0;
        //for now just create dummy data.
        BlueFolder bf;
        this.files = new List<BlueFolder>();
        //dummy 1
        bf = new BlueFolder();
        bf.Description = 'Document 1';
        bf.Link = '/#';
        bf.isUploaded = true;
        this.files.add(bf);
        completeCount += 1;
        totalCount += 1;
        //dummy 2
        bf = new BlueFolder();
        bf.Description = 'Document 2';
        bf.Link = '/#';
        bf.isUploaded = true;
        this.files.add(bf);
        completeCount += 1;
        totalCount += 1;
        //dummy 3
        bf = new BlueFolder();
        bf.Description = 'Document 3';
        bf.Link = '/#';
        bf.isUploaded = false;
        this.files.add(bf);
        totalCount += 1;
        //dummy 4
        bf = new BlueFolder();
        bf.Description = 'Document 4';
        bf.Link = '/#';
        bf.isUploaded = true;
        this.files.add(bf);
        completeCount += 1;
        totalCount += 1;
        system.debug('JK - completeCount: ' + completeCount);
        system.debug('JK - totalCount: ' + totalCount);
        this.percentComplete = (completeCount/totalCount) * 100;
        system.debug('JK - this.percentComplete: ' + this.percentComplete);
        system.debug('JK - files: ' + files);
    }
    
    public void populateSpeakerSummary() {
        //
        
        //get speaker info
        this.speakerSummary = new Address_vod__c();
        for(Address_vod__c ad : [SELECT Address_line_2_vod__c,City_vod__c,Name,Primary_vod__c,State_vod__c,Zip_vod__c, 
                                               Account_vod__r.Credentials_vod__c,Account_vod__r.PersonEmail,Account_vod__r.Phone,
                                               Account_vod__r.Specialty_1_vod__c,Account_vod__r.ONYX_Contract_Number_BMS__c,Account_vod__r.IsPersonAccount 
                                 FROM Address_vod__c 
                                 WHERE Account_vod__r.Id =:medicalEvent.Speaker_BMS__c AND
                                       Primary_vod__c = true]){
            this.speakerSummary = ad;                           
        }       
    }
    

    public class DisplayRateCard {
        public boolean isTemplate {get;set;}
        public string Name {get;set;}
        public decimal Hours {get;set;}
        public string Type {get;set;}
        public decimal HourlyRate {get;set;}
        public Id Id {get;set;}
        public decimal Total {get;set;}
        
        
        public DisplayRateCard() {
            
        }
    }
    public class FixedDisplayRateCard {
        public string Name {get;set;}
        public decimal Total {get;set;}
        
        public FixedDisplayRateCard() {
            
        }   
    }
    
    
    public class BlueFolder 
    {
        public Attachment newAttachment 
        {
            get 
            {
                if (attachment == null)
                    attachment = new Attachment();
                    return attachment;
            }
            set;
        }
        public string Description {get;set;}
        public string Link {get;set;}
        public boolean isUploaded {get;set;}
        public Id id {get;set;}
        public Attachment attachment {get;set;}
        public boolean isRequired {get;set;}
        
        public BlueFolder() 
        {
            
        }
    }
}