BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BP_ID__c</fullName>
        <description>VPRO - November 2011 - BMS Oncology Requirements &amp; Design: Custom Field to store BMS&apos; unique identifier for accounts.</description>
        <label>Master ID</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ID_vod__c</fullName>
        <description>External ID is used for data loading only.</description>
        <label>External ID</label>
        <length>120</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Address_vod__c.object
<CustomObject>
    <description>This object stores all addresses for each account profile as well as DEA and State Licenses for physicians.  The State Licenses are maintained across Address records based on the Address_trigger_vod trigger.</description>
    <fields>
        <fullName>External_ID_vod__c</fullName>
        <description>External ID is only used for data loading.</description>
        <externalId>true</externalId>
        <label>BPA ID</label>
        <length>120</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address line 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Error_Log_BMS__c.object
<CustomObject>
    <description>Error Log entries for BMS web services integration.</description>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>Populate this with account id</description>
        <externalId>true</externalId>
        <inlineHelpText>Populate this with account id.</inlineHelpText>
        <label>External ID</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Error Logs (Related Account)</relationshipLabel>
        <relationshipName>Error_Logs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Address to which this error belongs.</description>
        <inlineHelpText>Address to which this error belongs.</inlineHelpText>
        <label>Related Address</label>
        <referenceTo>Address_vod__c</referenceTo>
        <relationshipLabel>Error Logs</relationshipLabel>
        <relationshipName>Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resolved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Will be automatically checked if the error is resolved.</description>
        <inlineHelpText>Will be automatically checked if the error is resolved.</inlineHelpText>
        <label>Resolved</label>
        <type>Checkbox</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/classes/Resubmit_to_BMS_CM_Service_Controller.cls
public class Resubmit_to_BMS_CM_Service_Controller {
    String resubmitStatus = 'submitting...';
    Id eLogId = null;
    
    ApexPages.StandardController myController = null;
    
    public Resubmit_to_BMS_CM_Service_Controller(ApexPages.StandardController controller) {
    	myController = controller;
        eLogId = controller.getId();
    }


    public PageReference reSubmitToBMSCM() {
        // hardcoding for testing
	
        Error_log_bms__c eLog = [select id, external_id__c, related_account__c, related_address__c, Resolved__c from error_log_bms__c where id=:myController.getId() ];
        
        CustomerMasterWrapper_BMS.callWebService(new Set<ID>{eLog.related_address__c });
        Account myAcc    		= [select id, bp_id__c from account where id=:eLog.related_account__c];
        Address_vod__c myAdd    = [select id, external_id_vod__c from address_vod__c where id=:eLog.Related_Address__c];
        
        if(myAcc.bp_id__c != null && myAdd.external_id_vod__c != null){
            resubmitStatus = 'Re-submit success..';
            eLog.Resolved__c = true;
            update eLog;          	                                   
        } else {
          	resubmitStatus = 'Re-submit failed..';
        }     
        return null;
    }
   
    public String getResubmitStatus(){
        return resubmitStatus;
    }

}