BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Language_vod__c</fullName>
        <description>Language_vod holds the preferred Language for the Account. Used in Approved Email to drive the preferred language functionality.</description>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>en_US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>nl_NL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithoutProfilesXLation/src/objects/EM_Event_Budget_vod__c.object
<CustomObject>
    <fields>
        <fullName>Event_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The activity that is accessing the budget</description>
        <label>Event</label>
        <referenceTo>EM_Event_vod__c</referenceTo>
        <relationshipLabel>WBS/CCs</relationshipLabel>
        <relationshipName>Event_vod</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/EM_Event_Speaker_vod__c.object
<CustomObject>
    <description>Service Provider at an Activity for Veeva Event Management.</description>
    <fields>
        <fullName>Account_vod__c</fullName>
        <formula>CASESAFEID(Speaker_vod__r.Account_vod__c)</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The activity which the speaker is speaking at.</description>
        <label>Activity</label>
        <referenceTo>EM_Event_vod__c</referenceTo>
        <relationshipName>EM_Event_Speaker_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Speaker_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The speaker for an event.</description>
        <label>Service Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>EM_Speaker_vod__c.Status_vod__c</field>
                <operation>equals</operation>
                <value>Eligible_vod</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>EM_Speaker_vod__c</referenceTo>
        <relationshipName>Speakers_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time_vod__c</fullName>
        <description>Start time of the event</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status_vod__c</fullName>
        <description>Status of the speaker for the event.</description>
        <label>Veeva Status</label>
        <picklist>
            <picklistValues>
                <fullName>Nominated_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invited_vod</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cleared_Signature_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Did Not Attend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Event Service Provider</label>
    <nameField>
        <displayFormat>ESP-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Service Providers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/EM_Event_vod__c.object
<CustomObject>
    <description>Activity object for Veeva Events Management
Relabeled Activities for HCPTS SEW 05/2015</description>
    <fields>
        <fullName>Start_Time_vod__c</fullName>
        <description>Start time of the event.</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status_vod__c</fullName>
        <description>Status of an event. Custom values can be added.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Canceled_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Service Coordinator Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Closeout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Business Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Post-Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending_Approval_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Event-PostApproval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>EM Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EM Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/EM_Expense_Estimate_vod__c.object
<CustomObject>
    <description>Used to capture estimated expenses when in the initial process of planning an activity.</description>
    <fields>
        <fullName>Actual_vod__c</fullName>
        <description>Sum of actual values from related expense lines. This value is managed by a Veeva trigger.</description>
        <label>Actual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event_vod__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used for expense estimate rollups on an Activity. Do not use this field if using Activity Budgets.</description>
        <label>Event</label>
        <referenceTo>EM_Event_vod__c</referenceTo>
        <relationshipLabel>Expense Estimates</relationshipLabel>
        <relationshipName>Expense_Estimate_vod</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Expense Estimate</label>
    <nameField>
        <displayFormat>EE -{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Estimates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-TrackerConsolidationUpdates/src/objects/EM_Speaker_Qualification_vod__c.object
<CustomObject>
    <description>Used to store records of which topics a speaker has been trained on and which services a speaker can provide.</description>
    <fields>
        <fullName>Speaker_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The speaker that was trained.</description>
        <label>Service Provider</label>
        <referenceTo>EM_Speaker_vod__c</referenceTo>
        <relationshipLabel>Service Provider Qualifications</relationshipLabel>
        <relationshipName>Speaker_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Provider Qualification</label>
    <nameField>
        <displayFormat>SQ -{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Provider Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithoutProfilesXLation/src/objects/EM_Speaker_vod__c.object
<CustomObject>
    <fields>
        <fullName>Status_vod__c</fullName>
        <description>The status of a speaker.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Nominated_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired_vod</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Year_to_Date_Utilization_vod__c</fullName>
        <description>Number of times a speaker has spoken this year to date.</description>
        <inlineHelpText>Number of times a speaker has spoken this year to date.</inlineHelpText>
        <label>Year to Date Utilization</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Expense_Header_vod__c.object
<CustomObject>
    <description>Aggregates details of an expense line, such as the payee, the person who incurred the expense, and the payment status. Represents an invoice.</description>
    <fields>
        <fullName>Event_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Event that the expense is associated with.</description>
        <label>Event</label>
        <referenceTo>EM_Event_vod__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expense_Header_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_vod__c</fullName>
        <description>Status of payment</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Unpaid_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid_in_Full_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial_Payment_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PO Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concur Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Updated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concur Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>EH-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Expense_Line_vod__c.object
<CustomObject>
    <description>Contains details of an individual expense line. Represents an individual line on an invoice, broken out by sub-type.</description>
    <fields>
        <fullName>Event_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The activity for which an expense was incurred.</description>
        <label>Event</label>
        <referenceTo>EM_Event_vod__c</referenceTo>
        <relationshipLabel>Expense Lines</relationshipLabel>
        <relationshipName>Expense_Lines_Event_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Expense Line</label>
    <nameField>
        <displayFormat>EL -{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/objects/Expense_Type_vod__c.object
<CustomObject>
    <description>Defines expense types.</description>
    <fields>
        <fullName>Active_vod__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to activate or deactivate expense types. In the UI, Veeva lookup fields to expense types will prevent the user from selecting inactive expense types.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Expense Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/classes/SpeakerYTDCalculator.cls
public class SpeakerYTDCalculator {
	
    public static void calculate(Set<Id> speakerIds) {
        if(System.isFuture() || System.isBatch()) {
        	calculateSync(speakerIds);  
        } else {
        	calculateFuture(speakerIds);  
        }
    }
    
    @future
    public static void calculateFuture(Set<Id> speakerIds) {
        calculateSync(speakerIds);
    }
    
    public static Set<String> getSpeakerStatuses() {   	
        List<String> speakerSetting = new List<String>();
        Set<String> speakerStatuses = new Set<String>();
        Events_Management_Settings_vod__c emSetting = Events_Management_Settings_vod__c.getInstance();
        if(emSetting != null && emSetting.SPEAKER_ROLLUP_STATUS_FILTER_vod__c != null) {
        	speakerSetting = emSetting.SPEAKER_ROLLUP_STATUS_FILTER_vod__c.split(';;');
            String name = speakerSetting.get(0);
            String category = speakerSetting.get(1);
            if(speakerSetting.size() == 2) {
                List<Message_vod__c> speakerStatusesMessage = [SELECT Text_vod__c 
                                                               FROM Message_vod__c
                                                               WHERE Active_vod__c = true
                                                               AND NAME = :name
                                                               AND Category_vod__c = :category
                                                               AND Language_vod__c = 'en_US'];
                if(speakerStatusesMessage.size() > 0 && speakerStatusesMessage.get(0).Text_vod__c != null) {
                    speakerStatuses = new Set<String>(speakerStatusesMessage.get(0).Text_vod__c.split(','));
                }
            }
        }
        
        if(speakerStatuses.isEmpty()) {
            speakerStatuses.add('Attended_vod');
            speakerStatuses.add('Signed_vod');
        }    
        return speakerStatuses;
    }
    
    public static void calculateSync(Set<Id> speakerIds) {
        boolean multiCurrency = MultiCurrencyUtil.isMultiCurrencyOrg();
        Map<Id, Account> accounts = new Map<Id, Account>();
        for(Account account: [SELECT Id, (SELECT Id FROM EM_Speaker_vod__r) FROM Account WHERE Id IN (SELECT Account_vod__c FROM EM_Speaker_vod__c WHERE Id IN :speakerIds)]) {
       		accounts.put(account.Id, account);
        }

        Map<Id,EM_Speaker_vod__c> speakersToUpdate = new Map<Id,EM_Speaker_vod__c>();

        Integer defaultDay = Integer.valueOf(EM_Speaker_vod__c.Year_To_Date_Reset_Day_vod__c.getDescribe().getDefaultValue());
        Integer defaultMonth = Integer.valueOf(EM_Speaker_vod__c.Year_To_Date_Reset_Month_vod__c.getDescribe().getDefaultValue());

		Set<String> speakerStatuses = getSpeakerStatuses();

        Map<Id, String> speakerIdToIsoCode = new Map<Id,String>();

        if(multiCurrency) {
        	List<EM_Speaker_vod__c> speakersWithIsoCode = Database.query('SELECT CurrencyIsoCode, Id FROM EM_Speaker_vod__c WHERE Id IN ' + MultiCurrencyUtil.toCommaSeperated(speakerIds));
            for(EM_Speaker_vod__c speaker: speakersWithIsoCode) {
                speakerIdtoIsoCode.put(speaker.Id, (String)speaker.get('CurrencyIsoCode'));
            }
        }


        for(Id speakerId: speakerIds) {
            EM_Speaker_vod__c speaker = new EM_Speaker_vod__c(Id=speakerId, Year_to_Date_Utilization_vod__c = 0, Year_to_Date_Spend_vod__c = 0);
            if(multiCurrency) {
            	speaker.put('CurrencyIsoCode', speakerIdtoIsoCode.get(speakerId));
            }
            speakersToUpdate.put(speakerId, speaker);
        }

        Set<Id> relevantEvents = new Set<Id>();

        Date minimumDate = Date.newInstance(System.Today().year()-1, 1, 1);
        Date maximumDate = Date.newInstance(System.Today().year()+1, 12, 31);

        List<EM_Event_Speaker_vod__c> eventSpeakers;

        if(multiCurrency) {
            Datetime minDatetime = datetime.newInstance(minimumDate.year(), minimumDate.month(),minimumDate.day());
			Datetime maxDatetime = datetime.newInstance(maximumDate.year(), maximumDate.month(),maximumDate.day());

            String datetimeFormat = 'yyyy-MM-dd\'T\'HH:mm:ss\'Z\'';

            String formattedMin = minDateTime.formatGmt(datetimeFormat);
            String formattedMax = maxDatetime.formatGmt(datetimeFormat);

        	eventSpeakers = Database.query('SELECT Id, CurrencyIsoCode, Event_vod__c, Event_vod__r.Status_vod__c, Event_vod__r.Start_Time_vod__c, Status_vod__c, ' +
                                                       ' Speaker_vod__c, Speaker_vod__r.Year_To_Date_Reset_Day_vod__c, Speaker_vod__r.Year_To_Date_Reset_Month_vod__c' +
                                                       ' FROM EM_Event_Speaker_vod__c ' +
                                                       ' WHERE Speaker_vod__c IN ' + MultiCurrencyUtil.toCommaSeperated(speakerIds) +
                                                       ' AND Event_vod__r.Status_vod__c != \'Canceled_vod\'' +
                                                       ' AND Event_vod__r.Start_Time_vod__c >= ' + formattedMin +
                                                       ' AND Event_vod__r.Start_Time_vod__c <= ' + formattedMax);
        } else {
        	eventSpeakers = [SELECT Id, Event_vod__c, Event_vod__r.Status_vod__c, Event_vod__r.Start_Time_vod__c, Status_vod__c,
                                                       Speaker_vod__c, Speaker_vod__r.Year_To_Date_Reset_Day_vod__c, Speaker_vod__r.Year_To_Date_Reset_Month_vod__c
                                                       FROM EM_Event_Speaker_vod__c
                                                       WHERE Speaker_vod__c IN :speakerIds
                                                       AND Event_vod__r.Status_vod__c != 'Canceled_vod'
                                                       AND Event_vod__r.Start_Time_vod__c >= :minimumDate
                                                       AND Event_vod__r.Start_Time_vod__c <= :maximumDate];
        }


        for(EM_Event_Speaker_vod__c eventSpeaker: eventSpeakers) {

            EM_Speaker_vod__c speaker = speakersToUpdate.get(eventSpeaker.Speaker_vod__c);

            Integer day = eventSpeaker.Speaker_vod__r.Year_To_Date_Reset_Day_vod__c != null ? Integer.valueOf(eventSpeaker.Speaker_vod__r.Year_To_Date_Reset_Day_vod__c): defaultDay;
            Integer month = eventSpeaker.Speaker_vod__r.Year_To_Date_Reset_Month_vod__c != null ? Integer.valueOf(eventSpeaker.Speaker_vod__r.Year_To_Date_Reset_Month_vod__c): defaultMonth;
            Date currentResetDate = Date.newInstance(System.today().year(), month, day);
            Date startConstraint;
            Date endConstraint;

            if(System.today() < currentResetDate) {
            	startconstraint = Date.newInstance(currentResetDate.year()-1, month, day);
                endConstraint = currentResetDate;
            } else {
            	startconstraint = currentResetDate ;
                endConstraint = Date.newInstance(currentResetDate.year()+1, month, day);
            }

            if(eventSpeaker.Event_vod__r.Start_Time_vod__c >= startconstraint
               && eventSpeaker.Event_vod__r.Start_Time_vod__c < endConstraint) {
                   relevantEvents.add(eventSpeaker.Event_vod__c);
                   if(speakerStatuses.contains(eventSpeaker.Status_vod__c)) {
                   		speaker.Year_to_Date_Utilization_vod__c++;
                   }
            }
        }

        List<Expense_Line_vod__c> expenseLines;

        if(multiCurrency) {
            String query = 'SELECT CurrencyIsoCode, Actual_vod__c, Expense_Header_vod__r.Incurred_Expense_Speaker_vod__r.Speaker_vod__c,' +
                            ' Expense_Header_vod__r.Incurred_Expense_Account_vod__c, Expense_Header_vod__r.Incurred_Expense_Attendee_vod__r.Account_vod__c ' +
                            ' FROM Expense_Line_vod__c ' +
                            ' WHERE Event_vod__c IN ' + MultiCurrencyUtil.toCommaSeperated(relevantEvents) +
                            ' AND (';

                            if(!accounts.keySet().isEmpty()) {
                            	query += 'Expense_Header_vod__r.Incurred_Expense_Account_vod__c IN ' + MultiCurrencyUtil.toCommaSeperated(accounts.keySet());
                            } else {
                                query += 'Id != \'_______________\'';
                            }
            				query +=' OR ';

            				if(!accounts.keySet().isEmpty()) {
                            	query += 'Expense_Header_vod__r.Incurred_Expense_Speaker_vod__r.Speaker_vod__c IN ' + MultiCurrencyUtil.toCommaSeperated(speakerIds);
                            } else {
                                query += 'Id != \'_______________\'';
                            }
            				query +=' OR ';

            				if(!accounts.keySet().isEmpty()) {
                            	query += 'Expense_Header_vod__r.Incurred_Expense_Attendee_vod__r.Account_vod__c IN ' + MultiCurrencyUtil.toCommaSeperated(accounts.keySet());
                            } else {
                                query += 'Id != \'_______________\'';
                            }

                            query += ') AND Expense_Type_vod__r.Included_In_Speaker_Cap_vod__c = true';

            SYSTEM.debug('QUERY: ' + query);

        	expenseLines = Database.query(query);
        } else {
            expenseLines = [SELECT Actual_vod__c, Expense_Header_vod__r.Incurred_Expense_Speaker_vod__r.Speaker_vod__c,
                            Expense_Header_vod__r.Incurred_Expense_Account_vod__c, Expense_Header_vod__r.Incurred_Expense_Attendee_vod__r.Account_vod__c
                            FROM Expense_Line_vod__c
                            WHERE Event_vod__c IN :relevantEvents
                            AND (Expense_Header_vod__r.Incurred_Expense_Account_vod__c IN :accounts.keySet() OR
                                 Expense_Header_vod__r.Incurred_Expense_Speaker_vod__r.Speaker_vod__c IN :speakerIds OR
                                 Expense_Header_vod__r.Incurred_Expense_Attendee_vod__r.Account_vod__c IN :accounts.keySet())
                            AND Expense_Type_vod__r.Included_In_Speaker_Cap_vod__c = true];
        }

        for(Expense_Line_vod__c expense : expenseLines) {
            if(expense.Expense_Header_vod__r.Incurred_Expense_Speaker_vod__r.Speaker_vod__c != null) {
            	EM_Speaker_vod__c speaker = speakersToUpdate.get(expense.Expense_Header_vod__r.Incurred_Expense_Speaker_vod__r.Speaker_vod__c);

                addActual(speaker, expense, multiCurrency);
            } else if (expense.Expense_Header_vod__r.Incurred_Expense_Account_vod__c != null) {
                Account account = accounts.get(expense.Expense_Header_vod__r.Incurred_Expense_Account_vod__c);
                if(account.EM_Speaker_vod__r != null && !account.EM_Speaker_vod__r.isEmpty()) {
                    EM_Speaker_vod__c updateSpeaker = account.EM_Speaker_vod__r;
                    EM_Speaker_vod__c speaker = speakersToUpdate.get(updateSpeaker.Id);

            		addActual(speaker, expense, multiCurrency);
                }
            } else if (expense.Expense_Header_vod__r.Incurred_Expense_Attendee_vod__r.Account_vod__c != null) {
            	Account account = accounts.get(expense.Expense_Header_vod__r.Incurred_Expense_Attendee_vod__r.Account_vod__c);
                if(account.EM_Speaker_vod__r != null && !account.EM_Speaker_vod__r.isEmpty()) {
                    EM_Speaker_vod__c updateSpeaker = account.EM_Speaker_vod__r;
                    EM_Speaker_vod__c speaker = speakersToUpdate.get(updateSpeaker.Id);

            		addActual(speaker, expense, multiCurrency);
                }
            }
		}

        List<Expense_Attribution_vod__c> attributions = [SELECT Actual_vod__c, Incurred_Expense_Account_vod__c, Incurred_Expense_Speaker_vod__r.Speaker_vod__c, Incurred_Expense_Attendee_vod__r.Account_vod__c
                                                        FROM Expense_Attribution_vod__c
                                                        WHERE Expense_Line_vod__r.Event_vod__c IN :relevantEvents
                                                        AND Expense_Line_vod__r.Expense_Type_vod__r.Included_In_Speaker_Cap_vod__c = true
                                                        ANd Expense_Line_vod__r.Expense_Header_vod__r.Split_Lines_vod__c = 'Yes_vod'
                                                        AND (Incurred_Expense_Account_vod__c IN :accounts.keySet() OR
                                                             Incurred_Expense_Attendee_vod__r.Account_vod__c IN :accounts.keySet() OR
                                                             Incurred_Expense_Speaker_vod__r.Speaker_vod__c IN :speakerIds)];

        for(Expense_Attribution_vod__c attr: attributions) {
            if(attr.Incurred_Expense_Speaker_vod__r.Speaker_vod__c != null) {
            	EM_Speaker_vod__c speaker = speakersToUpdate.get(attr.Incurred_Expense_Speaker_vod__r.Speaker_vod__c);

                addActual(speaker, attr, multiCurrency);
            } else if (attr.Incurred_Expense_Account_vod__c != null) {
                Account account = accounts.get(attr.Incurred_Expense_Account_vod__c);
                if(account.EM_Speaker_vod__r != null && !account.EM_Speaker_vod__r.isEmpty()) {
                    EM_Speaker_vod__c updateSpeaker = account.EM_Speaker_vod__r;
                    EM_Speaker_vod__c speaker = speakersToUpdate.get(updateSpeaker.Id);

            		addActual(speaker, attr, multiCurrency);
                }
            } else if (attr.Incurred_Expense_Attendee_vod__r.Account_vod__c != null) {
            	Account account = accounts.get(attr.Incurred_Expense_Attendee_vod__r.Account_vod__c);
                if(account.EM_Speaker_vod__r != null && !account.EM_Speaker_vod__r.isEmpty()) {
                    EM_Speaker_vod__c updateSpeaker = account.EM_Speaker_vod__r;
                    EM_Speaker_vod__c speaker = speakersToUpdate.get(updateSpeaker.Id);

            		addActual(speaker, attr, multiCurrency);
                }
            }
        }

        if(speakersToUpdate.values().size() > 0) {
            update speakersToUpdate.values();
        }
    }

    private static void addActual(EM_Speaker_vod__c speaker, SObject expense, Boolean multiCurrency) {
        Decimal actual = (Decimal)expense.get('Actual_vod__c');

        if(multiCurrency) {
            actual = MultiCurrencyUtil.convertCurrency((String)expense.get('CurrencyIsoCode'), (String)speaker.get('CurrencyIsoCode'), actual);
        }

        speaker.Year_to_Date_Spend_vod__c += actual;
    }
}