BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Account_Territory_Loader_vod__c.object
<CustomObject>
    <description>The Account Territory Loader object is tool to modify Account territory assignments. Inserting a row into Account Territory Loader performs two operations: 1) Removes the current territory assignment for associated Account. 2) Assigns the account to the specified list of territories.</description>
    <fields>
        <fullName>Account_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This a lookup to the account object.  The account inserted/updated in this field will have the account sharing rules recalculated.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Territory Loaders</relationshipLabel>
        <relationshipName>R00NT0000000lj9mMAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory_vod__c</fullName>
        <description>Stores the territories associated with this account in a semicolon separated format. Salesforce.com territory rules later run on this field to actually assign territories. A leading and trailing semicolon must be contained within this field. Also, no spaces should be included in the text string. The following is an example of a valid value for this field: &quot;;TERR1;TERR2;TERR3;&quot;</description>
        <label>Territory List</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Account Territory Loader</label>
    <nameField>
        <displayFormat>ATL {00000000}</displayFormat>
        <label>Account Territory Loader Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Territory Loaders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EMSIM-AllTriggers&Apex/src/classes/VOD_ProcessATL_Asyn.cls
/* This class must run with administrator access.  User's sharing rules should not be applied. */
global class VOD_ProcessATL_Asyn {
    @future
    public static void processATL (String loadersXmlDoc, Set<Id> acctIds, boolean extendATLMode) {
        List<Account_Territory_Loader_vod__c> loaders = parse(loadersXmlDoc);
        VOD_ProcessATL.processATL(loaders, acctIds, extendATLMode);
    }
       
    public static String write(List<Account_Territory_Loader_vod__c> loaders) {
        XmlStreamWriter writer = new XmlStreamWriter();
        writer.writeStartDocument(null, '1.0');
        writer.writeStartElement(null, 'loaders', null);
        for (Account_Territory_Loader_vod__c loader : loaders) {      
            writer.writeStartElement(null, 'loader', null);
            writer.writeAttribute(null, null, 'acct', loader.Account_vod__c);
            writer.writeAttribute(null, null, 'territory', loader.Territory_vod__c);
            writer.writeEndElement();
        }
        writer.writeEndElement();
        writer.writeEndDocument();
        String xmlOutput = writer.getXmlString();
        writer.close();
        return xmlOutput;
    }
            
    static List<Account_Territory_Loader_vod__c> parse(String xmldoc) {
        Account_Territory_Loader_vod__c[] loaders = new List<Account_Territory_Loader_vod__c>();
        XmlStreamReader reader = new XmlStreamReader(xmldoc);
        while(reader.hasNext()) {
            reader.next();
            if (reader.getEventType() == XmlTag.START_ELEMENT) {
                if ('loader' == reader.getLocalName()) {
                    String acct = reader.getAttributeValue(null, 'acct');   
                    String terr = reader.getAttributeValue(null, 'territory');
                    Account_Territory_Loader_vod__c loader = new Account_Territory_Loader_vod__c(Account_vod__c=acct, Territory_vod__c=terr);
                    loaders.add(loader);
                }
           } 
        }
        return loaders;
    }
}