BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/BMS_EMEA_BatchMeeting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Country settings for meeting start date notification</description>
    <fields>
        <fullName>Notification_2_Delay__c</fullName>
        <defaultValue>7</defaultValue>
        <label>Delay for 2nd email reminder</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notification_delay__c</fullName>
        <defaultValue>14</defaultValue>
        <label>Delay for 1st email reminder</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BMS EMEA Batch Meeting notification</label>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/objects/Medical_Event_vod__c.object
<CustomObject>
    <description>This object is used to store medical events. It is not related to the base salesforce.com event (calendar event) object. It has one standard child (event attendees), but custom objects can be added as children to track different attributes of medical events. Medical Event is a top level object with its own security and is referred to in the interaction reporting functionality.</description>
    <fields>
        <fullName>Country_MasterFile_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: Country of the Meeting, populated from the Master File.</description>
        <formula>TEXT( Master_File_BMS_EMEA__r.Country_BMS_EMEA__c )</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Notification_2_flag_BMS_EMEA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>VPRO EMEA March 2014: Used in an Apex Batch job. Number of days prior to the Meeting Date when an email alert is fired to the Meeting Owner as a 2nd reminder.</description>
        <label>Delay for 2nd email reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email_Notification_flag_BMS_EMEA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>VPRO EMEA March 2014: Used in an Apex Batch job. Number of days prior to the Meeting Planned Date when an email alert is fired to the Meeting Owner as a 1st reminder.</description>
        <label>Delay for 1st email reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FFM_Step_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field used to match the Master File record with the Document Template object (to expose the required fields)</description>
        <label>FFM Step</label>
        <picklist>
            <picklistValues>
                <fullName>Meeting Planning</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Post-Execution</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date_vod__c</fullName>
        <description>The start date of the event.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status_BMS_CORE__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Saved</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted - Waiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <recordTypes>
        <fullName>Execution</fullName>
        <active>true</active>
        <description>Execution / En exécution</description>
        <label>3. Execution</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EMSIM-AllTriggers&Apex/src/classes/BatchMeetingNotification_BMS_EMEA.cls
global  class BatchMeetingNotification_BMS_EMEA implements Database.Batchable<SObject>{

    public String query;
    Date currentDate = date.today();

    global Database.QueryLocator start(Database.BatchableContext BC){

        //Query the needed meetings
        query = ('Select Id,Name,Start_Date_vod__c,Status_BMS_CORE__c,FFM_Step_BMS_EMEA__c,Email_Notification_flag_BMS_EMEA__c,Country_MasterFile_BMS_EMEA__c From Medical_Event_vod__c WHERE Status_BMS_CORE__c=\'Approved\' AND FFM_Step_BMS_EMEA__c=\'Meeting Post-Execution\' ');
        query += ' AND (Email_Notification_flag_BMS_EMEA__c = false OR Email_Notification_2_flag_BMS_EMEA__c = false)'; //added by Viktor to make this scalable
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<SObject> scope){
        
        List<Medical_Event_vod__c> meetingList = (List<Medical_Event_vod__c>) scope;
        
        //Inititate custom settings
        List<BMS_EMEA_BatchMeeting__c> notificationSettings = new list<BMS_EMEA_BatchMeeting__c>();
        
        notificationSettings = [select id,Name,Notification_delay__c from BMS_EMEA_BatchMeeting__c];
        
        Map<String, BMS_EMEA_BatchMeeting__c> mcs = BMS_EMEA_BatchMeeting__c.getAll();
        
        system.debug('--- NOtification Settings ---'+mcs);
        
        //Process each meeting
        for(Medical_Event_vod__c medicalEvent : meetingList){
            
            //REtrive country setting
            BMS_EMEA_BatchMeeting__c setting = mcs.get(medicalEvent.Country_MasterFile_BMS_EMEA__c);
             
            if(setting != null){
                //Check notification delay
                system.debug('--- Country -----'+setting.Name);
                system.debug('--- Notification delay -----'+setting.Notification_delay__c);
                
                integer delay = integer.valueOf(setting.Notification_delay__c);
                integer delay2 = integer.valueOf(setting.Notification_2_delay__c);
                
                System.debug('--- current date + delay '+currentDate.addDays(delay));
                system.debug('--- Meeting Start Date ---'+medicalEvent.Start_Date_vod__c);
                
                if(currentDate.addDays(delay)  >= medicalEvent.Start_Date_vod__c){
                    
                    //Set notification flag
                    medicalEvent.Email_Notification_flag_BMS_EMEA__c = true;
                }
                
                if(currentDate.addDays(delay2)  >= medicalEvent.Start_Date_vod__c)
                    medicalEvent.Email_Notification_2_flag_BMS_EMEA__c = true;
            }else{
                //Use the default value
                setting = mcs.get('Default');
                
                system.debug('--- Default delay -----'+setting.Notification_delay__c);
                
                integer delay = integer.valueOf(setting.Notification_delay__c);
                integer delay2 = integer.valueOf(setting.Notification_2_delay__c); 
                
                if(delay != null){
                    if(currentDate.addDays(delay)  >= medicalEvent.Start_Date_vod__c){
                     
                        //Set notification flag
                        medicalEvent.Email_Notification_flag_BMS_EMEA__c = true;
                    }
                }
                if(delay2 != null){   
                    if(currentDate.addDays(delay2)  >= medicalEvent.Start_Date_vod__c)
                        medicalEvent.Email_Notification_2_flag_BMS_EMEA__c = true;
                
                }
            }           
        }
        
        //Update meeting list
        update meetingList;
        
    }

    global void finish(Database.BatchableContext BC){
        
    }
    
}