BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/BMS_EMEA_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>VPRO Nov 2013: custom settings used to store EMEA variables (record type ID etc.).</description>
    <fields>
        <fullName>New_Meeting_button_Recordtype__c</fullName>
        <inlineHelpText>DeveloperName of the record types used in the &quot;New Meeting&quot; customized button.</inlineHelpText>
        <label>New Meeting button Recordtype</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>BMS EMEA Settings</label>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Master_File_BMS_EMEA__c.object
<CustomObject>
    <description>VPRO Oct 2013: Object part of the Field Force Meeting module for BMS EMEA. Master Files created by Marketing Leads will be stored here and then shared with Reps or MSM.</description>
    <fields>
        <fullName>End_Date_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: End Date (month) of the Master File.</description>
        <label>End Month</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HCPs_registration_fees_Event_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: Number field to track HCP Registration cost.</description>
        <inlineHelpText>Registration fees for third party event</inlineHelpText>
        <label>Budgeted HCPs Registration Fees</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Honorarium_Event_Budget_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: Number field to track Honorarium max budget per event.</description>
        <inlineHelpText>Honorarium for HCPs services aligned with Fair Market Value (a contract will be required)</inlineHelpText>
        <label>Budgeted Honorarium</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hotel_Event_Budget_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: Number field to track accommodation costs.</description>
        <label>Budgeted Hotel</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meals_Event_Budget_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: Number field to track costs related to Meals.</description>
        <label>Budgeted Meals</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_August_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meeting August</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_Dec_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meeting December</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_July_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meeting Jul</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_June_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meeting Jun</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_May_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meeting May</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_Name_guidance_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: Free text, no particular rules. Guidance around the name of the related Meetings.</description>
        <label>Meeting Name (guidance)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_November_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meeting Nov</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_October_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meeting Oct</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_September_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meeting Sep</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meetings_April_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meetings Apr</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meetings_February_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meetings Feb</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meetings_January_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meetings Jan</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meetings_March_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meetings Mar</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Objective_Total_BMS_EMEA__c</fullName>
        <label>Objective Total</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Other_Costs_Event_Budget_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: Number field to track costs that do not fit in any other cost sub-category.</description>
        <label>Budgeted Other Costs</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sponsorship_of_Event_Budget_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: Number field to track costs related to the Sponsorship of Event.</description>
        <inlineHelpText>Sponsorship to participate in third party or hospital event  (a contract will be required)</inlineHelpText>
        <label>Budgeted Sponsorship</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: Start Date (month) of the Master File.</description>
        <label>Start Month</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Targeted_number_of_Meetings_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: Number field used in many formulas.</description>
        <label>Targeted number of Meetings</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transportation_Budget_Event_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: Number field to track costs related to Transportation.</description>
        <label>Budgeted Transportation</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Audience_Participants_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: roll-up summary field from the Master File Participants where the type is Audience.</description>
        <label># of Audience Participants</label>
        <summarizedField>Master_File_Participant_BMS_EMEA__c.Number_per_Meeting_BMS_EMEA__c</summarizedField>
        <summaryFilterItems>
            <field>Master_File_Participant_BMS_EMEA__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>BMS - EMEA - Audience</value>
        </summaryFilterItems>
        <summaryForeignKey>Master_File_Participant_BMS_EMEA__c.Master_File_BMS_EMEA__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>of_BMS_Employees_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: roll-up summary field from the Master File Participants where the type is BMS Employee.</description>
        <label># of BMS Employees</label>
        <summarizedField>Master_File_Participant_BMS_EMEA__c.Number_per_Meeting_BMS_EMEA__c</summarizedField>
        <summaryFilterItems>
            <field>Master_File_Participant_BMS_EMEA__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>BMS - EMEA - BMS Employee</value>
        </summaryFilterItems>
        <summaryForeignKey>Master_File_Participant_BMS_EMEA__c.Master_File_BMS_EMEA__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>of_Sponsored_Participants_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: roll-up summary field from the Master File Participants where the type is Sponsored.</description>
        <label># of Sponsored Participants</label>
        <summarizedField>Master_File_Participant_BMS_EMEA__c.Number_per_Meeting_BMS_EMEA__c</summarizedField>
        <summaryFilterItems>
            <field>Master_File_Participant_BMS_EMEA__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>BMS - EMEA - Sponsored</value>
        </summaryFilterItems>
        <summaryForeignKey>Master_File_Participant_BMS_EMEA__c.Master_File_BMS_EMEA__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Master File</label>
    <nameField>
        <displayFormat>MF-{00000}</displayFormat>
        <label>Master File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Files</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/objects/Medical_Event_vod__c.object
<CustomObject>
    <description>This object is used to store medical events. It is not related to the base salesforce.com event (calendar event) object. It has one standard child (event attendees), but custom objects can be added as children to track different attributes of medical events. Medical Event is a top level object with its own security and is referred to in the interaction reporting functionality.</description>
    <fields>
        <fullName>Master_File_BMS_EMEA__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>TT 30/10/2013: any Meeting created by Reps must be related to a Master File.</description>
        <label>Master File</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Master File cannot be of type Standard Rep Presentation. You need to create an interaction instead to record Standard Rep Presentations.</errorMessage>
            <filterItems>
                <field>Master_File_BMS_EMEA__c.Activity_Type_BMS_EMEA__c</field>
                <operation>notEqual</operation>
                <value>Standard Representative Presentation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Master_File_BMS_EMEA__c</referenceTo>
        <relationshipLabel>Meetings</relationshipLabel>
        <relationshipName>Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_to_notify_BMS_EMEA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>VPRO March 2014: Optional field to add person to notify on Meeting Plan approval. User that is other than the Approver.</description>
        <label>Person to notify</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Meetings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <recordTypes>
        <fullName>Master</fullName>
        <active>true</active>
        <description>Default Record Type with Medical Event page layout assigned</description>
        <label>Master</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/classes/NewMeeting_BMS_EMEA.cls
public with sharing class NewMeeting_BMS_EMEA {
        
        public id masterfileID {get;set;}
        public Master_File_BMS_EMEA__c masterFile{get; set;} 
        public RecordType meetingPlanRecId  {get;set;}
        public Medical_Event_vod__c meeting {get;set;}
        public String userName {get;set;}
        list<String> customFields = new list<String>();
        
        public boolean customSectionView{ 
            get{
                if(customFields.size()>0) return true;
                else return false;
            }
        }
        
        public NewMeeting_BMS_EMEA(ApexPages.StandardController controller) {
                
            masterfileID = ApexPages.currentPage().getParameters().get('id');
                    
                    //Get details about this master file
            masterFile = [SELECT  Id,Meeting_Name_guidance_BMS_EMEA__c,Other_Costs_Event_Budget_BMS_EMEA__c,Hotel_Event_Budget_BMS_EMEA__c,Meals_Event_Budget_BMS_EMEA__c,Transportation_Budget_Event_BMS_EMEA__c,Sponsorship_of_Event_Budget_BMS_EMEA__c,HCPs_registration_fees_Event_BMS_EMEA__c ,Honorarium_Event_Budget_BMS_EMEA__c,of_Sponsored_Participants_BMS_EMEA__c,of_Audience_Participants_BMS_EMEA__c,of_BMS_Employees_BMS_EMEA__c,Targeted_number_of_Meetings_BMS_EMEA__c,Objective_Total_BMS_EMEA__c,End_Date_BMS_EMEA__c,Start_Date_BMS_EMEA__c,Meetings_January_BMS_EMEA__c,Meetings_February_BMS_EMEA__c,Meetings_March_BMS_EMEA__c,Meetings_April_BMS_EMEA__c,Meeting_May_BMS_EMEA__c,
                                Meeting_June_BMS_EMEA__c,Meeting_July_BMS_EMEA__c,Meeting_August_BMS_EMEA__c,Meeting_September_BMS_EMEA__c,Meeting_October_BMS_EMEA__c,Meeting_November_BMS_EMEA__c,Meeting_Dec_BMS_EMEA__c
                          FROM Master_File_BMS_EMEA__c
                          WHERE Id = :this.MasterFileID];
            
            //Get Recordtype custom settings
            BMS_EMEA_Settings__c bmsEmea = BMS_EMEA_Settings__c.getInstance();
            
            String newMeetingRecordtype = bmsEmea.New_Meeting_button_Recordtype__c;
            
            system.debug('--- New Meeting RecordType ---'+newMeetingRecordtype);
                          
            meetingPlanRecId = [select SobjectType,Name,IsActive,Id,DeveloperName From RecordType where SobjectType='Medical_Event_vod__c' and DeveloperName=:newMeetingRecordtype];                               
            
            userName = UserInfo.getName();
            
            //Create new medical event
            meeting = new  Medical_Event_vod__c();
                     
            meeting.RecordTypeId = meetingPlanRecId.id;
            meeting.Master_File_BMS_EMEA__c = masterFile.Id;
            meeting.Name = masterfile.Meeting_Name_guidance_BMS_EMEA__c;
                     
            meeting.OwnerId = UserInfo.getUserId(); 
            
            string LineManagerid = [SELECT Id, ManagerId from User where Id =: meeting.OwnerId].ManagerId;
            meeting.Person_to_notify_BMS_EMEA__c =LineManagerid ;
            
        }
        
     //Custom fields section, added by Viktor 2014-03-20
     public Component.Apex.PageBlockSection getCustomFields(){
        BMS_EMEA_Settings__c bmsEmea = BMS_EMEA_Settings__c.getInstance();
        if(bmsEmea.New_Meeting_Custom_Fields__c!=null) customFields = bmsEmea.New_Meeting_Custom_Fields__c.split(';'); 
        
        Component.Apex.PageBlockSection section = new Component.Apex.PageBlockSection();
        section.Title = 'Additional Fields';
        section.collapsible = false;
        section.rendered = customSectionView;
        
        for(String fieldDevName : customFields){
            Component.Apex.InputField inFld = new Component.Apex.InputField();
            inFld.expressions.value = '{!meeting.' + fieldDevName + '}';
            section.childComponents.add( inFld );
        }
        
        return section;
     }
     
        
     public PageReference saveMeeting(){
                
         try{
            insert meeting;
         }catch(System.DmlException e){
            for (Integer i = 0; i < e.getNumDml(); i++) {
                if(e.getDmlFieldNames(i).size()==0)
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getDmlMessage(i) ));
            }
            return null;
         }     
        
         PageReference pageRef = new PageReference('/'+meeting.id);
            
         return pageRef;
         
    }
}