BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/BMSNeedToEventInheritance__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Details what should be copied to an activity when a new activity budget is added</description>
    <fields>
        <fullName>Header_Field_Mapping_2__c</fullName>
        <label>Header Field Mapping 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Header_Field_Mapping_3__c</fullName>
        <label>Header Field Mapping 3</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Header_Field_Mapping_4__c</fullName>
        <label>Header Field Mapping 4</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Header_Field_Mapping_5__c</fullName>
        <label>Header Field Mapping 5</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Header_Field_Mapping__c</fullName>
        <description>These fields will be copied from the need to the event. The format should be sourceField:activityField;sourceField2:activityField2...</description>
        <inlineHelpText>These fields will be copied from the need to the event. The format should be sourceField:activityField;sourceField2:activityField2...</inlineHelpText>
        <label>Header Field Mapping</label>
        <type>TextArea</type>
    </fields>
    <label>BMSNeedToEventInheritance</label>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PROD ListViews/src/objects/EM_Budget_vod__c.object
<CustomObject>
</CustomObject>

BMSSimplificationEclipseWS/murugesh.naidu@EUFULL-TrackerUpdates/src/objects/EM_Budget_vod__c.object
    <fields>
        <fullName>External_ID_vod__c</fullName>
        <description>External ID</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithoutProfilesXLation/src/objects/EM_Event_Budget_vod__c.object
<CustomObject>
    <fields>
        <fullName>Event_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The activity that is accessing the budget</description>
        <label>Event</label>
        <referenceTo>EM_Event_vod__c</referenceTo>
        <relationshipLabel>WBS/CCs</relationshipLabel>
        <relationshipName>Event_vod</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithoutProfilesXLation/src/objects/EM_Event_vod__c.object
<CustomObject>
</CustomObject>

BMSSimplificationEclipseWS/murugesh.naidu@EUFULL-TrackerUpdates/src/objects/EM_Event_vod__c.object
    <fields>
        <fullName>External_ID_vod__c</fullName>
        <description>External ID.</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

BMSSimplificationEclipseWS/murugesh.naidu@EUFULL-TrackerUpdates/src/objects/EM_Event_vod__c.object
    <fields>
        <fullName>Mobile_ID_vod__c</fullName>
        <description>Field used by mobile products for synchronization.</description>
        <externalId>true</externalId>
        <label>Mobile ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithoutProfilesXLation/src/objects/EM_Expense_Estimate_vod__c.object
<CustomObject>
    <fields>
        <fullName>Event_Budget_vod__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used to pull estimates from budgets to impact future planning.</description>
        <label>WBS/CC</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>EM_Event_Budget_vod__c.Event_vod__c</field>
                <operation>equals</operation>
                <valueField>$Source.Event_vod__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>EM_Event_Budget_vod__c</referenceTo>
        <relationshipLabel>Expense Estimates</relationshipLabel>
        <relationshipName>EM_Expense_Estimate_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_vod__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used for expense estimate rollups on an Activity. Do not use this field if using Activity Budgets.</description>
        <label>Event</label>
        <referenceTo>EM_Event_vod__c</referenceTo>
        <relationshipLabel>Expense Estimates</relationshipLabel>
        <relationshipName>Expense_Estimate_vod</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/EM_Expense_Estimate_vod__c.object
    <fields>
        <fullName>Actual_vod__c</fullName>
        <description>Sum of actual values from related expense lines. This value is managed by a Veeva trigger.</description>
        <label>Actual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/EM_Expense_Estimate_vod__c.object
    <fields>
        <fullName>Committed_vod__c</fullName>
        <description>Sum of committed values from related expense lines. This value is managed by a Veeva trigger.</description>
        <label>Committed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/EM_Expense_Estimate_vod__c.object
    <fields>
        <fullName>Estimate_vod__c</fullName>
        <description>Estimated expense.</description>
        <label>Estimate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/EM_Expense_Estimate_vod__c.object
    <fields>
        <fullName>Expense_Type_Code_vod__c</fullName>
        <description>Stamped value of the expense type code as the expense was recorded. This value will remain constant even if the expense type changes.</description>
        <label>Expense Type Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/EM_Expense_Estimate_vod__c.object
    <fields>
        <fullName>Expense_Type_Name_vod__c</fullName>
        <description>Stamped value of the expense type as the expense was recorded. This value will remain constant even if the expense type changes.</description>
        <label>Expense Type Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/EM_Expense_Estimate_vod__c.object
    <fields>
        <fullName>Expense_Type_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship to an expense type for the expense estimate</description>
        <label>Expense Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Expense_Type_vod__c.Active_vod__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Expense_Type_vod__c</referenceTo>
        <relationshipLabel>Expense Estimates</relationshipLabel>
        <relationshipName>Expense_Type_vod</relationshipName>
        <type>Lookup</type>
    </fields>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/EM_Expense_Estimate_vod__c.object
    <fields>
        <fullName>External_ID_vod__c</fullName>
        <description>External ID</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/EM_Expense_Estimate_vod__c.object
    <fields>
        <fullName>Mobile_ID_vod__c</fullName>
        <description>Field used by mobile products for synchronization.</description>
        <externalId>true</externalId>
        <label>Mobile ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/EM_Expense_Estimate_vod__c.object
    <fields>
        <fullName>Parent_Expense_Type_Code_vod__c</fullName>
        <description>Stamped value of the parent expense type code as the expense was recorded. This value will remain constant even if the expense type changes.</description>
        <label>Parent Expense Type Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/objects/Expense_Type_vod__c.object
<CustomObject>
    <description>Defines expense types.</description>
    <fields>
        <fullName>External_ID_vod__c</fullName>
        <description>External ID</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Expense Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Need_Expense_Estimate_HCPTS__c.object
<CustomObject>
    <fields>
        <fullName>Actual_vod__c</fullName>
        <label>Actual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Committed_vod__c</fullName>
        <label>Committed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimate_vod__c</fullName>
        <label>Estimate Per Activity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expense_Type_Code_vod__c</fullName>
        <label>Expense Type Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expense_Type_Name_vod__c</fullName>
        <label>Expense Type Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expense_Type_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expense Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Expense_Type_vod__c.Active_vod__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Expense_Type_vod__c</referenceTo>
        <relationshipLabel>Need Expense Estimates</relationshipLabel>
        <relationshipName>Need_Expense_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_ID_vod__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Mobile_ID_vod__c</fullName>
        <externalId>true</externalId>
        <label>Mobile ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Need__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Need</label>
        <referenceTo>EM_Budget_vod__c</referenceTo>
        <relationshipLabel>Expense Estimates</relationshipLabel>
        <relationshipName>Need_Expense_Estimates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Need Expense Estimate</label>
    <nameField>
        <displayFormat>NEE -{0000000000}</displayFormat>
        <label>Need Expense Estimate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Need Expense Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Participants_HCPTS__c.object
<CustomObject>
    <description>Participant information for EM Initiatives</description>
    <fields>
        <fullName>Activity_HCPTS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to an Activity  - Only applies if you are creating a Participant record on an Activity. This field must be blank if you are creating a Participant record on a Need. This will should auto-populate on the UI if you are creating this from an Activity detail page.</description>
        <inlineHelpText>Lookup to an Activity  - Only applies if you are creating a Participant record on an Activity. This field must be blank if you are creating a Participant record on a Need. This will should auto-populate on the UI if you are creating this from an Activity</inlineHelpText>
        <label>Activity</label>
        <referenceTo>EM_Event_vod__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>EventParticipants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget_HCPTS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent Need - Only applies if you are creating a Participant record on the Need. This field must be blank if you are creating a Participant record on an Activity. This field will auto-populate on the UI if creating from a Need/Budget detail page</description>
        <inlineHelpText>Parent Need - Only applies if you are creating a Participant record on the Need. This field must be blank if you are creating a Participant record on an Activity. This field will auto-populate on the UI if creating from a Need/Budget detail page</inlineHelpText>
        <label>Need</label>
        <referenceTo>EM_Budget_vod__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>BudgetParticipants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mobile_ID_vod__c</fullName>
        <externalId>true</externalId>
        <label>Mobile ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Participants</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/classes/VPROF_Need_Inheritance.cls
public class VPROF_Need_Inheritance {
    
    public static Integer timeDelay = 12;

    public static void inheritHeaderInfo(EM_Event_Budget_vod__c activityBudget, EM_Event_vod__c activity,
                    BMSNeedToEventInheritance__c inheritanceSetting,EM_Budget_vod__c need){

        // get the field mappings
        String fieldCopyMapping = '';
        if(inheritanceSetting.Header_Field_Mapping__c!=null && inheritanceSetting.Header_Field_Mapping__c.trim()!=''){
            fieldCopyMapping+=inheritanceSetting.Header_Field_Mapping__c;
        }
        if(inheritanceSetting.Header_Field_Mapping_2__c!=null && inheritanceSetting.Header_Field_Mapping_2__c.trim()!=''){
            fieldCopyMapping+=inheritanceSetting.Header_Field_Mapping_2__c;
        }
        if(inheritanceSetting.Header_Field_Mapping_3__c!=null && inheritanceSetting.Header_Field_Mapping_3__c.trim()!=''){
            fieldCopyMapping+=inheritanceSetting.Header_Field_Mapping_3__c;
        }
        if(inheritanceSetting.Header_Field_Mapping_4__c!=null && inheritanceSetting.Header_Field_Mapping_4__c.trim()!=''){
            fieldCopyMapping+=inheritanceSetting.Header_Field_Mapping_4__c;
        }
        if(inheritanceSetting.Header_Field_Mapping_5__c!=null && inheritanceSetting.Header_Field_Mapping_5__c.trim()!=''){
            fieldCopyMapping+=inheritanceSetting.Header_Field_Mapping_5__c;
        }

        // populated the fields into the activity, populate the inherited need field, and udpate the activity
        if(fieldCopyMapping!=null && fieldCopyMapping.trim()!=''){
            String[] mappings = fieldCopyMapping.split(';');
            for(String aMapping: mappings){
                String budgetFieldName = aMapping.subStringBefore(':').trim();
                String eventFieldName = aMapping.subStringAfter(':').trim();
                System.debug('budgetFieldName: ' + budgetFieldName + '  eventFieldName: ' + eventFieldName);
                if(need.get(budgetFieldName)!=null){
                    activity.put(eventFieldName, need.get(budgetFieldName));//sets the Event field with Budget field value
                }
            }
        }
        activityBudget.Is_Need__c = true;
        update activity;

    }

    public static void inheritParticipants(ID activityBudgetId, Id activityId, Id needId){

        String participantQry = CustomVeevaUtilities.getDynamicSOQLForAllEligibleFields(Participants_HCPTS__c.sObjectType);
        participantQry += ' WHERE Budget_HCPTS__c = \'' + needId + '\'';
        List<Participants_HCPTS__c> parts = Database.query(participantQry);
        List<Participants_HCPTS__c> partsToInsert = new List<Participants_HCPTS__c>();
        for(Participants_HCPTS__c part: parts){
            Participants_HCPTS__c newPart = part.clone(false, true, false, false);
            newPart.Budget_HCPTS__c = null;
            newPart.Activity_HCPTS__c = activityId;
            partsToInsert.add(newPart);
        }
        insert partsToInsert;
    
    }

    public static void scheduleExpenseEstimateInheritance(Id activityBudgetId, Id activityId, Id needId){

        inheritExpenseEstimateFuture(activityBudgetId,activityId,needId,UserInfo.getUserId());

        Long startingTime = System.now().getTime(); // Num milliseconds since Jan 1 1970
        Integer delayInMilliseconds = 1000 * timeDelay;
        while (System.now().getTime() - startingTime < delayInMilliseconds)  {
            // Do nothing until desired delay has passed
        }

        System.debug('Testing if it worked: ' + System.now().getTime());

        // see if it worked, email the user to let them know that their request is being processed
        EM_Event_Budget_vod__c activityBudget = [SELECT Id,Failure_Inheriting_Expense_Estimates__c,Waiting_for_Expense_Estimate_Inheritance__c
                            FROM EM_Event_Budget_vod__c WHERE Id = :activityBudgetId];

        if(activityBudget.Failure_Inheriting_Expense_Estimates__c == false && activityBudget.Waiting_for_Expense_Estimate_Inheritance__c == true){

            Messaging.SingleEmailMessage errorEmail = new Messaging.SingleEmailMessage();
            errorEmail.setTargetObjectID(UserInfo.getUserId());
            errorEmail.setSubject(Label.Expense_Estimate_Inheritance_Delay);
            errorEmail.saveAsActivity = false;
            String emailBody = Label.Exp_Estimate_Inherit_Delay_Body_1;
            emailBody += ' ' + System.Url.getSalesforceBaseURL().toExternalForm() + '/' + activityId + ' ';
            emailBody += Label.Exp_Estimate_Inherit_Delay_Body_2;
            errorEmail.setHtmlBody(emailBody);

            Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{errorEmail});

        }
    }

    public static void inheritExpenseEstimate(Id activityBudgetId, Id activityId, Id needId){
        // delete the existing expense estimates on the activity
        List<EM_Expense_Estimate_vod__c> expEstimates = [SELECT Id FROM EM_Expense_Estimate_vod__c WHERE Event_vod__c = :activityId];
        Database.DeleteResult[] results = Database.delete(expEstimates, false);

        // copy over the new expense estimates
        String needEEQry = CustomVeevaUtilities.getDynamicSOQLForAllEligibleFields(Need_Expense_Estimate_HCPTS__c.sObjectType);
        needEEQry += ' WHERE Need__c = \'' + needId + '\'';
        List<Need_Expense_Estimate_HCPTS__c> needExpEstimtes = Database.query(needEEQry);
        List<EM_Expense_Estimate_vod__c> eesToInsert = new List<EM_Expense_Estimate_vod__c>();
        for(Need_Expense_Estimate_HCPTS__c nExpEst: needExpEstimtes){
            EM_Expense_Estimate_vod__c newEstimate = new EM_Expense_Estimate_vod__c();
            newEstimate.Actual_vod__c = nExpEst.Actual_vod__c;
            newEstimate.Committed_vod__c = nExpEst.Committed_vod__c;
            newEstimate.Estimate_vod__c = nExpEst.Estimate_vod__c;
            newEstimate.Expense_Type_vod__c = nExpEst.Expense_Type_vod__c;
            newEstimate.Expense_Type_Code_vod__c = nExpEst.Expense_Type_Code_vod__c;
            newEstimate.Expense_Type_Name_vod__c = nExpEst.Expense_Type_Name_vod__c;
            newEstimate.External_ID_vod__c = nExpEst.External_ID_vod__c;
            newEstimate.Mobile_ID_vod__c = nExpEst.Mobile_ID_vod__c;
            newEstimate.Parent_Expense_Type_Code_vod__c = nExpEst.Parent_Expense_Type_Code_vod__c;
            newEstimate.Parent_Expense_Type_Name_vod__c = nExpEst.Parent_Expense_Type_Name_vod__c;
            newEstimate.zvod_Expense_Type_vod__c = nExpEst.zvod_Expense_Type_vod__c;
            newEstimate.Event_vod__c = activityId;
            newEstimate.Event_Budget_vod__c = activityBudgetId;
            eesToInsert.add(newEstimate);
        }
        insert eesToInsert;
    }

    @future
    public static void inheritExpenseEstimateFuture(Id activityBudgetId, Id activityId, Id needId, Id userId){

        System.debug('Future call starting: ' + System.now().getTime());

        try{
            
            List<LockActivityChildren__c> lockedChildren = CustomVeevaUtilities.unlockForEdits('EM_Event_Budget_vod__c');
            List<LockActivityChildren__c> lockedChildren2 = CustomVeevaUtilities.unlockForEdits('EM_Expense_Estimate_vod__c');

            inheritExpenseEstimate(activityBudgetId, activityId, needId);
            EM_Event_Budget_vod__c activityBudget = new EM_Event_Budget_vod__c();
            activityBudget.Id = activityBudgetId;
            activityBudget.Waiting_for_Expense_Estimate_Inheritance__c = false;
            update activityBudget;

            if(lockedChildren!=null && lockedChildren.size() > 0){
               CustomVeevaUtilities.relockForEdits(lockedChildren);         
            }
            if(lockedChildren2!=null && lockedChildren2.size() > 0){
               CustomVeevaUtilities.relockForEdits(lockedChildren2);            
            }

            System.debug('Future call ending: ' + System.now().getTime());

            //throw new testException('Test error! There was a problem and this is the error message.');

        }Catch(Exception e){

            //if there is an error, send the user an email to alert them

            EM_Event_Budget_vod__c activityBudget = new EM_Event_Budget_vod__c();
            activityBudget.Id = activityBudgetId;
            activityBudget.Waiting_for_Expense_Estimate_Inheritance__c = false;
            activityBudget.Failure_Inheriting_Expense_Estimates__c = true;
            update activityBudget;

            Messaging.SingleEmailMessage errorEmail = new Messaging.SingleEmailMessage();
            errorEmail.setTargetObjectID(userId);
            errorEmail.setSubject(Label.Expense_Estimate_Inheritance_Failure);
            errorEmail.saveAsActivity = false;
            String emailBody = Label.EE_Inheritance_Failure_1;
            emailBody += ' ' + System.Url.getSalesforceBaseURL().toExternalForm() + '/' + needId;
            emailBody += ' ' + Label.EE_Inheritance_Failure_2;
            emailBody += ' ' + System.Url.getSalesforceBaseURL().toExternalForm() + '/' + activityId;
            emailBody += ' ' + Label.EE_Inheritance_Failure_3;
            emailBody += '<br />' + e.getMessage();
            errorEmail.setHtmlBody(emailBody);

            Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{errorEmail});

        }
    }

    //public class testException extends Exception {}

}