BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Contract_Partner_vod__c.object
<CustomObject>
    <description>Child of the Contract_vod object. One row represents an entity (Account) who has been associated to a Contract.</description>
    <fields>
        <fullName>Contract_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to corresponding Contract header.</description>
        <label>Contract</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>((1 AND 2) OR (3 AND 4) OR ( NOT (1 OR 2 OR 3 OR 4))) AND 5 AND 6</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sales_vod</value>
            </filterItems>
            <filterItems>
                <field>Contract_vod__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sales_vod</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Listing_vod</value>
            </filterItems>
            <filterItems>
                <field>Contract_vod__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Listing_vod</value>
            </filterItems>
            <filterItems>
                <field>Contract_vod__c.Template_vod__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>Contract_vod__c.Agreement_vod__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract_vod__c</referenceTo>
        <relationshipName>Contract_Partners_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date_vod__c</fullName>
        <description>Auto-populated by Contract Header; stores and shows the Contract end date.</description>
        <formula>Contract_vod__r.End_Date_vod__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date_vod__c</fullName>
        <description>Auto-populated by Contract Header; stores and shows the Contract start date.</description>
        <formula>Contract_vod__r.Start_Date_vod__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status_vod__c</fullName>
        <description>Stores the status of a Contract Partner record. If the status is &quot;Activated&quot; and the current date is between the Contract Partner start and end dates, the Contract associated with the Contract Partner record can be associated with an Order or Inventory Monitoring.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Rejected_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved_vod</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Activated_vod</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract Recipient</label>
    <nameField>
        <displayFormat>CP-{000000000}</displayFormat>
        <label>Contract Partner ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Recipients</pluralLabel>
    <recordTypes>
        <fullName>Framework_Agreement</fullName>
        <active>true</active>
        <description>Corresponding recordtype for Contract - Framework Agreement</description>
        <label>Framework Agreement</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/objects/EM_Event_Speaker_vod__c.object
<CustomObject>
    <description>Service Provider at an Activity for Veeva Event Management.</description>
    <fields>
        <fullName>Contract_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to select the contract being applied to a speaker for a particular event for Veeva Event Management.</description>
        <label>zContract</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>$Source.Speaker_vod__c</field>
                <operation>equals</operation>
                <valueField>Contract_vod__c.Speaker_HCPTS__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contract_vod__c.Status_vod__c</field>
                <operation>equals</operation>
                <value>Signed</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract_vod__c</referenceTo>
        <relationshipName>Event_Speakers_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_HCPTS__c</fullName>
        <formula>Speaker_vod__r.Country_HCPTS__c</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Language_HCPTS__c</fullName>
        <formula>TEXT(Speaker_vod__r.Preferred_Language_HCPTS__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Preferred Language</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Type_HCPTS__c</fullName>
        <description>Helps categorize a Contract per BMS Service Type. Please note: Long-term &amp; Short-term apply to Services Contract. Short-term contracts do not include an MSA while Long-term contracts do when Contracts are sent out to HCP. Events and Sponsorship Contract types applies to Exhibits &amp; Sponsorship activities respectively.</description>
        <inlineHelpText>Helps categorize a Contract per BMS Service Type. Please note: Long-term &amp; Short-term apply to Services Contract. Short-term contracts do not include an MSA while Long-term contracts do when Contracts are sent out to HCP.</inlineHelpText>
        <label>Contract Type</label>
        <picklist>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Speaker_Contract_HCPTS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Framework Agreement</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contract_vod__c.Speaker_HCPTS__c</field>
                <operation>equals</operation>
                <valueField>$Source.Speaker_vod__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contract_vod__c.Status_vod__c</field>
                <operation>equals</operation>
                <value>Activated</value>
            </filterItems>
            <filterItems>
                <field>Contract_vod__c.Expired_vod__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>Contract_vod__c.Service_Type_HCPTS__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Type_HCPTS__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contract_vod__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Framework Agreement</value>
            </filterItems>
            <infoMessage>Only Signed unexpired Framework Agreements for the Speaker are selectable from this screen</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract_vod__c</referenceTo>
        <relationshipName>Event_Speakers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Speaker_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The speaker for an event.</description>
        <label>Service Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>EM_Speaker_vod__c.Status_vod__c</field>
                <operation>equals</operation>
                <value>Eligible_vod</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>EM_Speaker_vod__c</referenceTo>
        <relationshipName>Speakers_vod</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_vod__c</fullName>
        <description>Status of the speaker for the event.</description>
        <label>Veeva Status</label>
        <picklist>
            <picklistValues>
                <fullName>Nominated_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invited_vod</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cleared_Signature_vod</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Did Not Attend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined_Simple</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Event Service Provider</label>
    <nameField>
        <displayFormat>ESP-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Service Providers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Information_Collection_Form__c.object
<CustomObject>
    <fields>
        <fullName>Country_Formula_HCPTS__c</fullName>
        <description>Formula field to populate ICF Country from the Speaker&apos;s Country record</description>
        <formula>Speaker_HCPTS__r.Country_Lookup_HCPTS__r.Alpha_2_Code_vod__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Provider Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_HCPTS__c</fullName>
        <description>Country</description>
        <label>zCountry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expired_Formula_HCPTS__c</fullName>
        <formula>ICF_End_Date_HCPTS__c &lt; TODAY()</formula>
        <label>Expired?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ICF_Type_HCPTS__c</fullName>
        <description>ICF Type</description>
        <label>ICF Type</label>
        <picklist>
            <picklistValues>
                <fullName>HCP/Non-HCP Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HCO Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preferred_Language_HCPTS__c</fullName>
        <formula>Text(Speaker_HCPTS__r.Language_HCPTS__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Preferred Language</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Speaker_HCPTS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Provider</label>
        <referenceTo>EM_Speaker_vod__c</referenceTo>
        <relationshipLabel>Information Collection Forms</relationshipLabel>
        <relationshipName>Information_Collection_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_HCPTS__c</fullName>
        <description>Status of ICF</description>
        <label>ICF Status</label>
        <picklist>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Out for Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Counter-Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Counter-Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled / Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed Manually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vendor_HCPTS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Party Reference</label>
        <referenceTo>EM_Vendor_vod__c</referenceTo>
        <relationshipLabel>Information Collection Forms</relationshipLabel>
        <relationshipName>Information_Collection_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Information Collection Form</label>
    <nameField>
        <label>Information Collection Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Information Collection Forms</pluralLabel>
    <recordTypes>
        <fullName>ICF</fullName>
        <active>true</active>
        <description>ICF that is editable</description>
        <label>ICF</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EMSIM-AllTriggers&Apex/src/classes/VPROF_Javascript_Utilities.cls
global class VPROF_Javascript_Utilities {
    
    webservice static string getEchosignAgreementIdForICF(String ICFId){

        Information_Collection_Form__c icf = [SELECT Id,Country_Formula_HCPTS__c,Preferred_Language_HCPTS__c,ICF_Type_HCPTS__c
            FROM Information_Collection_Form__c WHERE Id = :ICFId];

        List<echosign_dev1__Agreement_Template__c> agreeTemplate = [SELECT Id 
                    FROM echosign_dev1__Agreement_Template__c
                    WHERE ICF_Type_HCPTS__c = :icf.ICF_Type_HCPTS__c
                    AND Language_HCPTS__c =:icf.Preferred_Language_HCPTS__c
                    AND Country_HCPTS__r.Alpha_2_Code_vod__c =:icf.Country_Formula_HCPTS__c
                    ORDER BY LastModifiedDate DESC LIMIT 1];

        if(agreeTemplate == null || agreeTemplate.size() != 1){
            return 'Error';
        }else{
            return agreeTemplate[0].Id;
        }
        
    }

    webservice static string renewMSA(String espId) {
        
        String errorMessage = '';

        try{

            EM_Event_Speaker_vod__c esp = [SELECT Id,Speaker_vod__c,Speaker_Contract_HCPTS__c,Service_Type_HCPTS__c
                    FROM EM_Event_Speaker_vod__c WHERE Id = :espId];

            List<Information_Collection_Form__c> eligibleICF =
                    [Select Id, Name, RecordtypeId, RecordType.Name, ICF_Type_HCPTS__c,Vendor_HCPTS__c
                    FROM Information_Collection_Form__c 
                    WHERE Speaker_HCPTS__c =: esp.Speaker_vod__c
                    AND ( Expired_Formula_HCPTS__c = false or Expired_Formula_HCPTS__c = null)
                    AND Status_HCPTS__c IN ('Signed', 'Signed Manually')
                    ORDER BY LastModifiedDate desc
                    LIMIT 1];

            Id contractPartyFromICF = null;

            if(eligibleICF!=null && eligibleICF.size() > 0){
                contractPartyFromICF = eligibleICF[0].Vendor_HCPTS__c;
            }

            Map<String, RecordType> rtMapByDevName = new Map<String, Recordtype>();
            List<RecordType> contractRecTypeLst = [SELECT Name, Id, DeveloperName, SobjectType FROM RecordType
                                                    WHERE Sobjecttype = 'Contract_vod__c' and IsActive = TRUE];
            for(RecordType r: contractRecTypeLst){
                rtMapByDevName.put(r.DeveloperName, r);
            }

            if(esp.Service_Type_HCPTS__c == 'Services'){//applicable to Services Contract Type
                    Contract_vod__c fwCntrct = new Contract_vod__c(Start_Date_vod__c = System.today(), 
                                        End_Date_vod__c = System.today().addYears(2),
                                        Speaker_HCPTS__c = esp.Speaker_vod__c,
                                        //      Name = 'FrameworkAgreement-'+ esp.Name,
                                        Service_Type_HCPTS__c = esp.Service_Type_HCPTS__c,
                                        Status_vod__c = 'Draft_vod',
                                        RecordTypeId = rtMapByDevName.get('Framework_Agreement').Id,
                                        Vendor_HCPTS__c = contractPartyFromICF);
                    insert fwCntrct;
                    insert new Contract_Partner_vod__c(EM_Speaker_vod__c = esp.Speaker_vod__c, Contract_vod__c = fwCntrct.Id, Status_vod__c = 'Draft_vod');
                    esp.Speaker_Contract_HCPTS__c = fwCntrct.Id;
                    update esp;
                
            }else{
                return Label.Framework_renewal_only_Services;
            }
            errorMessage = Label.Framework_Update_Success;
        }Catch(Exception e){
            return Label.Error_updating_MSA + ' ' + e.getMessage();
        }

        return errorMessage;
    }
    
    /**
* Utilitiy function to convert a RecType Map with Names as Keys to DeveloperName as keys
*/
    public static Map<String, RecordTypeInfo> getMapByRecordTypeDevName(
                                                Map<String, RecordTypeInfo> rtMapByName){

        if(rtMapByName==null || rtMapByName.size() == 0){
            return rtMapByName;
        }
        Set<Id> rtIds = new Set<Id>();
        for(RecordTypeInfo rtInfo: rtMapByName.values()){
            rtIds.add(rtInfo.getRecordTypeId());
        }

        Map<Id, RecordType> recTypeMap = new Map<Id, RecordType> ([Select Id, DeveloperName from RecordType 
                                                                    where Id in: rtIds]);

        Map<String, RecordTypeInfo> rtMapByDevName = new Map<String, RecordTypeInfo> ();
        System.debug('rtMapByName = ' + rtMapByName);
        System.debug('recTypeMap = ' + recTypeMap);

        for(RecordTypeInfo rtInfo: rtMapByName.values()){
            System.debug('rtInfo = ' + rtInfo);
            if(rtInfo.getRecordTypeId()!=null && recTypeMap.get(rtInfo.getRecordTypeId())!=null){
                rtMapByDevName.put(recTypeMap.get(rtInfo.getRecordTypeId()).DeveloperName,
                                                    rtInfo);
            }
        }

        return rtMapByDevName;

    }   
    

}