BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Cycle_Plan_Target_vod__c.object
<CustomObject>
    <description>The Cycle Plan Target is an Account that is included in a Cycle Plan.</description>
    <fields>
        <fullName>Cycle_Plan_Account_vod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account that is a target for this Cycle Plan.</description>
        <label>Target</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cycle Plan Targets</relationshipLabel>
        <relationshipName>Cycle_Plan_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cycle_Plan_vod__c</fullName>
        <description>The Cycle Plan of which this account is part of.</description>
        <label>Cycle Plan</label>
        <referenceTo>Cycle_Plan_vod__c</referenceTo>
        <relationshipLabel>Cycle Plan Targets</relationshipLabel>
        <relationshipName>Cycle_Plan_Targets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Cycle Plan Target</label>
    <nameField>
        <displayFormat>CPT-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cycle Plan Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Cycle_Plan_vod__c.object
<CustomObject>
    <description>The Cycle Plan object holds a list of target accounts for a specified time frame.</description>
    <fields>
        <fullName>Active_vod__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, the Cycle Plan is considered Active.  There should be only one active Cycle Plan per user in a territory.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BU_BMS_CN__c</fullName>
        <label>BU</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date_vod__c</fullName>
        <description>The last day the Cycle Plan is in effect.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Owner_Sales_BMS_CN__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether the owner of Cycle Plan is Sales Rep or not. This field should be initialized every monthly  loaded Cycle Plan Data.</description>
        <label>Is Owner Sales?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date_vod__c</fullName>
        <description>The first day the Cycle Plan is in effect.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Territory_vod__c</fullName>
        <description>the territory of the Cycle Plan</description>
        <label>Territory</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Cycle Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cycle Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EMSIM-AllTriggers&Apex/src/classes/BMS_CN_Cycle_Plan_Clone_Medical.cls
global with sharing class BMS_CN_Cycle_Plan_Clone_Medical implements Database.Batchable<sObject>, Database.Stateful
{
	//Author:           Nate Zhang
    //Create Date:      2013.04.17 - Create
    //Last Update Date: 2013.04.17   
    //---------------------------------
    
    final Date startDate = Date.today().addMonths(-1).toStartOfMonth();
	final Date endDate = Date.today().toStartOfMonth().addDays(-1);
	String query;
    global Database.QueryLocator start(Database.BatchableContext BC) 
    { 
    	//Get medical plan of last month for deep cloning targets
    	query = 'SELECT Id, ' +
                '       Active_vod__c, ' +
                '       Start_Date_vod__c, '	  +
                ' 		End_Date_vod__c, ' +
                '		Territory_vod__c,' +
                '       BU_BMS_CN__c,'	   +
                '       Owner.Name '	  +
                ' FROM  Cycle_Plan_vod__c ' +
                ' WHERE Start_Date_vod__c = :startDate  '+
                ' AND   End_Date_vod__c = :endDate  ' +
                ' AND   Is_Owner_Sales_BMS_CN__c != true ' +
                ' AND   Owner.IsActive = true ' +
                ' ORDER By Territory_vod__c' ;  
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> batch) 
    { 
    	Date sDate = Date.today().toStartOfMonth();
		Date eDate = Date.today().addMonths(1).toStartOfMonth().addDays(-1);
    	for (sObject obj : batch) 
        {
        	Cycle_Plan_vod__c cp = (Cycle_Plan_vod__c)obj;
        	
        	List<Cycle_Plan_Target_vod__c> cpts = [SELECT 	  Cycle_Plan_Account_vod__c
        												FROM  Cycle_Plan_Target_vod__c
        												where Cycle_Plan_vod__c =:cp.Id
        												order by Cycle_Plan_Account_vod__c];
        												
        	Cycle_Plan_vod__c master = new Cycle_Plan_vod__c(Active_vod__c = true, 
        													 Start_Date_vod__c = sDate,
        													 End_Date_vod__c = eDate,
        													 Territory_vod__c = cp.Territory_vod__c,
        													 BU_BMS_CN__c = cp.BU_BMS_CN__c,
        													 OwnerId = cp.OwnerId,
        													 Name = '[Medical]-'+cp.Territory_vod__c + '-'+cp.Owner.Name+'-'+sDate.year()+'-'+sDate.month());
        	
        	cp.Active_vod__c = false;
        	update cp;
        													 
        	//must update cp first to Deactive the old cycle plan then insert new active cyplan plan
        	insert master;			
        										 
        	List<Cycle_Plan_Target_vod__c> cloned = new List<Cycle_Plan_Target_vod__c>();
        	for(Cycle_Plan_Target_vod__c cpt:cpts)
        	{
        		if(cpt.Cycle_Plan_Account_vod__c != null)
        			cloned.Add(new Cycle_Plan_Target_vod__c(Cycle_Plan_Account_vod__c = cpt.Cycle_Plan_Account_vod__c,
        												 Cycle_Plan_vod__c = master.id));
        	}
        	
        	if(cloned.size()>0)
        		insert cloned;
        	System.Debug('[Nate]: cloned:' + cloned);
        	
        }
    	
    }
    
    global void finish(Database.BatchableContext BC) 
    {
    	
    }

}