BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/KPI_Rep_Activity_BMS_CN__c.object
<CustomObject>
    <fields>
        <fullName>Daily_Calls_Inv_BMS_CN__c</fullName>
        <defaultValue>0.0</defaultValue>
        <label>Daily Calls(Inv)</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MTD_Calls_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MTD Calls</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MTD_Calls_Day_BMS_CN__c</fullName>
        <defaultValue>0.0</defaultValue>
        <label>MTD Calls/Day</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TOT_BMS_CN__c</fullName>
        <defaultValue>0.0</defaultValue>
        <label>TOT</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Working_Days_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Target Working Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>KPI Rep Activity Summary</label>
    <nameField>
        <displayFormat>KPA-{0000}</displayFormat>
        <label>KPI Rep Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI Rep Activity Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/KPI_Rep_Call_BMS_CN__c.object
<CustomObject>
    <fields>
        <fullName>Act_Call_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Act Call</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Freq_BMS_CN__c</fullName>
        <defaultValue>0.0</defaultValue>
        <label>Call Freq</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Doctors_Visited_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Doctors Visited</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dr_Coverage_BMS_CN__c</fullName>
        <formula>if(Total_Dr_Num_BMS_CN__c&gt;0,  Doctors_Visited_BMS_CN__c  /  Total_Dr_Num_BMS_CN__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dr Coverage %</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Dr_Level_BMS_CN__c</fullName>
        <label>Dr Level</label>
        <length>300</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Total_Dr_Num_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Dr Num.</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>KPI Rep Call Summary</label>
    <nameField>
        <displayFormat>KRC-{0000}</displayFormat>
        <label>KRC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI Rep Call Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/KPI_Rep_Calls_by_Level_BMS_CN__c.object
<CustomObject>
    <fields>
        <fullName>Account_BMS_CN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>KPI Rep Calls by Level</relationshipLabel>
        <relationshipName>KPI_Rep_Calls_by_Level</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Act_Calls_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Act Calls</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dr_Level_BMS_CN__c</fullName>
        <label>Dr Level</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hsp_Name_BMS_CN__c</fullName>
        <formula>Account_BMS_CN__r.Primary_Parent_vod__r.Primary_Parent_vod__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hsp Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Need_to_Call_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Need to Call</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>KPI Rep Calls by Level</label>
    <nameField>
        <displayFormat>KRCL-{0000}</displayFormat>
        <label>KPI Rep Calls by Level Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI Rep Calls by Level</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/classes/BMS_KPI_REP_VF_CNTRL.cls
/*
Controller Extension to facilitate PSR KPI REPORT GUI

Summary: 
Controller will query the current active PSR KPI REPORT
*/

public with sharing class BMS_KPI_REP_VF_CNTRL {
    //Object in view

    UserTerritory currUT = new UserTerritory();
    Territory currTerri = new Territory();        
    List<KPI_Rep_Activity_BMS_CN__c> repActivities = new List<KPI_Rep_Activity_BMS_CN__c>();
    List<KPI_Rep_Call_BMS_CN__c>  repCalls = new List<KPI_Rep_Call_BMS_CN__c>();
    List<KPI_Rep_Calls_by_Level_BMS_CN__c> repCallLevel = new List<KPI_Rep_Calls_by_Level_BMS_CN__c>();    
      
    public BMS_KPI_REP_VF_CNTRL() {
        //Query all related information
        ID owner = ApexPages.currentPage().getParameters().get('id');
        if(owner != null) { 
             currUT = [select TerritoryId, UserId from UserTerritory where UserId = :owner limit 1];  
             currTerri = [select Name,id, ParentTerritoryId from Territory where Id = : currUT.TerritoryId];
         }  
    }        
    
    public KPI_Rep_Activity_BMS_CN__c getRepActivity(){
        //Return object and related info
        repActivities = [SELECT Id, 
                    Daily_Calls_Inv_BMS_CN__c, 
                    MTD_Calls_BMS_CN__c, 
                    TOT_BMS_CN__c, 
                    Target_Working_Days_BMS_CN__c, 
                    MTD_Calls_Day_BMS_CN__c 
                    FROM KPI_Rep_Activity_BMS_CN__c 
                    limit 1];
/*
        if(repActivities.size() <= 0){
            KPI_Rep_Activity_BMS_CN__c repActivity = new KPI_Rep_Activity_BMS_CN__c();
            repActivity.Territory__c = 'None';
            repActivities.add(repActivity);
        }
*/       
        return repActivities[0];
    }   

    public List<KPI_Rep_Call_BMS_CN__c> getRepCall(){
        //Return object and related info       
        repCalls = [SELECT id,
                     Act_Call_BMS_CN__c, 
                     Call_Freq_BMS_CN__c, 
                     Doctors_Visited_BMS_CN__c, 
                     Dr_Coverage_BMS_CN__c, 
                     Dr_Level_BMS_CN__c, 
                     Total_Dr_Num_BMS_CN__c 
                     FROM KPI_Rep_Call_BMS_CN__c
                     ];
        return repCalls;
    }   
/*
    public List <KPI_Rep_Calls_by_Level_BMS_CN__c> getRepCallLevel(){
        //Return object and related info       
        repCallLevel = [SELECT Account_BMS_CN__c, 
                     Act_Calls_BMS_CN__c, 
                     Dr_Level_BMS_CN__c, 
                     Hsp_Name_BMS_CN__c, 
                     KPI_Rep_Call_Summary__c,  
                     Need_to_Call_BMS_CN__c, 
                     Id, 
                     KPI_Rep_Call_BMS_CN__r.Act_Call_BMS_CN__c, 
                     KPI_Rep_Call_BMS_CN__r.Call_Freq_BMS_CN__c, 
                     KPI_Rep_Call_BMS_CN__r.Doctors_Visited_BMS_CN__c, 
                     KPI_Rep_Call_BMS_CN__r.Dr_Coverage_BMS_CN__c, 
                     KPI_Rep_Call_BMS_CN__r.Dr_Level_BMS_CN__c, 
                     KPI_Rep_Call_BMS_CN__r.Total_Dr_Num_BMS_CN__c 
                     FROM KPI_Rep_Calls_by_Level_BMS_CN__c
                     ];
        return repCallLevel;
    }   
*/
}