BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Master_File_BMS_EMEA__c.object
<CustomObject>
    <description>VPRO Oct 2013: Object part of the Field Force Meeting module for BMS EMEA. Master Files created by Marketing Leads will be stored here and then shared with Reps or MSM.</description>
    <fields>
        <fullName>End_Date_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: End Date (month) of the Master File.</description>
        <label>End Month</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Meeting_August_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meeting August</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_Dec_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meeting December</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_July_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meeting Jul</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_June_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meeting Jun</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_May_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meeting May</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_November_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meeting Nov</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_October_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meeting Oct</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_September_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meeting Sep</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meetings_April_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meetings Apr</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meetings_February_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meetings Feb</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meetings_January_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meetings Jan</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meetings_March_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: field to store the distributed number of Targeted Meetings per month.</description>
        <label>Meetings Mar</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Objective_Total_BMS_EMEA__c</fullName>
        <label>Objective Total</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Apr_Completed_BMS_EMEA__c</fullName>
        <label>RollUp_Apr_Completed</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Apr_Planned_BMS_EMEA__c</fullName>
        <label>RollUp_Apr_Planned</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Aug_Completed_BMS_EMEA__c</fullName>
        <label>RollUp_Aug_Completed</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Aug_Planned_BMS_EMEA__c</fullName>
        <label>RollUp_Aug_Planned</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Dec_Completed_BMS_EMEA__c</fullName>
        <label>RollUp_Dec_Completed</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Dec_Planned_BMS_EMEA__c</fullName>
        <label>RollUp_Dec_Planned</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Feb_Completed_BMS_EMEA__c</fullName>
        <label>RollUp_Feb_Completed</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Feb_Planned_BMS_EMEA__c</fullName>
        <label>RollUp_Feb_Planned</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Jan_Completed_BMS_EMEA__c</fullName>
        <label>RollUp_Jan_Completed</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Jan_Planned_BMS_EMEA__c</fullName>
        <label>RollUp_Jan_Planned</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Jul_Completed_BMS_EMEA__c</fullName>
        <label>RollUp_Jul_Completed</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Jul_Planned_BMS_EMEA__c</fullName>
        <label>RollUp_Jul_Planned</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Jun_Completed_BMS_EMEA__c</fullName>
        <label>RollUp_Jun_Completed</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Jun_Planned_BMS_EMEA__c</fullName>
        <label>RollUp_Jun_Planned</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Mar_Completed_BMS_EMEA__c</fullName>
        <label>RollUp_Mar_Completed</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Mar_Planned_BMS_EMEA__c</fullName>
        <label>RollUp_Mar_Planned</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_May_Completed_BMS_EMEA__c</fullName>
        <label>RollUp_May_Completed</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_May_Planned_BMS_EMEA__c</fullName>
        <label>RollUp_May_Planned</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Nov_Completed_BMS_EMEA__c</fullName>
        <label>RollUp_Nov_Completed</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Nov_Planned_BMS_EMEA__c</fullName>
        <label>RollUp_Nov_Planned</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Oct_Completed_BMS_EMEA__c</fullName>
        <label>RollUp_Oct_Completed</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Oct_Planned_BMS_EMEA__c</fullName>
        <label>RollUp_Oct_Planned</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Sep_Completed_BMS_EMEA__c</fullName>
        <label>RollUp_Sep_Completed</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RollUp_Sep_Planned_BMS_EMEA__c</fullName>
        <label>RollUp_Sep_Planned</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: Start Date (month) of the Master File.</description>
        <label>Start Month</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Targeted_number_of_Meetings_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: Number field used in many formulas.</description>
        <label>Targeted number of Meetings</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Actual_Cost_BMS_EMEA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Actual Costs</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Planned_Cost_BMS_EMEA__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Planned Costs</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Audience_Participants_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: roll-up summary field from the Master File Participants where the type is Audience.</description>
        <label># of Audience Participants</label>
        <summarizedField>Master_File_Participant_BMS_EMEA__c.Number_per_Meeting_BMS_EMEA__c</summarizedField>
        <summaryFilterItems>
            <field>Master_File_Participant_BMS_EMEA__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>BMS - EMEA - Audience</value>
        </summaryFilterItems>
        <summaryForeignKey>Master_File_Participant_BMS_EMEA__c.Master_File_BMS_EMEA__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>of_BMS_Employees_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: roll-up summary field from the Master File Participants where the type is BMS Employee.</description>
        <label># of BMS Employees</label>
        <summarizedField>Master_File_Participant_BMS_EMEA__c.Number_per_Meeting_BMS_EMEA__c</summarizedField>
        <summaryFilterItems>
            <field>Master_File_Participant_BMS_EMEA__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>BMS - EMEA - BMS Employee</value>
        </summaryFilterItems>
        <summaryForeignKey>Master_File_Participant_BMS_EMEA__c.Master_File_BMS_EMEA__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>of_Sponsored_Participants_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: roll-up summary field from the Master File Participants where the type is Sponsored.</description>
        <label># of Sponsored Participants</label>
        <summarizedField>Master_File_Participant_BMS_EMEA__c.Number_per_Meeting_BMS_EMEA__c</summarizedField>
        <summaryFilterItems>
            <field>Master_File_Participant_BMS_EMEA__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>BMS - EMEA - Sponsored</value>
        </summaryFilterItems>
        <summaryForeignKey>Master_File_Participant_BMS_EMEA__c.Master_File_BMS_EMEA__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Master File</label>
    <nameField>
        <displayFormat>MF-{00000}</displayFormat>
        <label>Master File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Files</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/classes/PhasingDistribution_BMS_EMEA.cls
public with sharing class PhasingDistribution_BMS_EMEA {
    
    public Id MasterFileID{get; set;}
    public List<Master_File_BMS_EMEA__c> MasterFile{get; set;}    
    public Decimal NoOfDays = 0;
    public String currentId{get;set;}  
                 
    public PhasingDistribution_BMS_EMEA(ApexPages.StandardController controller) {   
      
        currentId = '';
        this.MasterFileID= ((Master_File_BMS_EMEA__c)controller.getRecord()).Id;
        MasterFile = new List<Master_File_BMS_EMEA__c>();

        //Get details about this master file
        MasterFile = [SELECT  Id,Total_Planned_Cost_BMS_EMEA__c,Total_Actual_Cost_BMS_EMEA__c ,RollUp_Jan_Planned_BMS_EMEA__c,RollUp_Feb_Planned_BMS_EMEA__c,RollUp_Mar_Planned_BMS_EMEA__c,RollUp_Apr_Planned_BMS_EMEA__c,RollUp_May_Planned_BMS_EMEA__c,RollUp_Jun_Planned_BMS_EMEA__c,RollUp_Jul_Planned_BMS_EMEA__c,RollUp_Aug_Planned_BMS_EMEA__c,RollUp_Sep_Planned_BMS_EMEA__c,RollUp_Oct_Planned_BMS_EMEA__c,RollUp_Nov_Planned_BMS_EMEA__c,RollUp_Dec_Planned_BMS_EMEA__c,
                                                RollUp_Apr_Completed_BMS_EMEA__c,RollUp_Aug_Completed_BMS_EMEA__c,RollUp_Dec_Completed_BMS_EMEA__c,RollUp_Feb_Completed_BMS_EMEA__c,RollUp_Jan_Completed_BMS_EMEA__c,RollUp_Jul_Completed_BMS_EMEA__c,RollUp_Jun_Completed_BMS_EMEA__c,RollUp_Mar_Completed_BMS_EMEA__c,RollUp_May_Completed_BMS_EMEA__c,RollUp_Nov_Completed_BMS_EMEA__c,RollUp_Oct_Completed_BMS_EMEA__c,RollUp_Sep_Completed_BMS_EMEA__c,
                                                of_Sponsored_Participants_BMS_EMEA__c,of_Audience_Participants_BMS_EMEA__c,of_BMS_Employees_BMS_EMEA__c,Targeted_number_of_Meetings_BMS_EMEA__c,Objective_Total_BMS_EMEA__c,End_Date_BMS_EMEA__c,Start_Date_BMS_EMEA__c,Meetings_January_BMS_EMEA__c,Meetings_February_BMS_EMEA__c,Meetings_March_BMS_EMEA__c,Meetings_April_BMS_EMEA__c,Meeting_May_BMS_EMEA__c,
                            Meeting_June_BMS_EMEA__c,Meeting_July_BMS_EMEA__c,Meeting_August_BMS_EMEA__c,Meeting_September_BMS_EMEA__c,Meeting_October_BMS_EMEA__c,Meeting_November_BMS_EMEA__c,Meeting_Dec_BMS_EMEA__c,Total_Budget_all_Events_BMS_EMEA__c,Total_number_of_Meeting_PostExc_BMS_EMEA__c,Total_number_of_Meeting_Plans_BMS_EMEA__c
                      FROM Master_File_BMS_EMEA__c
                      WHERE Id = :this.MasterFileID];    
              
    }
    //Cancel command link
    public void cancelBMS(){
                MasterFile = [SELECT  Id,Total_Planned_Cost_BMS_EMEA__c,Total_Actual_Cost_BMS_EMEA__c ,RollUp_Jan_Planned_BMS_EMEA__c,RollUp_Feb_Planned_BMS_EMEA__c,RollUp_Mar_Planned_BMS_EMEA__c,RollUp_Apr_Planned_BMS_EMEA__c,RollUp_May_Planned_BMS_EMEA__c,RollUp_Jun_Planned_BMS_EMEA__c,RollUp_Jul_Planned_BMS_EMEA__c,RollUp_Aug_Planned_BMS_EMEA__c,RollUp_Sep_Planned_BMS_EMEA__c,RollUp_Oct_Planned_BMS_EMEA__c,RollUp_Nov_Planned_BMS_EMEA__c,RollUp_Dec_Planned_BMS_EMEA__c,
                                        RollUp_Apr_Completed_BMS_EMEA__c,RollUp_Aug_Completed_BMS_EMEA__c,RollUp_Dec_Completed_BMS_EMEA__c,RollUp_Feb_Completed_BMS_EMEA__c,RollUp_Jan_Completed_BMS_EMEA__c,RollUp_Jul_Completed_BMS_EMEA__c,RollUp_Jun_Completed_BMS_EMEA__c,RollUp_Mar_Completed_BMS_EMEA__c,RollUp_May_Completed_BMS_EMEA__c,RollUp_Nov_Completed_BMS_EMEA__c,RollUp_Oct_Completed_BMS_EMEA__c,RollUp_Sep_Completed_BMS_EMEA__c,
                                        of_Sponsored_Participants_BMS_EMEA__c,of_Audience_Participants_BMS_EMEA__c,of_BMS_Employees_BMS_EMEA__c,Targeted_number_of_Meetings_BMS_EMEA__c,Objective_Total_BMS_EMEA__c,End_Date_BMS_EMEA__c,Start_Date_BMS_EMEA__c,Meetings_January_BMS_EMEA__c,Meetings_February_BMS_EMEA__c,Meetings_March_BMS_EMEA__c,Meetings_April_BMS_EMEA__c,Meeting_May_BMS_EMEA__c,
                            Meeting_June_BMS_EMEA__c,Meeting_July_BMS_EMEA__c,Meeting_August_BMS_EMEA__c,Meeting_September_BMS_EMEA__c,Meeting_October_BMS_EMEA__c,Meeting_November_BMS_EMEA__c,Meeting_Dec_BMS_EMEA__c,Total_Budget_all_Events_BMS_EMEA__c,Total_number_of_Meeting_PostExc_BMS_EMEA__c,Total_number_of_Meeting_Plans_BMS_EMEA__c
                      FROM Master_File_BMS_EMEA__c
                      WHERE Id = :this.MasterFileID];   
                      
            currentId = '';
    }
    
     //Save    
    public void SaveBMS() {
        MasterFile[0].Objective_Total_BMS_EMEA__c = 0;      
        MasterFile[0].Objective_Total_BMS_EMEA__c += (MasterFile[0].Meetings_January_BMS_EMEA__c == null)?0:MasterFile[0].Meetings_January_BMS_EMEA__c;
        MasterFile[0].Objective_Total_BMS_EMEA__c += (MasterFile[0].Meetings_February_BMS_EMEA__c == null)?0:MasterFile[0].Meetings_February_BMS_EMEA__c;
        MasterFile[0].Objective_Total_BMS_EMEA__c += (MasterFile[0].Meetings_March_BMS_EMEA__c == null)?0:MasterFile[0].Meetings_March_BMS_EMEA__c;
        MasterFile[0].Objective_Total_BMS_EMEA__c += (MasterFile[0].Meetings_April_BMS_EMEA__c == null)?0:MasterFile[0].Meetings_April_BMS_EMEA__c;
        MasterFile[0].Objective_Total_BMS_EMEA__c += (MasterFile[0].Meeting_May_BMS_EMEA__c == null)?0:MasterFile[0].Meeting_May_BMS_EMEA__c;
        MasterFile[0].Objective_Total_BMS_EMEA__c += (MasterFile[0].Meeting_June_BMS_EMEA__c == null)?0:MasterFile[0].Meeting_June_BMS_EMEA__c;
        MasterFile[0].Objective_Total_BMS_EMEA__c += (MasterFile[0].Meeting_July_BMS_EMEA__c == null)?0:MasterFile[0].Meeting_July_BMS_EMEA__c;
        MasterFile[0].Objective_Total_BMS_EMEA__c += (MasterFile[0].Meeting_August_BMS_EMEA__c == null)?0:MasterFile[0].Meeting_August_BMS_EMEA__c;
        MasterFile[0].Objective_Total_BMS_EMEA__c += (MasterFile[0].Meeting_September_BMS_EMEA__c == null)?0:MasterFile[0].Meeting_September_BMS_EMEA__c;
        MasterFile[0].Objective_Total_BMS_EMEA__c += (MasterFile[0].Meeting_October_BMS_EMEA__c == null)?0:MasterFile[0].Meeting_October_BMS_EMEA__c;
        MasterFile[0].Objective_Total_BMS_EMEA__c += (MasterFile[0].Meeting_November_BMS_EMEA__c == null)?0:MasterFile[0].Meeting_November_BMS_EMEA__c;
        MasterFile[0].Objective_Total_BMS_EMEA__c += (MasterFile[0].Meeting_Dec_BMS_EMEA__c == null)?0:MasterFile[0].Meeting_Dec_BMS_EMEA__c;
        
        if(MasterFile[0].Objective_Total_BMS_EMEA__c != MasterFile[0].Targeted_number_of_Meetings_BMS_EMEA__c){
            MasterFile[0].Objective_Total_BMS_EMEA__c = MasterFile[0].Targeted_number_of_Meetings_BMS_EMEA__c;
            MasterFile[0].addError('The Objective Total must be equal to ' + MasterFile[0].Targeted_number_of_Meetings_BMS_EMEA__c);
        }
        else{
            update MasterFile;
            currentId = '';
        }
    }  
    
    
    
}