BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Master_File_BMS_EMEA__c.object
<CustomObject>
    <description>VPRO Oct 2013: Object part of the Field Force Meeting module for BMS EMEA. Master Files created by Marketing Leads will be stored here and then shared with Reps or MSM.</description>
    <fields>
        <fullName>Activity_Type_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013. Type of expected Meeting. This field will drive the Meeting Format values too.</description>
        <label>Activity Type</label>
        <picklist>
            <controllingField>Country_BMS_EMEA__c</controllingField>
            <picklistValues>
                <fullName>Speaker Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P2P Discussion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Representative Presentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Representative Presentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship of local meetings (stand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship of Hospital meetings (stand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship of HCPs to local Congress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advisory Boards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DA Group Meetings with External Speaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DA MSM Presentation with MSM as Speaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Non Promotional Meetings in response to an expressed need</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other External Meetings in response to an expressed need</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country_BMS_EMEA__c</fullName>
        <description>VPRO Oct 2013: Country for the events.</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Czech Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denmark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greece</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hungary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ireland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Israel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Netherlands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portugal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Romania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Russia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sweden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Switzerland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turkey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United Kingdom</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FFM_Step_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field used to match the Master File record with the Document Template object (to expose the required fields)</description>
        <label>FFM Step</label>
        <picklist>
            <picklistValues>
                <fullName>Master File</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Master File</label>
    <nameField>
        <displayFormat>MF-{00000}</displayFormat>
        <label>Master File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Files</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/zEUFULL-PRODMigration-MetadataWithPermsXLation/src/objects/Medical_Event_vod__c.object
<CustomObject>
    <description>This object is used to store medical events. It is not related to the base salesforce.com event (calendar event) object. It has one standard child (event attendees), but custom objects can be added as children to track different attributes of medical events. Medical Event is a top level object with its own security and is referred to in the interaction reporting functionality.</description>
    <fields>
        <fullName>Activity_Type_BMS_EMEA__c</fullName>
        <description>VPRO - October 2013 - BMS EMEA Core Requirements &amp; Design: Custom field to capture the Activity Type of a meeting.  This field was created in relation to H20 meetings module for EMEA.</description>
        <label>Activity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Advisory Boards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DA Group Meetings with External Speaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DA MSM Presentation with MSM as Speaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Promotional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Promotional Stand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Serial - Advisory Boards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Serial - Disease Area Group Meetings with External Speaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Serial - Disease Area MSM presentation with MSM as Speaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Serial - Non Promotional Stand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Serial - Other Presentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Serial - Speaker Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Serial - Sponsorship of local HCP to a national/international congress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non serial - Sponsorship of local meeting (Symposium)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Serial - Sponsorship of national or international meeting (symposium)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Non Promotional Meetings in response to an expressed need</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Representative Presentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P2P Discussion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serial - Disease Area Group Meetings with External Speaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serial - Disease Area MSM presentation with MSM as Speaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serial - Other Presentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serial - Speaker Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speaker Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship of Hospital meetings (stand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship of local meetings (stand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRP - Opportunity Meetings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRP - Staff Meetings</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FFM_Step_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field used to match the Master File record with the Document Template object (to expose the required fields)</description>
        <label>FFM Step</label>
        <picklist>
            <picklistValues>
                <fullName>Meeting Planning</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Post-Execution</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Master_File_BMS_EMEA__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>TT 30/10/2013: any Meeting created by Reps must be related to a Master File.</description>
        <label>Master File</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Master File cannot be of type Standard Rep Presentation. You need to create an interaction instead to record Standard Rep Presentations.</errorMessage>
            <filterItems>
                <field>Master_File_BMS_EMEA__c.Activity_Type_BMS_EMEA__c</field>
                <operation>notEqual</operation>
                <value>Standard Representative Presentation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Master_File_BMS_EMEA__c</referenceTo>
        <relationshipLabel>Meetings</relationshipLabel>
        <relationshipName>Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <recordTypes>
        <fullName>Master</fullName>
        <active>true</active>
        <description>Default Record Type with Medical Event page layout assigned</description>
        <label>Master</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Meeting_Document_Template__c.object
<CustomObject>
    <description>Template for documents required for Meetings</description>
    <fields>
        <fullName>Activity_Type_BMS_EMEA__c</fullName>
        <label>Activity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Speaker Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P2P Discussion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Representative Presentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Representative Presentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship of local meetings (stand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship of Hospital meetings (stand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship of HCPs to local Congress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advisory Boards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DA Group Meetings with External Speaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DA MSM Presentation with MSM as Speaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Non Promotional Meetings in response to an expressed need</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other External Meetings in response to an expressed need</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FFM_Step_BMS_EMEA__c</fullName>
        <description>VPRO Nov 2013: field used to have different required fields based on the FFM Step</description>
        <label>FFM Step</label>
        <picklist>
            <picklistValues>
                <fullName>Master File</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Post-Execution</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Required__c</fullName>
        <defaultValue>true</defaultValue>
        <description>True if the document is required when closing out the meeting</description>
        <label>Is Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Meeting_Type__c</fullName>
        <label>Meeting Type</label>
        <picklist>
            <picklistValues>
                <fullName>Corporate Support Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OLA Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lunch and Learn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accredited</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Meeting Document Template</label>
    <nameField>
        <label>Meeting Document Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Document Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/classes/AttachmentValidationLogic_BMS_EMEA.cls
public class AttachmentValidationLogic_BMS_EMEA{

    /******************************************************Master File Attachment validation**********************************************************************************/
    public static map<Id, boolean> validationlogic(List<Master_File_BMS_EMEA__c> mfileLst){
        set<string> country = new set<string>();
        set<string> activity = new set<string>();
        set<string> ffmstep = new set<string>();
        set<Id> mfIds = new set<Id>();
        for(Master_File_BMS_EMEA__c mf:mfileLst){
           country.add(mf.Country_BMS_EMEA__c);
           activity.add(mf.Activity_Type_BMS_EMEA__c);
           ffmstep.add(mf.FFM_Step_BMS_EMEA__c);
           mfIds.add(mf.Id);
        }
        
        List<Meeting_Document_Template__c> mdtList = [SELECT Id,Meeting_Type__c,Name, Is_Required__c,Activity_Type_BMS_EMEA__c,FFM_Step_BMS_EMEA__c,Country_Specific_BMS_EMEA__c 
                                                               FROM Meeting_Document_Template__c
                                                               WHERE Is_Required__c=: true and Country_Specific_BMS_EMEA__c in:country and Activity_Type_BMS_EMEA__c in:activity and FFM_Step_BMS_EMEA__c in:ffmstep];
        
        map<Id, List<Attachment>> mapAttach = new map<Id, List<Attachment>>();
        for(Master_File_BMS_EMEA__c mf:[select Id, (select Description from Attachments) from Master_File_BMS_EMEA__c where Id in:mfIds]){
            mapAttach.put(mf.Id, mf.Attachments);
        }
        
        map<Id, boolean> mapValidation = new map<Id, boolean>();
        map<string, Attachment> mapAttachList = new map<string, Attachment>();
        
        for(Master_File_BMS_EMEA__c mf:mfileLst){
            mapValidation.put(mf.Id, true);
            mapAttachList = new map<string, Attachment>();
            if(mapAttach.get(mf.Id) != null){
            for(Attachment att:mapAttach.get(mf.Id)){
                mapAttachList.put(att.Description, att);
            }
            }
            
            for(Meeting_Document_Template__c mdt: mdtList){
                if(mapAttachList.get(mdt.Name) == null && mf.FFM_Step_BMS_EMEA__c == mdt.FFM_Step_BMS_EMEA__c && mf.Activity_Type_BMS_EMEA__c == mdt.Activity_Type_BMS_EMEA__c && mdt.Country_Specific_BMS_EMEA__c == mf.Country_BMS_EMEA__c){
                    mapValidation.put(mf.Id, false);
                    break;
                }
            }            
        
        }
        
        return mapValidation;
    }
    
    
    /******************************************************Meeting Attachment validation**********************************************************************************/
    public static map<Id, boolean> meetvalidationlogic(List<Medical_Event_vod__c> medevtLst){
        set<string> evtType = new set<string>();
        set<Id> mdIds = new set<Id>();
        
        //3 fields Update for meetings
        set<string> country = new set<string>();
        set<string> activity = new set<string>();
        set<string> ffmstep = new set<string>();
        
                 
        for(Medical_Event_vod__c me:medevtLst){
           evtType.add(me.Event_Type__c);
           //3 fields Update for meetings
           country.add(me.Country_MasterFile_BMS_EMEA__c);
           activity.add(me.FFM_Activity_Type_BMS_EMEA__c);
           ffmstep.add(me.FFM_Step_BMS_EMEA__c);
           mdIds.add(me.Id);
        }
        
        system.debug('---country ---'+country);
        system.debug('---activity ---'+activity);
        system.debug('---ffmstep ---'+ffmstep);
        
        List<Meeting_Document_Template__c> mdtList = [SELECT Id,Meeting_Type__c,Name, Is_Required__c,Activity_Type_BMS_EMEA__c,FFM_Step_BMS_EMEA__c,Country_Specific_BMS_EMEA__c 
                                                               FROM Meeting_Document_Template__c
                                                               WHERE Is_Required__c=: true and Country_Specific_BMS_EMEA__c in:country and Activity_Type_BMS_EMEA__c in:activity and FFM_Step_BMS_EMEA__c in:ffmstep];
        
        map<Id, List<Attachment>> mapAttach = new map<Id, List<Attachment>>();
        for(Medical_Event_vod__c me:[select Id, (select Description from Attachments) from Medical_Event_vod__c where Id in:mdIds]){
            mapAttach.put(me.Id, me.Attachments);
        }
        
        map<Id, boolean> mapValidation = new map<Id, boolean>();
        map<string, Attachment> mapAttachList = new map<string, Attachment>();
        
        for(Medical_Event_vod__c me:medevtLst){
            mapValidation.put(me.Id, true);
            mapAttachList = new map<string, Attachment>();
            if(mapAttach.get(me.Id) != null){
            for(Attachment att:mapAttach.get(me.Id)){
                mapAttachList.put(att.Description, att);
            }
            }
            
            for(Meeting_Document_Template__c mdt: mdtList){
             
             system.debug('---- mapAttachList.get(mdt.Name) ----'+mapAttachList.get(mdt.Name));
             
             system.debug('---- meeting  ----'+me);
             
             system.debug('---- attachment ---'+mdt);
             
             /* updated for meeting validation required'  */
             if(mapAttachList.get(mdt.Name) == null && me.FFM_Activity_Type_BMS_EMEA__c == mdt.Activity_Type_BMS_EMEA__c 
                                                && mdt.FFM_Step_BMS_EMEA__c == me.FFM_Step_BMS_EMEA__c 
                                                && mdt.Country_Specific_BMS_EMEA__c == me.Country_MasterFile_BMS_EMEA__c){
                    
                    mapValidation.put(me.Id, false);
                    break;
                }   
               
             
         //       if(mapAttachList.get(mdt.Name) == null && me.Event_Type__c == mdt.Meeting_Type__c){
        //            mapValidation.put(me.Id, false);
           
        //        }
            }            
        
        }
        
        system.debug('--- mapValidation ---'+mapValidation);
        return mapValidation;
    }

}