BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Meeting_Speaker_BMS__c.object
<CustomObject>
    <fields>
        <fullName>Meeting__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Meeting</label>
        <referenceTo>Medical_Event_vod__c</referenceTo>
        <relationshipLabel>Meeting Speakers</relationshipLabel>
        <relationshipName>Meeting_Speakers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Meeting Speaker</label>
    <nameField>
        <displayFormat>MS-{0000}</displayFormat>
        <label>Meeting Speaker BMS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EMSIM-AllTriggers&Apex/src/classes/EventManagementWebservice_BMS.cls
global class EventManagementWebservice_BMS{ 
   webService static Boolean allSpeakersApproved(String medicalEventId) {
        Boolean allApproved = true;
        List<Meeting_Speaker_BMS__c> meetingSpeakers = new List<Meeting_Speaker_BMS__c>();
        List<String> speakerIds = new List<String>();
        for (Meeting_Speaker_BMS__c ms : [SELECT ID FROM Meeting_Speaker_BMS__c
                                          WHERE Meeting__c = :medicalEventId]) {
            speakerIds.add(ms.Id);                        
        } 
        
        for (ProcessInstance pi : [SELECT Status 
                                   FROM ProcessInstance 
                                   WHERE TargetObjectId IN :speakerIds]) {
            if (pi.Status != 'Approved') {
                allApproved = false;
                break;
            }
        }                                     
        
        return allApproved;
   }
}