BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/objects/Patient_Tracker_BMS_CN__c.object
<CustomObject>
    <description>Patient Tracker</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patient Tracker</relationshipLabel>
        <relationshipName>Patient_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Baraclude_ETV_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Baraclude patient share among total ETV (%)</description>
        <label>Baraclude patient share among total ETV</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cycle_Period_BMS_CN__c</fullName>
        <description>Cycle Period</description>
        <label>Cycle Period</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ETV_ARV_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <description>ETV patient share among total ARV (%)</description>
        <label>ETV patient share among total ARV</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Lamivudine_ARV_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Lamivudine patient share among total ARV (%)</description>
        <label>Lamivudine patient share among total ARV</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Paraplatin_Actual_LC_Patients_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of Paraplatin Actual LC patients</description>
        <label>Num of Actual Lung Cancer patients</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Paraplatin_Actual_OC_Patients_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of Paraplatin Actual OC patients</description>
        <label>Num of Actual Ovarian Cancer patients</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Paraplatin_Actual_Other_Patients_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Num of Paraplatin Actual Other patients</description>
        <label>Num of Actual Other patients</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Paraplatin_Planned_LC_Patients_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of Paraplatin Planned LC patients</description>
        <label>Num of Planned Lung Cancer patients</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Paraplatin_Planned_OC_Patients_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of Paraplatin Planned OC patients</description>
        <label>Num of Planned Ovarian Cancer patients</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Paraplatin_Planned_Other_Patients_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Num of Paraplatin Planned Other patients</description>
        <label>Num of Planned Other patients</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Taxol_Actual_BC_Patients_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of Taxol Actual BC patients</description>
        <label>Num of Actual Breast Cancer patients</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Taxol_Actual_LC_Patients_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of Taxol Actual LC patients</description>
        <label>Num of Actual Lung Cancer patients</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Taxol_Actual_OC_Patients_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of Taxol Actual OC patients</description>
        <label>Num of Actual Ovarian Cancer patients</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Taxol_Actual_Other_Patients_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of Taxol Actual Other patients</description>
        <label>Num of Actual Other patients</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Taxol_Planned_BC_Patients_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of Taxol Planned BC patients</description>
        <label>Num of Planned Breast Cancer patients</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Taxol_Planned_LC_Patients_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of Taxol Planned LC patients</description>
        <label>Num of Planned Lung Cancer patients</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Taxol_Planned_OC_Patients_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of Taxol Planned OC patients</description>
        <label>Num of Planned Ovarian Cancer patients</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Taxol_Planned_Other_Patients_BMS_CN__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of Taxol Planned Other patients</description>
        <label>Num of Planned Other patients</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Patient Tracker</label>
    <nameField>
        <displayFormat>PT-{0000000000}</displayFormat>
        <label>Patient Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BMSSimplificationEclipseWS/EUFULL-Org-Backup/src/classes/BMS_CN_Create_Patient_Tracker.cls
/*
* Name: BMS_CN_Create_Patient_Tracker
* Description: Monthly create patient tracker for HCP
* Author: Roy Zhang
* Created Date: 06/19/2013
* Last Modified Date: 06/19/2013
*/
global class BMS_CN_Create_Patient_Tracker implements Database.Batchable<sObject>{
	global String strQuery;
	global String strPeriod;
	
	global BMS_CN_Create_Patient_Tracker() {
		strPeriod = getPeriod(-1);
		strQuery = 'SELECT'
					+ '     Id,'
					+ '     Cycle_Period_BMS_CN__c ,'
					+ '     Account__c,'
					+ '     Baraclude_ETV_BMS_CN__c,'
					+ '     ETV_ARV_BMS_CN__c,'
					+ '     Lamivudine_ARV_BMS_CN__c,'
					+ '     Taxol_Actual_BC_Patients_BMS_CN__c,'
					+ '     Taxol_Actual_LC_Patients_BMS_CN__c,'
					+ '     Taxol_Actual_OC_Patients_BMS_CN__c,'
					+ '     Taxol_Actual_Other_Patients_BMS_CN__c,'
					+ '     Taxol_Planned_BC_Patients_BMS_CN__c,'
					+ '     Taxol_Planned_LC_Patients_BMS_CN__c,'
					+ '     Taxol_Planned_OC_Patients_BMS_CN__c,'
					+ '     Taxol_Planned_Other_Patients_BMS_CN__c,'
					+ '     Paraplatin_Actual_Other_Patients_BMS_CN__c,'
					+ '     Paraplatin_Planned_Other_Patients_BMS_CN__c,'
					+ '     Paraplatin_Actual_LC_Patients_BMS_CN__c,'
					+ '     Paraplatin_Actual_OC_Patients_BMS_CN__c,'
					+ '     Paraplatin_Planned_LC_Patients_BMS_CN__c,'
					+ '     Paraplatin_Planned_OC_Patients_BMS_CN__c'					
					+ ' FROM'
					+ '     Patient_Tracker_BMS_CN__c'
					+ ' WHERE'
					+ '     Cycle_Period_BMS_CN__c = \'' + strPeriod + '\'';
					
	}
	global Database.Querylocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(strQuery);
	}
	
	global void execute(Database.BatchableContext BC, List<sObject> scope){
		List<Patient_Tracker_BMS_CN__c> ptList = scope;
		String newPeriod = getPeriod(0);
		
		List<Patient_Tracker_BMS_CN__c> newPTList = new List<Patient_Tracker_BMS_CN__c>();
		
		for(Patient_Tracker_BMS_CN__c pt : ptList){
			Patient_Tracker_BMS_CN__c ptNew = new Patient_Tracker_BMS_CN__c();
			ptNew.Cycle_Period_BMS_CN__c = newPeriod;
			ptNew.Account__c = pt.Account__c;
			ptNew.Baraclude_ETV_BMS_CN__c = pt.Baraclude_ETV_BMS_CN__c;
			ptNew.ETV_ARV_BMS_CN__c = pt.ETV_ARV_BMS_CN__c;
			ptNew.Lamivudine_ARV_BMS_CN__c = pt.Lamivudine_ARV_BMS_CN__c;
			ptNew.Paraplatin_Actual_LC_Patients_BMS_CN__c = pt.Paraplatin_Actual_LC_Patients_BMS_CN__c;
			ptNew.Paraplatin_Actual_OC_Patients_BMS_CN__c = pt.Paraplatin_Actual_OC_Patients_BMS_CN__c;
			ptNew.Paraplatin_Planned_LC_Patients_BMS_CN__c = pt.Paraplatin_Planned_LC_Patients_BMS_CN__c;
			ptNew.Paraplatin_Planned_OC_Patients_BMS_CN__c = pt.Paraplatin_Planned_OC_Patients_BMS_CN__c;
			ptNew.Taxol_Actual_BC_Patients_BMS_CN__c = pt.Taxol_Actual_BC_Patients_BMS_CN__c;
			ptNew.Taxol_Actual_LC_Patients_BMS_CN__c = pt.Taxol_Actual_LC_Patients_BMS_CN__c;
			ptNew.Taxol_Actual_OC_Patients_BMS_CN__c = pt.Taxol_Actual_OC_Patients_BMS_CN__c;
			ptNew.Taxol_Actual_Other_Patients_BMS_CN__c = pt.Taxol_Actual_Other_Patients_BMS_CN__c;
			ptNew.Taxol_Planned_BC_Patients_BMS_CN__c = pt.Taxol_Planned_BC_Patients_BMS_CN__c;
			ptNew.Taxol_Planned_LC_Patients_BMS_CN__c = pt.Taxol_Planned_LC_Patients_BMS_CN__c;
			ptNew.Taxol_Planned_OC_Patients_BMS_CN__c = pt.Taxol_Planned_OC_Patients_BMS_CN__c;
			ptNew.Taxol_Planned_Other_Patients_BMS_CN__c = pt.Taxol_Planned_Other_Patients_BMS_CN__c;
			ptNew.Paraplatin_Actual_Other_Patients_BMS_CN__c = pt.Paraplatin_Actual_Other_Patients_BMS_CN__c;
			ptNew.Paraplatin_Planned_Other_Patients_BMS_CN__c = pt.Paraplatin_Planned_Other_Patients_BMS_CN__c;
				
			newPTList.add(ptNew);			
		}
		
		insert newPTList;
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	//Get period
	public String getPeriod(Integer shift) {
		Date nextMonth = Date.Today().addMonths(shift);
	    String s=String.ValueOf(nextMonth);
	    String[] ymd = s.split('-', -1);
	    return (ymd[0]+'/'+ymd[1]);
	}
}